/**
 * memorySection integration test — per-viewer cross-actor isolation.
 *
 * The live production path (`memorySection.build`) provisions each chat
 * participant's memories against the SPEAKER as viewer (ownerId != viewerId
 * for other participants), so `evaluateShareability`/`checkScope` genuinely
 * run cross-actor. Provision rejects `private` and `blocked` memories for a
 * non-owner BEFORE they reach the (probabilistic) injection step — so those
 * memories can NEVER appear in a non-owner's context. This test asserts that
 * guarantee deterministically: a dark-elf's private/blocked memories are
 * withheld from a human viewer in the same chat, proving the per-viewer path
 * is live (regression guard for `IDEA-memory-knowledge-isolation-and-world-timeline.md`).
 */
import { describe, expect, test, } from "bun:test";
import type { Generated, } from "kysely";
import type { ChatMode, } from "../../../db/enums-core";
import { createLogger, } from "../../../logger";
import { createTestDb, } from "../../../test-utils/create-test-db";
import {
  insertActorMemories,
  insertActors,
  insertChatParticipants,
  insertChats,
  insertUsers,
} from "../../../test-utils/insert-helpers";
import type { AssembleContext, } from "../types";
import { memorySection, } from "./memories";

describe("memorySection — per-viewer cross-actor isolation", () => {
  const elfPrivate = "elf private: the underground castle was abandoned.";
  const elfSecretBlocked = "elf blocked: the vault opens with the iron key.";
  const humanPublic = "human memory: I met a merchant at the crossroads.";
  // Insert-helper opts type generated columns as Generated<T>; cast through `unknown`
  // (plain-literals are otherwise rejected by the branded type).
  const characterScope = "character" as unknown as Generated<string>;
  const privatePrivacy = "private" as unknown as Generated<string>;
  const secretPrivacy = "secret" as unknown as Generated<string>;
  const publicPrivacy = "public" as unknown as Generated<string>;
  const storyMode = "story" as unknown as Generated<ChatMode>;

  test("withholds a non-owner's private and blocked memories from the speaker", async () => {
    // Logger must be present before migration runs (createTestDb calls runMigrations).
    try {
      createLogger({ level: "error", },);
    } catch {
      // Already initialized — ignore.
    }

    const { db, sqlite, } = await createTestDb();
    try {
      // Chat owner (users FK) + two actors participating. Ids are generated by the
      // helpers; read them back deterministically by display name / username.
      await insertUsers(db, "human", "Human",);
      await insertActors(db, "Dark Elf",);
      await insertActors(db, "Human",);
      const users = await db.selectFrom("users",).select(["id", "username",],).execute();
      const actors = await db.selectFrom("actors",).select(["id", "display_name",],).execute();
      const userId = users.find((u,) => u.username === "human")!.id;
      const elfId = actors.find((a,) => a.display_name === "Dark Elf")!.id;
      const humanId = actors.find((a,) => a.display_name === "Human")!.id;

      await insertChats(db, "Castle chat", userId, { mode: storyMode, },);
      const chat = await db.selectFrom("chats",).select(["id",],).limit(1,).executeTakeFirstOrThrow();
      const chatId = chat.id;

      await insertChatParticipants(db, chatId, elfId,);
      await insertChatParticipants(db, chatId, humanId,);

      // Elf's own memories a human must NEVER see (cross-actor withhold).
      await insertActorMemories(db, elfId, elfPrivate, {
        scope: characterScope,
        privacy: privatePrivacy,
      },);
      await insertActorMemories(db, elfId, elfSecretBlocked, {
        scope: characterScope,
        privacy: secretPrivacy,
        shareability: JSON.stringify({ blockedActorIds: [humanId,], },),
      },);

      // Human's own memory — present in their own provisioning; presence not asserted
      // (injection is probabilistic), only proves the section path runs.
      await insertActorMemories(db, humanId, humanPublic, {
        scope: characterScope,
        privacy: publicPrivacy,
      },);

      const ctx: AssembleContext = {
        db,
        actor: {
          id: humanId,
          display_name: "Human",
          system_prompt: null,
          description: null,
          personality: null,
          scenario: null,
          post_history_instructions: null,
          mes_example: null,
          agent_role: null,
        },
        chat: { id: chatId, mode: "story", world_id: null, current_location_id: null, },
        params: { actorId: humanId, chatId, modelId: "test-model", },
        isStory: false,
        tokenBudget: 4000,
      };

      const messages = await memorySection.build(ctx,);
      const output = messages.map((m,) => m.content).join("\n",);

      // The elf's private and blocked memories must never reach the human's prompt
      // (withheld at provision, before the probabilistic injection step — deterministic).
      expect(output,).not.toContain("underground castle was abandoned",);
      expect(output,).not.toContain("vault opens with the iron key",);
      // NOTE: presence of the human's own memories is intentionally NOT asserted — the
      // injection filter rolls probability (memorySection has no randomFn lever), so which
      // memories appear is non-deterministic. The withdraw guarantee above is the
      // deterministic contract this test defends.
    } finally {
      sqlite.close();
    }
  });
});
