/**
 * memorySection integration test — per-viewer cross-actor isolation.
 *
 * The live production path (`memorySection.build`) provisions each chat
 * participant's memories against the SPEAKER as viewer (ownerId != viewerId
 * for other participants), so `evaluateShareability`/`checkScope` genuinely
 * run cross-actor. Provision rejects `private` and `blocked` memories for a
 * non-owner BEFORE they reach the (probabilistic) injection step — so those
 * memories can NEVER appear in a non-owner's context. This test asserts that
 * guarantee deterministically: a dark-elf's private/blocked memories are
 * withheld from a human viewer in the same chat, proving the per-viewer path
 * is live (regression guard for `IDEA-memory-knowledge-isolation-and-world-timeline.md`).
 */
import { beforeEach, describe, expect, mock, test, } from "bun:test";
import type {} from "kysely";

import { createLogger, } from "../../../logger";
import { createTestDb, } from "../../../test-utils/create-test-db";
import {
  insertActorMemories,
  insertActors,
  insertChatParticipants,
  insertChats,
  insertUsers,
} from "../../../test-utils/insert-helpers";
import { describeOrSkip, ISOLATED, } from "../../../test-utils/isolate-only";
import type { AssembleContext, } from "../types";
import { memorySection, } from "./memories";

describe("memorySection — per-viewer cross-actor isolation", () => {
  const elfPrivate = "elf private: the underground castle was abandoned.";
  const elfSecretBlocked = "elf blocked: the vault opens with the iron key.";
  const humanPublic = "human memory: I met a merchant at the crossroads.";
  // Insert-helper opts type generated columns as Generated<T>; cast through `unknown`
  // (plain-literals are otherwise rejected by the branded type).
  const characterScope = "character";
  const privatePrivacy = "private";
  const secretPrivacy = "secret";
  const publicPrivacy = "public";
  const storyMode = "story";

  test("withholds a non-owner's private and blocked memories from the speaker", async () => {
    // Logger must be present before migration runs (createTestDb calls runMigrations).
    try {
      createLogger({ level: "error", },);
    } catch {
      // Already initialized — ignore.
    }

    const { db, sqlite, } = await createTestDb();
    try {
      // Chat owner (users FK) + two actors participating. Ids are generated by the
      // helpers; read them back deterministically by display name / username.
      await insertUsers(db, "human", "Human",);
      await insertActors(db, "Dark Elf",);
      await insertActors(db, "Human",);
      const users = await db.selectFrom("users",).select(["id", "username",],).execute();
      const actors = await db.selectFrom("actors",).select(["id", "display_name",],).execute();
      const userId = users.find((u,) => u.username === "human")!.id;
      const elfId = actors.find((a,) => a.display_name === "Dark Elf")!.id;
      const humanId = actors.find((a,) => a.display_name === "Human")!.id;

      await insertChats(db, "Castle chat", userId, { mode: storyMode, },);
      const chat = await db.selectFrom("chats",).select(["id",],).limit(1,).executeTakeFirstOrThrow();
      const chatId = chat.id;

      await insertChatParticipants(db, chatId, elfId,);
      await insertChatParticipants(db, chatId, humanId,);

      // Elf's own memories a human must NEVER see (cross-actor withhold).
      await insertActorMemories(db, elfId, elfPrivate, {
        scope: characterScope,
        privacy: privatePrivacy,
      },);
      await insertActorMemories(db, elfId, elfSecretBlocked, {
        scope: characterScope,
        privacy: secretPrivacy,
        shareability: JSON.stringify({ blockedActorIds: [humanId,], },),
      },);

      // Human's own memory — present in their own provisioning; presence not asserted
      // (injection is probabilistic), only proves the section path runs.
      await insertActorMemories(db, humanId, humanPublic, {
        scope: characterScope,
        privacy: publicPrivacy,
      },);

      const ctx: AssembleContext = {
        db,
        actor: {
          id: humanId,
          display_name: "Human",
          system_prompt: null,
          description: null,
          personality: null,
          scenario: null,
          post_history_instructions: null,
          mes_example: null,
          agent_role: null,
        },
        chat: { id: chatId, mode: "story", world_id: null, current_location_id: null, },
        params: { actorId: humanId, chatId, modelId: "test-model", },
        isStory: false,
        tokenBudget: 4000,
      };

      const messages = await memorySection.build(ctx,);
      const output = messages.map((m,) => m.content).join("\n",);

      // The elf's private and blocked memories must never reach the human's prompt
      // (withheld at provision, before the probabilistic injection step — deterministic).
      expect(output,).not.toContain("underground castle was abandoned",);
      expect(output,).not.toContain("vault opens with the iron key",);
      // NOTE: presence of the human's own memories is intentionally NOT asserted — the
      // injection filter rolls probability (memorySection has no randomFn lever), so which
      // memories appear is non-deterministic. The withdraw guarantee above is the
      // deterministic contract this test defends.
    } finally {
      sqlite.close();
    }
  });
});

// ── BUG-ollama-outage-hard-fails-all-generations ───────────────────────
// If semanticRecall throws (embed provider down), the memory section must
// degrade gracefully: keep the keyword-ranked order and still build.
// mock.module is gated to the isolated canonical gate (bun run test:unit /
// bun run check). See src/test-utils/isolate-only.ts.
if (ISOLATED) {
  mock.module("../../../memory/embeddings", () => ({
    semanticRecall: async () => {
      throw new Error("ollama: connection refused",);
    },
  }),);
}

const { memorySection: isolatedMemorySection, } = await import("./memories");

describeOrSkip("memorySection — semantic recall outage degrades gracefully", () => {
  beforeEach(async () => {
    createLogger({ level: "error", },);
  },);

  test("build still returns the keyword-ranked section when semanticRecall throws", async () => {
    const { db, sqlite, } = await createTestDb();
    try {
      await insertUsers(db, "island", "Islander",);
      const users = await db.selectFrom("users",).select("id",).execute();
      const userId = users[0]!.id;
      await insertActors(db, "Wanderer",);
      const actors = await db.selectFrom("actors",).select(["id", "display_name",],).execute();
      const actorId = actors.find((a,) => a.display_name === "Wanderer")!.id;

      await insertChats(db, "Island chat", userId,);
      const chat = await db.selectFrom("chats",).select("id",).limit(1,).executeTakeFirstOrThrow();
      await insertChatParticipants(db, chat.id, actorId,);

      // A public character-scope memory so the section has material to rank.
      await insertActorMemories(db, actorId, "The island's southern shore is calm.", {
        scope: "character",
        privacy: "public",
      },);

      const ctx: AssembleContext = {
        db,
        actor: {
          id: actorId,
          display_name: "Wanderer",
          system_prompt: null,
          description: null,
          personality: null,
          scenario: null,
          post_history_instructions: null,
          mes_example: null,
          agent_role: null,
        },
        chat: { id: chat.id, mode: "story", world_id: null, current_location_id: null, },
        params: { actorId, chatId: chat.id, modelId: "test-model", },
        isStory: false,
        tokenBudget: 4000,
      };

      // Must not throw; must return the memory section (non-empty).
      const messages = await isolatedMemorySection.build(ctx,);
      expect(messages.length,).toBeGreaterThan(0,);
      expect(messages[0]!.content,).toContain("memory_context",);
    } finally {
      sqlite.close();
    }
  });
},);
