// SPDX-License-Identifier: LGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Loop Lore Contributors

/**
 * E2E Key Store — Browser-side private key persistence (TASK-asymmetric-key-pairs-followup)
 *
 * Stores the local actor's ECDH private key as a JWK in localStorage. The
 * private key NEVER leaves the browser. The server only sees the public key
 * (registered via `server-registry.ts`).
 *
 * Security notes (v1 — localStorage):
 *   - localStorage is accessible to any JS on the origin. Injected scripts
 *     could read the key. IndexedDB with a wrapped key is the next hardening
 *     step; tracked in TASK-asymmetric-key-pairs-followup.md §"Open Questions".
 *   - For v1 we accept the same threat surface as other persisted secrets
 *     (session token, theme prefs, etc.). The protocol is designed so even a
 *     stolen private key only exposes future messages from THIS device, not
 *     past messages (sender-key ratchet is the upgrade path).
 *
 * Storage shape:
 *   - key `ll-e2e-privkey-v1` → JSON-stringified `{ actorId, keyPairJwk, algorithm, createdAt }`
 *   - key `ll-e2e-privkey-v1:${actorId}` if multiple actors ever log into the
 *     same browser (per-actor namespace).
 */

import type { KeyPairJwk, } from "../../crypto/e2e/key-pairs";
import { generateKeyPair, importKeyPair, } from "../../crypto/e2e/key-pairs";
import { exportPrivateJwk, exportPublicJwk, } from "../../crypto/e2e/key-pairs";

const STORAGE_PREFIX = "ll-e2e-privkey-v1";
const DEFAULT_ALGORITHM = "ECDH-P256" as const;

export interface StoredKeyPair {
  actorId: string;
  keyPairJwk: KeyPairJwk;
  algorithm: string;
  createdAt: string;
}

export interface LoadOrCreateOpts {
  actorId: string;
  /** If true, generate a new key pair even if one already exists (rotation). */
  rotate?: boolean;
}

export interface LoadOrCreateResult {
  /** The local actor's full key pair (both keys as `CryptoKey` handles). */
  cryptoKeyPair: CryptoKeyPair;
  /** The public-key JWK to upload to the server registry. */
  publicKeyJwk: JsonWebKey;
  /** Whether a new key pair was generated by this call. */
  created: boolean;
}

/**
 * Load the persisted key pair for the given actor, or create a new one if
 * none exists. Always returns runtime `CryptoKey` handles ready for use.
 *
 * The private key is imported as non-extractable (cannot be re-exported after
 * this call). Use `getStoredKeyPair` to retrieve the persisted JWK for backup.
 */
export async function loadOrCreateKeyPair(opts: LoadOrCreateOpts,): Promise<LoadOrCreateResult> {
  const existing = opts.rotate ? null : getStoredKeyPair(opts.actorId,);
  if (existing) {
    const cryptoKeyPair = await importKeyPair(existing.keyPairJwk,);
    return { cryptoKeyPair, publicKeyJwk: existing.keyPairJwk.publicKey, created: false, };
  }

  const generated = await generateKeyPair({ extractable: true, },);
  const publicKeyJwk = await exportPublicJwk(generated.publicKey,);
  const privateKeyJwk = await exportPrivateJwk(generated.privateKey,);

  const stored: StoredKeyPair = {
    actorId: opts.actorId,
    keyPairJwk: { publicKey: publicKeyJwk, privateKey: privateKeyJwk, },
    algorithm: DEFAULT_ALGORITHM,
    createdAt: new Date().toISOString(),
  };
  persistStoredKeyPair(stored,);

  // Re-import as non-extractable for runtime use.
  const cryptoKeyPair = await importKeyPair(stored.keyPairJwk, { extractablePrivate: false, },);
  return { cryptoKeyPair, publicKeyJwk, created: true, };
}

/**
 * Read the persisted key pair for the given actor (JWK form). Returns null
 * if no key pair is stored. Use this for backup/export flows — runtime code
 * should call `loadOrCreateKeyPair` instead.
 */
export function getStoredKeyPair(actorId: string,): StoredKeyPair | null {
  const raw = localStorage.getItem(storageKey(actorId,),);
  if (!raw) { return null; }
  try {
    const parsed: unknown = JSON.parse(raw,);
    return isStoredKeyPair(parsed,) ? parsed : null;
  } catch {
    return null;
  }
}

/**
 * Delete the persisted key pair for the given actor. Used when the user
 * explicitly revokes their key on a device. The corresponding row in
 * `actor_e2e_pubkeys` is NOT deleted automatically — call
 * `server-registry.revokePublicKey` for that.
 */
export function deleteStoredKeyPair(actorId: string,): void {
  localStorage.removeItem(storageKey(actorId,),);
}

/** List all actor IDs that have a persisted key pair on this device. */
export function listStoredActorIds(): string[] {
  const ids: string[] = [];
  for (let i = 0; i < localStorage.length; i++) {
    const key = localStorage.key(i,);
    if (key && key.startsWith(`${STORAGE_PREFIX}:`,)) {
      ids.push(key.slice(`${STORAGE_PREFIX}:`.length,),);
    }
  }
  return ids;
}

function storageKey(actorId: string,): string {
  return `${STORAGE_PREFIX}:${actorId}`;
}

function persistStoredKeyPair(stored: StoredKeyPair,): void {
  try {
    localStorage.setItem(storageKey(stored.actorId,), JSON.stringify(stored,),);
  } catch {
    // Quota or serialization error — silently skip. Backup is the user's
    // responsibility via the export flow.
  }
}

function isStoredKeyPair(value: unknown,): value is StoredKeyPair {
  if (typeof value !== "object" || value === null) { return false; }
  const v = value as Record<string, unknown>;
  if (typeof v["actorId"] !== "string") { return false; }
  if (typeof v["algorithm"] !== "string") { return false; }
  if (typeof v["createdAt"] !== "string") { return false; }
  if (typeof v["keyPairJwk"] !== "object" || v["keyPairJwk"] === null) { return false; }
  const jwk = v["keyPairJwk"] as Record<string, unknown>;
  if (typeof jwk["publicKey"] !== "object" || jwk["publicKey"] === null) { return false; }
  if (typeof jwk["privateKey"] !== "object" || jwk["privateKey"] === null) { return false; }
  return true;
}
