// SPDX-License-Identifier: LGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Loop Lore Contributors

/**
 * E2E Public Keys Registry (TASK-asymmetric-key-pairs-followup)
 *
 * Stores per-actor ECDH public keys so the server can relay them to other
 * participants without ever holding the private key. Private keys live on the
 * client only; the server cannot decrypt E2E chats.
 *
 * Columns:
 *   - id              : primary key (text, generated by app)
 *   - actor_id        : FK → actors.id (UNIQUE — one active pubkey per actor)
 *   - public_key_jwk  : JSON-stringified JWK (raw public EC point)
 *   - algorithm       : crypto algo name ("ECDH-P256" for v1; extensible)
 *   - created_at      : ISO timestamp
 *   - expires_at      : optional rotation/expiry timestamp (null = no expiry)
 *   - revoked_at      : soft-revoke marker (null = active)
 *
 * Indexes:
 *   - uniq(actor_id) — only one active pubkey per actor; rotation uses
 *     UPDATE + soft-revoke on the old row.
 *
 * Threat model:
 *   - Server stores PUBLIC keys only. Private keys never reach the server.
 *   - Revoked keys remain on disk for audit but are filtered out at read time.
 *   - Public-key rotation is opt-in (rotation ratchet is out of scope for v1).
 */
import type { Kysely, } from "kysely";
import { sql, } from "kysely";

export async function up(db: Kysely<unknown>,): Promise<void> {
  await db.schema
    .createTable("actor_e2e_pubkeys",)
    .addColumn("id", "text", (col,) => col.primaryKey(),)
    .addColumn("actor_id", "text", (col,) => col.notNull().references("actors.id",).onDelete("cascade",),)
    .addColumn("public_key_jwk", "text", (col,) => col.notNull(),)
    .addColumn("algorithm", "text", (col,) => col.notNull().defaultTo("ECDH-P256",),)
    .addColumn("created_at", "text", (col,) => col.notNull().defaultTo(sql`(datetime('now'))`,),)
    .addColumn("expires_at", "text",)
    .addColumn("revoked_at", "text",)
    .execute();

  // Non-unique lookup index. "Only one active row per actor" is enforced
  // in application code (registerPublicKey soft-revokes the old row before
  // inserting a new one; reads filter by `revoked_at IS NULL`). A non-unique
  // index lets audit history of revoked keys coexist with the active row.
  await db.schema
    .createIndex("idx_actor_e2e_pubkeys_actor_id",)
    .on("actor_e2e_pubkeys",)
    .column("actor_id",)
    .execute();

  await db.schema
    .createIndex("idx_actor_e2e_pubkeys_revoked",)
    .on("actor_e2e_pubkeys",)
    .column("revoked_at",)
    .execute();
}

export async function down(db: Kysely<unknown>,): Promise<void> {
  await db.schema.dropIndex("idx_actor_e2e_pubkeys_revoked",).execute();
  await db.schema.dropIndex("idx_actor_e2e_pubkeys_actor_id",).execute();
  await db.schema.dropTable("actor_e2e_pubkeys",).execute();
}
