// SPDX-License-Identifier: LGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Loop Lore Contributors
// AUTO-GENERATED by scripts/generate-schema-fuzz.ts — DO NOT EDIT MANUALLY.
// Regenerate: bun run scripts/generate-schema-fuzz.ts

/**
 * Schema fuzz (property) tests for the validation schema barrel.
 *
 * Each `describe` block is one exported TypeBox schema. Arbitraries come
 * from `@/test-utils/schema-arbitrary`, which only emits schema-valid
 * values — a failure here means the mapper drifted from the schema.
 */

import type { TSchema, } from "@sinclair/typebox";
import { Value, } from "@sinclair/typebox/value";
import { describe, expect, test, } from "bun:test";
import fc from "fast-check";

import { schemaToArbitrary, } from "@/test-utils/schema-arbitrary";
import * as schemas from "@/validation/schemas";

/** Fixed run count + seed — a regenerated file must replay identical values. */
const FC_RUNS = { numRuns: 100, seed: 20260101, };

/** Every generated value must satisfy its own schema. */
function checkAllValid(schema: TSchema,): void {
  fc.assert(
    fc.property(schemaToArbitrary(schema,), (v,) => Value.Check(schema, v,) === true,),
    FC_RUNS,
  );
}

/** JSON.stringify must be lossless — no dropped keys, no coerced values. */
function checkJsonRoundTrip(schema: TSchema,): void {
  fc.assert(
    fc.property(schemaToArbitrary(schema,), (v,) => {
      const round: unknown = JSON.parse(JSON.stringify(v,),);
      expect(round,).toEqual(v,);
    },),
    FC_RUNS,
  );
}

describe("ActorCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.ActorCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ActorCreateBody,));
});

describe("ActorEmotionParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.ActorEmotionParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ActorEmotionParams,));
});

describe("ActorIdAssetIdParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.ActorIdAssetIdParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ActorIdAssetIdParams,));
});

describe("ActorIdAvatarIdParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.ActorIdAvatarIdParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ActorIdAvatarIdParams,));
});

describe("ActorIdAvatarParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.ActorIdAvatarParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ActorIdAvatarParams,));
});

describe("ActorIdParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.ActorIdParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ActorIdParams,));
});

describe("ActorTargetParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.ActorTargetParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ActorTargetParams,));
});

describe("ActorTypeSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.ActorTypeSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ActorTypeSchema,));
});

describe("ActorUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.ActorUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ActorUpdateBody,));
});

describe("ActorVisibilitySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.ActorVisibilitySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ActorVisibilitySchema,));
});

describe("ActorsQuery", () => {
  test("accepts generated values", () => checkAllValid(schemas.ActorsQuery,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ActorsQuery,));
});

describe("AddAssetTagBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.AddAssetTagBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AddAssetTagBody,));
});

describe("AdminChatUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.AdminChatUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AdminChatUpdateBody,));
});

describe("AdminModelRoleOverrideBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.AdminModelRoleOverrideBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AdminModelRoleOverrideBody,));
});

describe("AdminOverrideCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.AdminOverrideCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AdminOverrideCreateBody,));
});

describe("AdminRoleUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.AdminRoleUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AdminRoleUpdateBody,));
});

describe("AdminSystemConfigBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.AdminSystemConfigBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AdminSystemConfigBody,));
});

describe("AdminSystemConfigImportBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.AdminSystemConfigImportBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AdminSystemConfigImportBody,));
});

describe("AdminTemplateCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.AdminTemplateCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AdminTemplateCreateBody,));
});

describe("AdminTemplateUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.AdminTemplateUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AdminTemplateUpdateBody,));
});

describe("AgentTypeSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.AgentTypeSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AgentTypeSchema,));
});

describe("ApiKeyCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.ApiKeyCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ApiKeyCreateBody,));
});

describe("AssetSearchQuery", () => {
  test("accepts generated values", () => checkAllValid(schemas.AssetSearchQuery,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AssetSearchQuery,));
});

describe("AssetSearchResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.AssetSearchResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AssetSearchResponse,));
});

describe("AssetSearchResult", () => {
  test("accepts generated values", () => checkAllValid(schemas.AssetSearchResult,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AssetSearchResult,));
});

describe("AssetTagListResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.AssetTagListResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AssetTagListResponse,));
});

describe("AssetTagRecordSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.AssetTagRecordSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AssetTagRecordSchema,));
});

describe("AssetTagResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.AssetTagResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AssetTagResponse,));
});

describe("AssetTagScopeSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.AssetTagScopeSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AssetTagScopeSchema,));
});

describe("AssetTagSourceSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.AssetTagSourceSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AssetTagSourceSchema,));
});

describe("AssetTypeSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.AssetTypeSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AssetTypeSchema,));
});

describe("AssetVisibilitySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.AssetVisibilitySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AssetVisibilitySchema,));
});

describe("AvailabilityBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.AvailabilityBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AvailabilityBody,));
});

describe("AvatarConfigBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.AvatarConfigBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AvatarConfigBody,));
});

describe("AvatarCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.AvatarCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AvatarCreateBody,));
});

describe("AvatarResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.AvatarResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AvatarResponse,));
});

describe("AvatarSelectBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.AvatarSelectBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AvatarSelectBody,));
});

describe("AvatarUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.AvatarUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.AvatarUpdateBody,));
});

describe("BatchIdsBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.BatchIdsBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.BatchIdsBody,));
});

describe("BlogCommentCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.BlogCommentCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.BlogCommentCreateBody,));
});

describe("BlogCommentResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.BlogCommentResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.BlogCommentResponse,));
});

describe("BlogPostCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.BlogPostCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.BlogPostCreateBody,));
});

describe("BlogPostResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.BlogPostResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.BlogPostResponse,));
});

describe("BlogPostStatusBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.BlogPostStatusBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.BlogPostStatusBody,));
});

describe("BlogPostUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.BlogPostUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.BlogPostUpdateBody,));
});

describe("CharacterEmotionBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.CharacterEmotionBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.CharacterEmotionBody,));
});

describe("CharacterSystemsExportBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.CharacterSystemsExportBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.CharacterSystemsExportBody,));
});

describe("CharacterSystemsImportUrlBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.CharacterSystemsImportUrlBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.CharacterSystemsImportUrlBody,));
});

describe("ChatAutoTranslateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatAutoTranslateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatAutoTranslateBody,));
});

describe("ChatCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatCreateBody,));
});

describe("ChatHistoryCarrySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatHistoryCarrySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatHistoryCarrySchema,));
});

describe("ChatIdParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatIdParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatIdParams,));
});

describe("ChatImpersonateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatImpersonateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatImpersonateBody,));
});

describe("ChatLocationUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatLocationUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatLocationUpdateBody,));
});

describe("ChatMarkReadBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatMarkReadBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatMarkReadBody,));
});

describe("ChatMigrateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatMigrateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatMigrateBody,));
});

describe("ChatMigrateCarrySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatMigrateCarrySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatMigrateCarrySchema,));
});

describe("ChatModeSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatModeSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatModeSchema,));
});

describe("ChatOutfitOverrideBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatOutfitOverrideBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatOutfitOverrideBody,));
});

describe("ChatParticipantParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatParticipantParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatParticipantParams,));
});

describe("ChatParticipantRoleSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatParticipantRoleSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatParticipantRoleSchema,));
});

describe("ChatParticipantUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatParticipantUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatParticipantUpdateBody,));
});

describe("ChatPersonaUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatPersonaUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatPersonaUpdateBody,));
});

describe("ChatRenameBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatRenameBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatRenameBody,));
});

describe("ChatRenderingOverrideSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatRenderingOverrideSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatRenderingOverrideSchema,));
});

describe("ChatSetupTemplateCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatSetupTemplateCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatSetupTemplateCreateBody,));
});

describe("ChatSetupTemplateSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatSetupTemplateSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatSetupTemplateSchema,));
});

describe("ChatSetupTemplateUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatSetupTemplateUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatSetupTemplateUpdateBody,));
});

describe("ChatTypeSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatTypeSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatTypeSchema,));
});

describe("ChatUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatUpdateBody,));
});

describe("ChatVisibilitySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.ChatVisibilitySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ChatVisibilitySchema,));
});

describe("ContentEncodingSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.ContentEncodingSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ContentEncodingSchema,));
});

describe("ContentRatingSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.ContentRatingSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ContentRatingSchema,));
});

describe("DismissTagPropositionBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.DismissTagPropositionBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.DismissTagPropositionBody,));
});

describe("DisplayName", () => {
  test("accepts generated values", () => checkAllValid(schemas.DisplayName,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.DisplayName,));
});

describe("EmotionDefinitionCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.EmotionDefinitionCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.EmotionDefinitionCreateBody,));
});

describe("EncryptionLevelSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.EncryptionLevelSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.EncryptionLevelSchema,));
});

describe("EntityCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.EntityCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.EntityCreateBody,));
});

describe("EntityReviewStatusSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.EntityReviewStatusSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.EntityReviewStatusSchema,));
});

describe("EntityScopeSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.EntityScopeSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.EntityScopeSchema,));
});

describe("EntityScopeUpdateSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.EntityScopeUpdateSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.EntityScopeUpdateSchema,));
});

describe("EntityUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.EntityUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.EntityUpdateBody,));
});

describe("ErrorResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.ErrorResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ErrorResponse,));
});

describe("GameStateAnalysisSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.GameStateAnalysisSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.GameStateAnalysisSchema,));
});

describe("GameStateEntitySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.GameStateEntitySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.GameStateEntitySchema,));
});

describe("GameStateItemSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.GameStateItemSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.GameStateItemSchema,));
});

describe("GameStateMovementSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.GameStateMovementSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.GameStateMovementSchema,));
});

describe("GameStateSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.GameStateSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.GameStateSchema,));
});

describe("GenerationStatusSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.GenerationStatusSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.GenerationStatusSchema,));
});

describe("GmConfigSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.GmConfigSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.GmConfigSchema,));
});

describe("GmGuidanceSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.GmGuidanceSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.GmGuidanceSchema,));
});

describe("GmGuidanceUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.GmGuidanceUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.GmGuidanceUpdateBody,));
});

describe("GmTurnPrioritySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.GmTurnPrioritySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.GmTurnPrioritySchema,));
});

describe("Id", () => {
  test("accepts generated values", () => checkAllValid(schemas.Id,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.Id,));
});

describe("InviteChatParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.InviteChatParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.InviteChatParams,));
});

describe("InviteCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.InviteCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.InviteCreateBody,));
});

describe("InviteJoinParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.InviteJoinParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.InviteJoinParams,));
});

describe("InviteParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.InviteParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.InviteParams,));
});

describe("InviteSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.InviteSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.InviteSchema,));
});

describe("ItemCategorySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.ItemCategorySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ItemCategorySchema,));
});

describe("ItemRaritySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.ItemRaritySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ItemRaritySchema,));
});

describe("LicensingBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.LicensingBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.LicensingBody,));
});

describe("LlmTemplateSectionSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.LlmTemplateSectionSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.LlmTemplateSectionSchema,));
});

describe("LocationOutfitBindingsBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.LocationOutfitBindingsBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.LocationOutfitBindingsBody,));
});

describe("LocationStateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.LocationStateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.LocationStateBody,));
});

describe("LocationTraitCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.LocationTraitCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.LocationTraitCreateBody,));
});

describe("LocationTraitUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.LocationTraitUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.LocationTraitUpdateBody,));
});

describe("LoginBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.LoginBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.LoginBody,));
});

describe("LoreEntrySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.LoreEntrySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.LoreEntrySchema,));
});

describe("LorePositionSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.LorePositionSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.LorePositionSchema,));
});

describe("LoreScopeSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.LoreScopeSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.LoreScopeSchema,));
});

describe("LoreSubjectBaseSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.LoreSubjectBaseSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.LoreSubjectBaseSchema,));
});

describe("LoreSubjectKindSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.LoreSubjectKindSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.LoreSubjectKindSchema,));
});

describe("LoreSubjectSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.LoreSubjectSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.LoreSubjectSchema,));
});

describe("MemoryCarrySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.MemoryCarrySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MemoryCarrySchema,));
});

describe("MemoryTypeSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.MemoryTypeSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MemoryTypeSchema,));
});

describe("MessageAiActionBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.MessageAiActionBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MessageAiActionBody,));
});

describe("MessageAttachmentSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.MessageAttachmentSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MessageAttachmentSchema,));
});

describe("MessageContentTypeSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.MessageContentTypeSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MessageContentTypeSchema,));
});

describe("MessageCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.MessageCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MessageCreateBody,));
});

describe("MessageForwardBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.MessageForwardBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MessageForwardBody,));
});

describe("MessageIdParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.MessageIdParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MessageIdParams,));
});

describe("MessageRoleSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.MessageRoleSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MessageRoleSchema,));
});

describe("MessageSearchQuery", () => {
  test("accepts generated values", () => checkAllValid(schemas.MessageSearchQuery,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MessageSearchQuery,));
});

describe("MessageSearchResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.MessageSearchResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MessageSearchResponse,));
});

describe("MessageSearchResult", () => {
  test("accepts generated values", () => checkAllValid(schemas.MessageSearchResult,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MessageSearchResult,));
});

describe("MessageStatusSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.MessageStatusSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MessageStatusSchema,));
});

describe("MessageStatusUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.MessageStatusUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MessageStatusUpdateBody,));
});

describe("MessageVariantQuery", () => {
  test("accepts generated values", () => checkAllValid(schemas.MessageVariantQuery,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MessageVariantQuery,));
});

describe("MessageVisibilitySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.MessageVisibilitySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MessageVisibilitySchema,));
});

describe("MessageVisibilityUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.MessageVisibilityUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MessageVisibilityUpdateBody,));
});

describe("MessagesQuery", () => {
  test("accepts generated values", () => checkAllValid(schemas.MessagesQuery,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MessagesQuery,));
});

describe("MoodCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.MoodCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MoodCreateBody,));
});

describe("MoodDeltaBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.MoodDeltaBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MoodDeltaBody,));
});

describe("MoodEventBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.MoodEventBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MoodEventBody,));
});

describe("MoodStateResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.MoodStateResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MoodStateResponse,));
});

describe("MoodUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.MoodUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MoodUpdateBody,));
});

describe("MusicLinkMessageSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.MusicLinkMessageSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.MusicLinkMessageSchema,));
});

describe("Name", () => {
  test("accepts generated values", () => checkAllValid(schemas.Name,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.Name,));
});

describe("NoteCategorySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.NoteCategorySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.NoteCategorySchema,));
});

describe("NotificationPreferencesBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.NotificationPreferencesBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.NotificationPreferencesBody,));
});

describe("NpcStateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.NpcStateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.NpcStateBody,));
});

describe("NullableChatRenderingOverrideSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.NullableChatRenderingOverrideSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.NullableChatRenderingOverrideSchema,));
});

describe("NullableId", () => {
  test("accepts generated values", () => checkAllValid(schemas.NullableId,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.NullableId,));
});

describe("OptionalId", () => {
  test("accepts generated values", () => checkAllValid(schemas.OptionalId,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.OptionalId,));
});

describe("OutfitGenerateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.OutfitGenerateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.OutfitGenerateBody,));
});

describe("OutfitGenerateSingleBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.OutfitGenerateSingleBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.OutfitGenerateSingleBody,));
});

describe("OutfitResolveBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.OutfitResolveBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.OutfitResolveBody,));
});

describe("OutputStylePresetSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.OutputStylePresetSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.OutputStylePresetSchema,));
});

describe("PaginationQuery", () => {
  test("accepts generated values", () => checkAllValid(schemas.PaginationQuery,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.PaginationQuery,));
});

describe("PinnedStateSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.PinnedStateSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.PinnedStateSchema,));
});

describe("QuestCategorySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.QuestCategorySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.QuestCategorySchema,));
});

describe("QuestCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.QuestCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.QuestCreateBody,));
});

describe("QuestProgressBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.QuestProgressBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.QuestProgressBody,));
});

describe("QuestResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.QuestResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.QuestResponse,));
});

describe("QuestStatusSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.QuestStatusSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.QuestStatusSchema,));
});

describe("QuestTypeSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.QuestTypeSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.QuestTypeSchema,));
});

describe("QuestUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.QuestUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.QuestUpdateBody,));
});

describe("QuickReplyTriggerSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.QuickReplyTriggerSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.QuickReplyTriggerSchema,));
});

describe("RelationshipCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.RelationshipCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.RelationshipCreateBody,));
});

describe("RelationshipEventBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.RelationshipEventBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.RelationshipEventBody,));
});

describe("RelationshipResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.RelationshipResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.RelationshipResponse,));
});

describe("RelationshipUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.RelationshipUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.RelationshipUpdateBody,));
});

describe("RemoveAssetTagBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.RemoveAssetTagBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.RemoveAssetTagBody,));
});

describe("RenameAssetTagBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.RenameAssetTagBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.RenameAssetTagBody,));
});

describe("SettingsUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.SettingsUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.SettingsUpdateBody,));
});

describe("StorageBackendSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.StorageBackendSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.StorageBackendSchema,));
});

describe("StoryItemInstanceBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.StoryItemInstanceBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.StoryItemInstanceBody,));
});

describe("StoryItemResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.StoryItemResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.StoryItemResponse,));
});

describe("StoryTurnCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.StoryTurnCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.StoryTurnCreateBody,));
});

describe("SuccessResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.SuccessResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.SuccessResponse,));
});

describe("TagAutocompleteResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.TagAutocompleteResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TagAutocompleteResponse,));
});

describe("TagPropositionListResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.TagPropositionListResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TagPropositionListResponse,));
});

describe("TagPropositionSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.TagPropositionSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TagPropositionSchema,));
});

describe("TagProvenanceSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.TagProvenanceSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TagProvenanceSchema,));
});

describe("TelemetryAnalyticsErrorsRow", () => {
  test("accepts generated values", () => checkAllValid(schemas.TelemetryAnalyticsErrorsRow,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TelemetryAnalyticsErrorsRow,));
});

describe("TelemetryEventBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.TelemetryEventBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TelemetryEventBody,));
});

describe("TemplateApplyBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.TemplateApplyBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TemplateApplyBody,));
});

describe("TemplateCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.TemplateCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TemplateCreateBody,));
});

describe("TemplateDetailLevelSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.TemplateDetailLevelSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TemplateDetailLevelSchema,));
});

describe("TemplateImportBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.TemplateImportBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TemplateImportBody,));
});

describe("TemplateImportResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.TemplateImportResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TemplateImportResponse,));
});

describe("TemplateModalitySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.TemplateModalitySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TemplateModalitySchema,));
});

describe("TemplateSummaryResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.TemplateSummaryResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TemplateSummaryResponse,));
});

describe("TemplateUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.TemplateUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TemplateUpdateBody,));
});

describe("ThinkingVisibilitySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.ThinkingVisibilitySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.ThinkingVisibilitySchema,));
});

describe("TraitCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.TraitCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TraitCreateBody,));
});

describe("TraitResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.TraitResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TraitResponse,));
});

describe("TraitUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.TraitUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TraitUpdateBody,));
});

describe("TurnSkipBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.TurnSkipBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TurnSkipBody,));
});

describe("TurnStatusSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.TurnStatusSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TurnStatusSchema,));
});

describe("TurnStrategySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.TurnStrategySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TurnStrategySchema,));
});

describe("TurnTypeSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.TurnTypeSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.TurnTypeSchema,));
});

describe("UserIdParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.UserIdParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.UserIdParams,));
});

describe("UserProfileUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.UserProfileUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.UserProfileUpdateBody,));
});

describe("UserRoleSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.UserRoleSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.UserRoleSchema,));
});

describe("UserStatusSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.UserStatusSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.UserStatusSchema,));
});

describe("WardrobeActorParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.WardrobeActorParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WardrobeActorParams,));
});

describe("WardrobeBindBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.WardrobeBindBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WardrobeBindBody,));
});

describe("WardrobeBindingParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.WardrobeBindingParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WardrobeBindingParams,));
});

describe("WardrobeChatParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.WardrobeChatParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WardrobeChatParams,));
});

describe("WardrobeItemCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.WardrobeItemCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WardrobeItemCreateBody,));
});

describe("WardrobeItemParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.WardrobeItemParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WardrobeItemParams,));
});

describe("WardrobeItemUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.WardrobeItemUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WardrobeItemUpdateBody,));
});

describe("WorldActorParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.WorldActorParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WorldActorParams,));
});

describe("WorldAvatarConfigBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.WorldAvatarConfigBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WorldAvatarConfigBody,));
});

describe("WorldCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.WorldCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WorldCreateBody,));
});

describe("WorldEventTypeSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.WorldEventTypeSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WorldEventTypeSchema,));
});

describe("WorldIdParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.WorldIdParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WorldIdParams,));
});

describe("WorldInviteParams", () => {
  test("accepts generated values", () => checkAllValid(schemas.WorldInviteParams,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WorldInviteParams,));
});

describe("WorldInviteSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.WorldInviteSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WorldInviteSchema,));
});

describe("WorldKindSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.WorldKindSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WorldKindSchema,));
});

describe("WorldSetupInventoryItemSchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.WorldSetupInventoryItemSchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WorldSetupInventoryItemSchema,));
});

describe("WorldSetupLoreEntrySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.WorldSetupLoreEntrySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WorldSetupLoreEntrySchema,));
});

describe("WorldSetupResolvedResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.WorldSetupResolvedResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WorldSetupResolvedResponse,));
});

describe("WorldSetupResponse", () => {
  test("accepts generated values", () => checkAllValid(schemas.WorldSetupResponse,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WorldSetupResponse,));
});

describe("WorldSetupUpsertBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.WorldSetupUpsertBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WorldSetupUpsertBody,));
});

describe("WorldStateCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.WorldStateCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WorldStateCreateBody,));
});

describe("WorldTraitCreateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.WorldTraitCreateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WorldTraitCreateBody,));
});

describe("WorldUpdateBody", () => {
  test("accepts generated values", () => checkAllValid(schemas.WorldUpdateBody,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WorldUpdateBody,));
});

describe("WorldVisibilitySchema", () => {
  test("accepts generated values", () => checkAllValid(schemas.WorldVisibilitySchema,));
  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.WorldVisibilitySchema,));
});

// 221 schemas discovered by scripts/generate-schema-fuzz.ts.
