/**
 * Test Insert Helpers — Auto-generated
 *
 * Typed functions for inserting test data. Required fields are params,
 * optional fields use defaults or accept undefined.
 *
 * Auto-generated by scripts/generate-db-types.ts
 * DO NOT EDIT MANUALLY — run `bun run db:sync-types` to regenerate.
 */
import type { Kysely, } from "kysely";
import type { DB, } from "../db/schema";

type Db = Kysely<DB>;

/** Insert a users row. */
export function insertUsers(db: Db, username: string, display_name: string, opts?: { id?: Generated<string>; password_hash?: string | null; role?: Generated<UserRole>; status?: Generated<UserStatus>; settings?: Generated<string>; birth_date?: string | null; age_gate_accepted_at?: string | null; created_at?: Generated<string>; last_seen_at?: string | null; format_version?: Generated<number> }): Promise<void> {
  return db.insertInto("users",).values({
    id: crypto.randomUUID(),
    username,
    display_name,
    ...opts,
  },).execute();
}

/** Insert a sessions row. */
export function insertSessions(db: Db, user_id: string, token_hash: string, expires_at: string, opts?: { id?: Generated<string>; ip?: string | null; user_agent?: string | null; created_at?: Generated<string>; last_activity?: Generated<string> }): Promise<void> {
  return db.insertInto("sessions",).values({
    id: crypto.randomUUID(),
    user_id,
    token_hash,
    expires_at,
    ...opts,
  },).execute();
}

/** Insert a assets row. */
export function insertAssets(db: Db, owner_id: string, filename: string, mime_type: string, asset_type: AssetType, size_bytes: number, storage_path: string, opts?: { id?: Generated<string>; storage_backend?: Generated<StorageBackend>; width?: number | null; height?: number | null; duration_secs?: number | null; alt_text?: string | null; visibility?: Generated<AssetVisibility>; created_at?: Generated<string>; encryption_tier?: Generated<string>; encrypted_key_id?: string | null }): Promise<void> {
  return db.insertInto("assets",).values({
    id: crypto.randomUUID(),
    owner_id,
    filename,
    mime_type,
    asset_type,
    size_bytes,
    storage_path,
    ...opts,
  },).execute();
}

/** Insert a asset_links row. */
export function insertAssetLinks(db: Db, asset_id: string, entity_type: AssetLinkEntity, entity_id: string, opts?: { label?: string | null; sort_order?: Generated<number>; created_at?: Generated<string> }): Promise<void> {
  return db.insertInto("asset_links",).values({
    asset_id,
    entity_type,
    entity_id,
    ...opts,
  },).execute();
}

/** Insert a asset_shares row. */
export function insertAssetShares(db: Db, asset_id: string, shared_with_id: string, shared_by_id: string, opts?: { id?: Generated<string>; created_at?: Generated<string> }): Promise<void> {
  return db.insertInto("asset_shares",).values({
    id: crypto.randomUUID(),
    asset_id,
    shared_with_id,
    shared_by_id,
    ...opts,
  },).execute();
}

/** Insert a personas row. */
export function insertPersonas(db: Db, user_id: string, name: string, opts?: { id?: Generated<string>; avatar_asset_id?: string | null; description?: string | null; title?: string | null; is_default?: Generated<string>; created_at?: Generated<string>; updated_at?: Generated<string>; format_version?: Generated<number> }): Promise<void> {
  return db.insertInto("personas",).values({
    id: crypto.randomUUID(),
    user_id,
    name,
    ...opts,
  },).execute();
}

/** Insert a group_initiatives row. */
export function insertGroupInitiatives(db: Db, chat_id: string, scene_id: string, actor_id: string, opts?: { score?: Generated<number>; created_at?: Generated<string>; updated_at?: Generated<string> }): Promise<void> {
  return db.insertInto("group_initiatives",).values({
    chat_id,
    scene_id,
    actor_id,
    ...opts,
  },).execute();
}

/** Insert a chat_mentions row. */
export function insertChatMentions(db: Db, message_id: string, actor_id: string, opts?: { id?: Generated<string>; created_at?: Generated<string> }): Promise<void> {
  return db.insertInto("chat_mentions",).values({
    id: crypto.randomUUID(),
    message_id,
    actor_id,
    ...opts,
  },).execute();
}

/** Insert a worlds row. */
export function insertWorlds(db: Db, owner_id: string, name: string, opts?: { id?: Generated<string>; description?: string | null; lore?: string | null; scan_depth?: Generated<number>; token_budget?: Generated<number>; difficulty_modifier?: Generated<number>; difficulty_reroll?: Generated<DifficultyReroll>; difficulty_state?: Generated<DifficultyState>; created_at?: Generated<string>; updated_at?: Generated<string>; nsfw_override?: string | null }): Promise<void> {
  return db.insertInto("worlds",).values({
    id: crypto.randomUUID(),
    owner_id,
    name,
    ...opts,
  },).execute();
}

/** Insert a locations row. */
export function insertLocations(db: Db, world_id: string, name: string, opts?: { id?: Generated<string>; description?: string | null; connections?: Generated<string>; parent_location_id?: string | null; created_at?: Generated<string>; updated_at?: Generated<string> }): Promise<void> {
  return db.insertInto("locations",).values({
    id: crypto.randomUUID(),
    world_id,
    name,
    ...opts,
  },).execute();
}

/** Insert a items row. */
export function insertItems(db: Db, world_id: string, name: string, category: ItemCategory, opts?: { id?: Generated<string>; description?: string | null; rarity?: Generated<ItemRarity>; stackable?: Generated<StackableState>; max_stack?: Generated<number>; properties?: Generated<string>; value?: Generated<number>; weight?: Generated<number>; created_at?: Generated<string>; updated_at?: Generated<string> }): Promise<void> {
  return db.insertInto("items",).values({
    id: crypto.randomUUID(),
    world_id,
    name,
    category,
    ...opts,
  },).execute();
}

/** Insert a world_lore_entries row. */
export function insertWorldLoreEntries(db: Db, world_id: string, content: string, opts?: { id?: Generated<string>; name?: string | null; keys?: Generated<string>; secondary_keys?: string | null; selective?: Generated<number>; case_sensitive?: Generated<number>; enabled?: Generated<LoreEntryStatus>; constant?: Generated<number>; position?: Generated<LorePosition>; insertion_order?: Generated<number>; priority?: Generated<number>; comment?: string | null; sort_order?: Generated<number>; created_at?: Generated<string>; updated_at?: Generated<string>; cooldown_seconds?: Generated<number>; last_activated?: string | null }): Promise<void> {
  return db.insertInto("world_lore_entries",).values({
    id: crypto.randomUUID(),
    world_id,
    content,
    ...opts,
  },).execute();
}

/** Insert a chats row. */
export function insertChats(db: Db, name: string, created_by: string, opts?: { id?: Generated<string>; type?: Generated<ChatType>; mode?: Generated<ChatMode>; world_id?: string | null; current_location_id?: string | null; story_state?: string | null; gm_config?: string | null; turn_strategy?: TurnStrategy | null; max_turns?: number | null; auto_advance?: number | null; encryption_level?: Generated<string>; response_length_preset?: Generated<string>; response_length_custom?: number | null; context_max_tokens?: number | null; created_at?: Generated<string>; updated_at?: Generated<string>; is_pinned?: Generated<string>; parent_chat_id?: string | null; visual_novel?: Generated<number>; streaming?: number | null; nsfw_override?: string | null; name_source?: string | null }): Promise<void> {
  return db.insertInto("chats",).values({
    id: crypto.randomUUID(),
    name,
    created_by,
    ...opts,
  },).execute();
}

/** Insert a actors row. */
export function insertActors(db: Db, display_name: string, opts?: { id?: Generated<string>; actor_type?: Generated<ActorType>; user_id?: string | null; owner_id?: string | null; avatar_asset_id?: string | null; description?: string | null; system_prompt?: string | null; agent_type?: Generated<AgentType>; settings?: Generated<string>; format_version?: Generated<number>; visibility?: Generated<string>; welcome_message?: string | null; personality?: string | null; scenario?: string | null; mes_example?: string | null; alternate_greetings?: string | null; post_history_instructions?: string | null; creator_notes?: string | null; creator?: string | null; character_version?: string | null; import_spec?: Generated<string>; created_at?: Generated<string>; updated_at?: Generated<string>; content_rating?: Generated<string>; template_overrides?: Generated<string>; data_source_format?: string | null; data_raw?: string | null }): Promise<void> {
  return db.insertInto("actors",).values({
    id: crypto.randomUUID(),
    display_name,
    ...opts,
  },).execute();
}

/** Insert a chat_participants row. */
export function insertChatParticipants(db: Db, chat_id: string, actor_id: string, opts?: { role_in_chat?: Generated<ChatParticipantRole>; joined_at?: Generated<string>; last_read_message_id?: string | null; impersonate_actor_id?: string | null; persona_id?: string | null; talkativity?: Generated<number>; initiative?: Generated<number> }): Promise<void> {
  return db.insertInto("chat_participants",).values({
    chat_id,
    actor_id,
    ...opts,
  },).execute();
}

/** Insert a characters row. */
export function insertCharacters(db: Db, owner_id: string, name: string, opts?: { id?: Generated<string>; avatar_asset_id?: string | null; description?: string | null; system_prompt?: string | null; agent_type?: Generated<AgentType>; settings?: Generated<string>; created_at?: Generated<string>; updated_at?: Generated<string> }): Promise<void> {
  return db.insertInto("characters",).values({
    id: crypto.randomUUID(),
    owner_id,
    name,
    ...opts,
  },).execute();
}

/** Insert a world_items row. */
export function insertWorldItems(db: Db, world_id: string, item_id: string, opts?: { id?: Generated<string>; location_id?: string | null; owner_actor_id?: string | null; quantity?: Generated<number>; visibility?: Generated<ItemVisibility>; spawn_condition?: string | null; respawnable?: Generated<number>; created_at?: Generated<string>; updated_at?: Generated<string> }): Promise<void> {
  return db.insertInto("world_items",).values({
    id: crypto.randomUUID(),
    world_id,
    item_id,
    ...opts,
  },).execute();
}

/** Insert a actor_memories row. */
export function insertActorMemories(db: Db, actor_id: string, content: string, opts?: { id?: Generated<string>; source_chat_id?: string | null; memory_type?: Generated<MemoryType>; confidence?: Generated<number>; importance?: Generated<number>; keywords?: string | null; created_at?: Generated<string>; updated_at?: Generated<string>; expires_at?: string | null; decay_rate?: Generated<number>; strength?: Generated<number>; last_accessed_at?: string | null; source_message_id?: string | null; context?: string | null; world_id?: string | null; user_id?: string | null; scope?: Generated<string>; pinned?: Generated<number>; privacy?: Generated<string>; shareability?: string | null }): Promise<void> {
  return db.insertInto("actor_memories",).values({
    id: crypto.randomUUID(),
    actor_id,
    content,
    ...opts,
  },).execute();
}

/** Insert a actor_notes row. */
export function insertActorNotes(db: Db, actor_id: string, title: string, content: string, opts?: { id?: Generated<string>; category?: Generated<NoteCategory>; pinned?: Generated<PinnedState>; sort_order?: Generated<number>; created_at?: Generated<string>; updated_at?: Generated<string> }): Promise<void> {
  return db.insertInto("actor_notes",).values({
    id: crypto.randomUUID(),
    actor_id,
    title,
    content,
    ...opts,
  },).execute();
}

/** Insert a actor_items row. */
export function insertActorItems(db: Db, actor_id: string, name: string, item_type: ActorItemType, opts?: { id?: Generated<string>; description?: string | null; quantity?: Generated<number>; value?: string | null; weight?: number | null; tags?: string | null; metadata?: string | null; equipped?: Generated<EquipState>; sort_order?: Generated<number>; created_at?: Generated<string>; updated_at?: Generated<string> }): Promise<void> {
  return db.insertInto("actor_items",).values({
    id: crypto.randomUUID(),
    actor_id,
    name,
    item_type,
    ...opts,
  },).execute();
}

/** Insert a actor_lore_entries row. */
export function insertActorLoreEntries(db: Db, actor_id: string, content: string, opts?: { id?: Generated<string>; name?: string | null; keys?: Generated<string>; secondary_keys?: string | null; selective?: Generated<number>; case_sensitive?: Generated<number>; enabled?: Generated<LoreEntryStatus>; constant?: Generated<number>; position?: Generated<LorePosition>; insertion_order?: Generated<number>; priority?: Generated<number>; comment?: string | null; sort_order?: Generated<number>; created_at?: Generated<string>; updated_at?: Generated<string>; cooldown_seconds?: Generated<number>; last_activated?: string | null }): Promise<void> {
  return db.insertInto("actor_lore_entries",).values({
    id: crypto.randomUUID(),
    actor_id,
    content,
    ...opts,
  },).execute();
}

/** Insert a system_config row. */
export function insertSystemConfig(db: Db, value: string, opts?: { key?: Generated<string>; description?: string | null; created_at?: Generated<string>; updated_at?: Generated<string> }): Promise<void> {
  return db.insertInto("system_config",).values({
    value,
    ...opts,
  },).execute();
}

/** Insert a log_entries row. */
export function insertLogEntries(db: Db, timestamp: number, time: string, message: string, opts?: { id?: Generated<string>; level?: Generated<number>; module?: string | null; user_id?: string | null; session_id?: string | null; request_id?: string | null; meta?: string | null; event_type?: string | null; entity_type?: string | null; entity_id?: string | null; action?: string | null; created_at?: Generated<string> }): Promise<void> {
  return db.insertInto("log_entries",).values({
    id: crypto.randomUUID(),
    timestamp,
    time,
    message,
    ...opts,
  },).execute();
}

/** Insert a plugin_state row. */
export function insertPluginState(db: Db, opts?: { name?: Generated<string>; enabled?: Generated<number>; enabled_at?: string | null; disabled_at?: string | null; created_at?: Generated<string>; updated_at?: Generated<string> }): Promise<void> {
  return db.insertInto("plugin_state",).values({
    ...opts,
  },).execute();
}

/** Insert a telemetry_events row. */
export function insertTelemetryEvents(db: Db, event_type: string, created_at: string, opts?: { id?: Generated<string>; session_id?: string | null; user_id?: string | null; chat_id?: string | null; event_data?: Generated<string>; source?: Generated<string> }): Promise<void> {
  return db.insertInto("telemetry_events",).values({
    id: crypto.randomUUID(),
    event_type,
    created_at,
    ...opts,
  },).execute();
}

/** Insert a notifications row. */
export function insertNotifications(db: Db, user_id: string, type: string, title: string, opts?: { id?: Generated<string>; body?: string | null; link?: string | null; read?: Generated<number>; data?: string | null; created_at?: Generated<string> }): Promise<void> {
  return db.insertInto("notifications",).values({
    id: crypto.randomUUID(),
    user_id,
    type,
    title,
    ...opts,
  },).execute();
}

/** Insert a data_migrations row. */
export function insertDataMigrations(db: Db, table_name: string, from_version: number, to_version: number, description: string, opts?: { applied_at?: Generated<string> }): Promise<void> {
  return db.insertInto("data_migrations",).values({
    table_name,
    from_version,
    to_version,
    description,
    ...opts,
  },).execute();
}

/** Insert a messages row. */
export function insertMessages(db: Db, chat_id: string, actor_id: string, role: MessageRole, content: string, opts?: { id?: Generated<string>; parent_id?: string | null; key_id?: string | null; content_format?: Generated<MessageContentFormat>; content_type?: Generated<MessageContentType>; content_encoding?: Generated<ContentEncoding>; model_id?: string | null; provider?: string | null; token_count_prompt?: number | null; token_count_completion?: number | null; token_count_total?: number | null; token_cost?: number | null; generation_time_ms?: number | null; tokens_per_second?: number | null; status?: Generated<MessageStatus>; visibility?: Generated<MessageVisibility>; hidden_by?: string | null; hidden_reason?: string | null; idempotency_key?: string | null; continuation_index?: number | null; swipe_index?: number | null; created_at?: Generated<string>; edited_at?: string | null; attachments?: string | null; archived_at?: string | null; format_version?: Generated<number> }): Promise<void> {
  return db.insertInto("messages",).values({
    id: crypto.randomUUID(),
    chat_id,
    actor_id,
    role,
    content,
    ...opts,
  },).execute();
}

/** Insert a actor_keys row. */
export function insertActorKeys(db: Db, actor_id: string, name: string, key_type: KeyType, encrypted_key: string, opts?: { id?: Generated<string>; created_at?: Generated<string>; expires_at?: string | null; status?: Generated<KeyStatus>; public_key?: string | null }): Promise<void> {
  return db.insertInto("actor_keys",).values({
    id: crypto.randomUUID(),
    actor_id,
    name,
    key_type,
    encrypted_key,
    ...opts,
  },).execute();
}

/** Insert a user_api_keys row. */
export function insertUserApiKeys(db: Db, user_id: string, provider_name: string, api_key_encrypted: string, opts?: { id?: Generated<string>; created_at?: Generated<string>; updated_at?: Generated<string> }): Promise<void> {
  return db.insertInto("user_api_keys",).values({
    id: crypto.randomUUID(),
    user_id,
    provider_name,
    api_key_encrypted,
    ...opts,
  },).execute();
}

/** Insert a generation_attempts row. */
export function insertGenerationAttempts(db: Db, chat_id: string, parent_message_id: string, actor_id: string, idempotency_key: string, model_id: string, provider: string, opts?: { id?: Generated<string>; status?: Generated<GenerationStatus>; cancel_reason?: CancelReason | null; cancel_reason_detail?: string | null; cancel_source?: CancelSource | null; abort_signal_id?: string | null; started_at?: Generated<string>; completed_at?: string | null; prompt_tokens?: number | null; completion_tokens?: number | null; total_tokens?: number | null; generation_time_ms?: number | null; error_message?: string | null; streaming_chunks_received?: number | null; streaming_chars_received?: number | null; repetition_score?: number | null; repetition_analysis?: string | null; policy_analysis?: string | null; response_count_in_turn?: number | null; parent_attempt_id?: string | null; continuation_count?: number | null; partial_content?: string | null; step_index?: number | null; total_steps?: number | null; created_at?: Generated<string>; updated_at?: Generated<string> }): Promise<void> {
  return db.insertInto("generation_attempts",).values({
    id: crypto.randomUUID(),
    chat_id,
    parent_message_id,
    actor_id,
    idempotency_key,
    model_id,
    provider,
    ...opts,
  },).execute();
}

/** Insert a story_turns row. */
export function insertStoryTurns(db: Db, chat_id: string, turn_number: number, actor_id: string, turn_type: TurnType, prompt_sent: string, opts?: { id?: Generated<string>; response_received?: string | null; quality_score?: number | null; quality_details?: string | null; regeneration_count?: Generated<number>; status?: Generated<TurnStatus>; gm_decision?: string | null; world_events?: Generated<string>; quest_progress?: Generated<string>; started_at?: Generated<string>; completed_at?: string | null; created_at?: Generated<string>; updated_at?: Generated<string> }): Promise<void> {
  return db.insertInto("story_turns",).values({
    id: crypto.randomUUID(),
    chat_id,
    turn_number,
    actor_id,
    turn_type,
    prompt_sent,
    ...opts,
  },).execute();
}

/** Insert a quests row. */
export function insertQuests(db: Db, world_id: string, creator_id: string, name: string, type: QuestType, target: number, opts?: { id?: Generated<string>; description?: string | null; status?: Generated<QuestStatus>; priority?: Generated<number>; config?: Generated<string>; progress?: Generated<number>; start_time?: string | null; deadline?: string | null; time_location_id?: string | null; rewards?: Generated<string>; narrative_hooks?: Generated<string>; created_at?: Generated<string>; updated_at?: Generated<string>; completed_at?: string | null }): Promise<void> {
  return db.insertInto("quests",).values({
    id: crypto.randomUUID(),
    world_id,
    creator_id,
    name,
    type,
    target,
    ...opts,
  },).execute();
}

/** Insert a quest_progress row. */
export function insertQuestProgress(db: Db, quest_id: string, chat_id: string, opts?: { id?: Generated<string>; progress?: Generated<number>; status?: Generated<QuestProgressStatus>; contributed_events?: Generated<string>; started_at?: Generated<string>; created_at?: Generated<string>; updated_at?: Generated<string>; completed_at?: string | null }): Promise<void> {
  return db.insertInto("quest_progress",).values({
    id: crypto.randomUUID(),
    quest_id,
    chat_id,
    ...opts,
  },).execute();
}

/** Insert a world_states row. */
export function insertWorldStates(db: Db, world_id: string, snapshot: string, opts?: { id?: Generated<string>; trigger_message_id?: string | null; trigger_turn_id?: string | null; description?: string | null; created_at?: Generated<string> }): Promise<void> {
  return db.insertInto("world_states",).values({
    id: crypto.randomUUID(),
    world_id,
    snapshot,
    ...opts,
  },).execute();
}

/** Insert a npc_states row. */
export function insertNpcStates(db: Db, actor_id: string, world_id: string, opts?: { id?: Generated<string>; location_id?: string | null; health?: Generated<number>; mental_state?: Generated<string>; knowledge?: Generated<string>; relationships?: Generated<string>; inventory?: Generated<string>; schedule?: Generated<string>; created_at?: Generated<string>; updated_at?: Generated<string> }): Promise<void> {
  return db.insertInto("npc_states",).values({
    id: crypto.randomUUID(),
    actor_id,
    world_id,
    ...opts,
  },).execute();
}

/** Insert a location_states row. */
export function insertLocationStates(db: Db, location_id: string, world_id: string, opts?: { id?: Generated<string>; description_override?: string | null; atmosphere?: string | null; npcs_present?: Generated<string>; items_available?: Generated<string>; time_of_day?: string | null; weather?: string | null; hazards?: Generated<string>; created_at?: Generated<string>; updated_at?: Generated<string> }): Promise<void> {
  return db.insertInto("location_states",).values({
    id: crypto.randomUUID(),
    location_id,
    world_id,
    ...opts,
  },).execute();
}

/** Insert a synthetic_data row. */
export function insertSyntheticData(db: Db, type: SyntheticDataType, source_data: string, generated_cases: string, opts?: { id?: Generated<string>; chat_id?: string | null; world_id?: string | null; metadata?: Generated<string>; status?: Generated<SyntheticDataStatus>; created_at?: Generated<string>; validated_at?: string | null; validated_by?: string | null }): Promise<void> {
  return db.insertInto("synthetic_data",).values({
    id: crypto.randomUUID(),
    type,
    source_data,
    generated_cases,
    ...opts,
  },).execute();
}

/** Insert a model_role_overrides row. */
export function insertModelRoleOverrides(db: Db, provider: string, model: string, opts?: { role?: Generated<ModelRole>; created_at?: Generated<string>; updated_at?: Generated<string> }): Promise<void> {
  return db.insertInto("model_role_overrides",).values({
    provider,
    model,
    ...opts,
  },).execute();
}

/** Insert a message_reactions row. */
export function insertMessageReactions(db: Db, message_id: string, user_id: string, emoji: string, opts?: { id?: Generated<string>; created_at?: Generated<string> }): Promise<void> {
  return db.insertInto("message_reactions",).values({
    id: crypto.randomUUID(),
    message_id,
    user_id,
    emoji,
    ...opts,
  },).execute();
}

/** Insert a chat_pins row. */
export function insertChatPins(db: Db, chat_id: string, message_id: string, pinned_by: string, opts?: { id?: Generated<string>; pinned_at?: Generated<string> }): Promise<void> {
  return db.insertInto("chat_pins",).values({
    id: crypto.randomUUID(),
    chat_id,
    message_id,
    pinned_by,
    ...opts,
  },).execute();
}

/** Insert a character_permanent_traits row. */
export function insertCharacterPermanentTraits(db: Db, actor_id: string, trait_category: TraitCategory, trait_name: string, trait_value: string, created_at: string, updated_at: string, opts?: { id?: Generated<string>; immutable?: Generated<number> }): Promise<void> {
  return db.insertInto("character_permanent_traits",).values({
    id: crypto.randomUUID(),
    actor_id,
    trait_category,
    trait_name,
    trait_value,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a character_world_traits row. */
export function insertCharacterWorldTraits(db: Db, actor_id: string, world_id: string, trait_category: WorldTraitCategory, trait_name: string, trait_value: string, created_at: string, updated_at: string, opts?: { id?: Generated<string> }): Promise<void> {
  return db.insertInto("character_world_traits",).values({
    id: crypto.randomUUID(),
    actor_id,
    world_id,
    trait_category,
    trait_name,
    trait_value,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a character_location_traits row. */
export function insertCharacterLocationTraits(db: Db, actor_id: string, location_id: string, trait_name: string, trait_value: string, created_at: string, updated_at: string, opts?: { id?: Generated<string>; bonus?: number | null; penalty?: number | null; effects?: string | null; equipment_override?: string | null }): Promise<void> {
  return db.insertInto("character_location_traits",).values({
    id: crypto.randomUUID(),
    actor_id,
    location_id,
    trait_name,
    trait_value,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a character_mood row. */
export function insertCharacterMood(db: Db, actor_id: string, last_mood_change: string, created_at: string, updated_at: string, opts?: { id?: Generated<string>; world_id?: string | null; happiness?: Generated<number>; base_mood?: Generated<string>; current_mood?: Generated<string>; mood_stability?: Generated<number>; expression_modifiers?: string | null }): Promise<void> {
  return db.insertInto("character_mood",).values({
    id: crypto.randomUUID(),
    actor_id,
    last_mood_change,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a mood_events row. */
export function insertMoodEvents(db: Db, actor_id: string, event_type: string, happiness_delta: number, source: string, created_at: string, opts?: { id?: Generated<string>; world_id?: string | null; mood_override?: string | null; source_id?: string | null }): Promise<void> {
  return db.insertInto("mood_events",).values({
    id: crypto.randomUUID(),
    actor_id,
    event_type,
    happiness_delta,
    source,
    created_at,
    ...opts,
  },).execute();
}

/** Insert a character_relationships row. */
export function insertCharacterRelationships(db: Db, actor_id: string, target_actor_id: string, relationship_type: RelationshipType, created_at: string, updated_at: string, opts?: { id?: Generated<string>; world_id?: string | null; standing?: Generated<number>; trust?: Generated<number>; familiarity?: Generated<number>; is_bidirectional?: Generated<number>; metadata?: string | null }): Promise<void> {
  return db.insertInto("character_relationships",).values({
    id: crypto.randomUUID(),
    actor_id,
    target_actor_id,
    relationship_type,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a character_avatars row. */
export function insertCharacterAvatars(db: Db, actor_id: string, asset_id: string, label: string, created_at: string, updated_at: string, opts?: { id?: Generated<string>; tags?: Generated<string>; is_primary?: Generated<number>; sort_order?: Generated<number> }): Promise<void> {
  return db.insertInto("character_avatars",).values({
    id: crypto.randomUUID(),
    actor_id,
    asset_id,
    label,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a character_avatar_config row. */
export function insertCharacterAvatarConfig(db: Db, actor_id: string, created_at: string, updated_at: string, opts?: { id?: Generated<string>; selection_rule?: Generated<string>; weights?: string | null; fallback_chain?: string | null }): Promise<void> {
  return db.insertInto("character_avatar_config",).values({
    id: crypto.randomUUID(),
    actor_id,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a world_avatar_config row. */
export function insertWorldAvatarConfig(db: Db, world_id: string, actor_id: string, created_at: string, updated_at: string, opts?: { id?: Generated<string>; selection_rule_override?: AvatarSelectionRule | null; weights_override?: string | null }): Promise<void> {
  return db.insertInto("world_avatar_config",).values({
    id: crypto.randomUUID(),
    world_id,
    actor_id,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a emotions row. */
export function insertEmotions(db: Db, name: string, display_name: string, category: string, valence: number, arousal: number, created_at: string, opts?: { id?: Generated<string>; icon?: string | null }): Promise<void> {
  return db.insertInto("emotions",).values({
    id: crypto.randomUUID(),
    name,
    display_name,
    category,
    valence,
    arousal,
    created_at,
    ...opts,
  },).execute();
}

/** Insert a character_emotions row. */
export function insertCharacterEmotions(db: Db, actor_id: string, emotion_id: string, created_at: string, updated_at: string, opts?: { id?: Generated<string>; intensity?: Generated<number>; context?: string | null; expires_at?: string | null }): Promise<void> {
  return db.insertInto("character_emotions",).values({
    id: crypto.randomUUID(),
    actor_id,
    emotion_id,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a character_availability row. */
export function insertCharacterAvailability(db: Db, actor_id: string, created_at: string, updated_at: string, opts?: { id?: Generated<string>; status?: Generated<string>; usage_policy?: string | null; activity_restrictions?: string | null; content_policy?: string | null; nsfw_policy?: string | null }): Promise<void> {
  return db.insertInto("character_availability",).values({
    id: crypto.randomUUID(),
    actor_id,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a character_licensing row. */
export function insertCharacterLicensing(db: Db, actor_id: string, license_type: LicenseType, created_at: string, updated_at: string, opts?: { id?: Generated<string>; custom_license_text?: string | null; attribution?: string | null; allow_derivatives?: Generated<number>; allow_commercial?: Generated<number>; share_alike?: Generated<number> }): Promise<void> {
  return db.insertInto("character_licensing",).values({
    id: crypto.randomUUID(),
    actor_id,
    license_type,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a admin_character_overrides row. */
export function insertAdminCharacterOverrides(db: Db, actor_id: string, admin_id: string, action: AdminOverrideAction, created_at: string, opts?: { id?: Generated<string>; visibility_override?: VisibilityOverride | null; license_override?: LicenseType | null; reason?: string | null; expires_at?: string | null }): Promise<void> {
  return db.insertInto("admin_character_overrides",).values({
    id: crypto.randomUUID(),
    actor_id,
    admin_id,
    action,
    created_at,
    ...opts,
  },).execute();
}

/** Insert a crafting_recipes row. */
export function insertCraftingRecipes(db: Db, world_id: string, name: string, discipline: CraftingDiscipline, output_item_id: string, created_at: string, updated_at: string, opts?: { id?: Generated<string>; description?: string | null; tier?: Generated<number>; level_required?: Generated<number>; output_quantity?: Generated<number>; crafting_time_seconds?: Generated<number>; base_success_chance?: Generated<number>; base_quality_min?: Generated<number>; base_quality_max?: Generated<number>; perfect_threshold?: Generated<number>; station_type_required?: CraftingStationType | null; discovered_by_default?: Generated<number>; tags?: Generated<string> }): Promise<void> {
  return db.insertInto("crafting_recipes",).values({
    id: crypto.randomUUID(),
    world_id,
    name,
    discipline,
    output_item_id,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a crafting_recipe_materials row. */
export function insertCraftingRecipeMaterials(db: Db, recipe_id: string, item_id: string, created_at: string, opts?: { id?: Generated<string>; quantity?: Generated<number>; slot_type?: Generated<MaterialSlotType>; quality_requirement?: QualityLevel | null; bonus_effect?: string | null; sort_order?: Generated<number> }): Promise<void> {
  return db.insertInto("crafting_recipe_materials",).values({
    id: crypto.randomUUID(),
    recipe_id,
    item_id,
    created_at,
    ...opts,
  },).execute();
}

/** Insert a crafting_station_defs row. */
export function insertCraftingStationDefs(db: Db, world_id: string, name: string, station_type: CraftingStationType, created_at: string, updated_at: string, opts?: { id?: Generated<string>; description?: string | null; tier?: Generated<number>; speed_bonus?: Generated<number>; quality_bonus?: Generated<number>; success_bonus?: Generated<number>; material_saving_chance?: Generated<number>; max_durability?: Generated<number> }): Promise<void> {
  return db.insertInto("crafting_station_defs",).values({
    id: crypto.randomUUID(),
    world_id,
    name,
    station_type,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a crafting_station_instances row. */
export function insertCraftingStationInstances(db: Db, station_def_id: string, world_id: string, current_durability: number, created_at: string, updated_at: string, opts?: { id?: Generated<string>; location_id?: string | null; owner_actor_id?: string | null; is_active?: Generated<number> }): Promise<void> {
  return db.insertInto("crafting_station_instances",).values({
    id: crypto.randomUUID(),
    station_def_id,
    world_id,
    current_durability,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a professions row. */
export function insertProfessions(db: Db, actor_id: string, world_id: string, discipline: CraftingDiscipline, created_at: string, updated_at: string, opts?: { id?: Generated<string>; level?: Generated<number>; experience?: Generated<number>; title?: Generated<ProfessionTitle> }): Promise<void> {
  return db.insertInto("professions",).values({
    id: crypto.randomUUID(),
    actor_id,
    world_id,
    discipline,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a profession_specializations row. */
export function insertProfessionSpecializations(db: Db, profession_id: string, name: string, bonus_type: ProfessionBonusType, created_at: string, opts?: { id?: Generated<string>; description?: string | null; bonus_value?: Generated<number>; requirement_level?: Generated<number>; requirement_specializations?: Generated<string>; is_active?: Generated<number> }): Promise<void> {
  return db.insertInto("profession_specializations",).values({
    id: crypto.randomUUID(),
    profession_id,
    name,
    bonus_type,
    created_at,
    ...opts,
  },).execute();
}

/** Insert a recipe_discoveries row. */
export function insertRecipeDiscoveries(db: Db, actor_id: string, world_id: string, recipe_id: string, discovery_method: DiscoveryMethod, discovered_at: string, opts?: { id?: Generated<string>; mastery_level?: Generated<number> }): Promise<void> {
  return db.insertInto("recipe_discoveries",).values({
    id: crypto.randomUUID(),
    actor_id,
    world_id,
    recipe_id,
    discovery_method,
    discovered_at,
    ...opts,
  },).execute();
}

/** Insert a gathering_node_defs row. */
export function insertGatheringNodeDefs(db: Db, world_id: string, name: string, node_type: GatheringNodeType, created_at: string, updated_at: string, opts?: { id?: Generated<string>; description?: string | null; skill_required?: Generated<number>; respawn_time_seconds?: Generated<number>; rarity?: Generated<QualityLevel>; max_uses?: Generated<number> }): Promise<void> {
  return db.insertInto("gathering_node_defs",).values({
    id: crypto.randomUUID(),
    world_id,
    name,
    node_type,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a gathering_node_materials row. */
export function insertGatheringNodeMaterials(db: Db, node_def_id: string, item_id: string, created_at: string, opts?: { id?: Generated<string>; min_quantity?: Generated<number>; max_quantity?: Generated<number>; drop_chance?: Generated<number>; min_quality?: QualityLevel | null; max_quality?: QualityLevel | null; sort_order?: Generated<number> }): Promise<void> {
  return db.insertInto("gathering_node_materials",).values({
    id: crypto.randomUUID(),
    node_def_id,
    item_id,
    created_at,
    ...opts,
  },).execute();
}

/** Insert a gathering_node_instances row. */
export function insertGatheringNodeInstances(db: Db, node_def_id: string, world_id: string, current_uses: number, created_at: string, updated_at: string, opts?: { id?: Generated<string>; location_id?: string | null; is_depleted?: Generated<number>; respawn_at?: string | null }): Promise<void> {
  return db.insertInto("gathering_node_instances",).values({
    id: crypto.randomUUID(),
    node_def_id,
    world_id,
    current_uses,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a crafting_attempts row. */
export function insertCraftingAttempts(db: Db, actor_id: string, world_id: string, recipe_id: string, status: CraftingAttemptStatus, created_at: string, opts?: { id?: Generated<string>; station_instance_id?: string | null; materials_used?: Generated<string>; quality_achieved?: Generated<number>; output_item_id?: string | null; output_quantity?: Generated<number>; experience_gained?: Generated<number>; skill_increase?: Generated<number>; bonus_effects?: Generated<string>; duration_ms?: Generated<number> }): Promise<void> {
  return db.insertInto("crafting_attempts",).values({
    id: crypto.randomUUID(),
    actor_id,
    world_id,
    recipe_id,
    status,
    created_at,
    ...opts,
  },).execute();
}

/** Insert a crafting_orders row. */
export function insertCraftingOrders(db: Db, world_id: string, requester_actor_id: string, recipe_id: string, created_at: string, updated_at: string, opts?: { id?: Generated<string>; crafter_actor_id?: string | null; quantity?: Generated<number>; max_quality?: QualityLevel | null; offered_payment?: Generated<number>; offered_materials?: Generated<string>; status?: Generated<string>; deadline?: string | null }): Promise<void> {
  return db.insertInto("crafting_orders",).values({
    id: crypto.randomUUID(),
    world_id,
    requester_actor_id,
    recipe_id,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a character_intimacy row. */
export function insertCharacterIntimacy(db: Db, actor_id: string, target_actor_id: string, created_at: string, updated_at: string, opts?: { id?: Generated<string>; world_id?: string | null; score?: Generated<number>; action_history?: Generated<string>; unlocked_thresholds?: Generated<string> }): Promise<void> {
  return db.insertInto("character_intimacy",).values({
    id: crypto.randomUUID(),
    actor_id,
    target_actor_id,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a character_arousal row. */
export function insertCharacterArousal(db: Db, actor_id: string, last_update: string, created_at: string, updated_at: string, opts?: { id?: Generated<string>; world_id?: string | null; level?: Generated<number>; buildup_rate?: Generated<number>; decay_rate?: Generated<number>; modifiers?: Generated<string> }): Promise<void> {
  return db.insertInto("character_arousal",).values({
    id: crypto.randomUUID(),
    actor_id,
    last_update,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a character_desire_profile row. */
export function insertCharacterDesireProfile(db: Db, actor_id: string, created_at: string, updated_at: string, opts?: { id?: Generated<string>; turn_ons?: Generated<string>; turn_offs?: Generated<string>; fetishes?: Generated<string>; hard_limits?: Generated<string>; current_desire?: Generated<number>; desire_decay_rate?: Generated<number>; desire_buildup_rate?: Generated<number> }): Promise<void> {
  return db.insertInto("character_desire_profile",).values({
    id: crypto.randomUUID(),
    actor_id,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a character_seduction_skills row. */
export function insertCharacterSeductionSkills(db: Db, actor_id: string, skill_category: SeductionSkillCategory, skill_name: string, created_at: string, updated_at: string, opts?: { id?: Generated<string>; level?: Generated<number>; xp?: Generated<number>; xp_to_next?: Generated<number> }): Promise<void> {
  return db.insertInto("character_seduction_skills",).values({
    id: crypto.randomUUID(),
    actor_id,
    skill_category,
    skill_name,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a nsfw_encounters row. */
export function insertNsfwEncounters(db: Db, encounter_type: NsfwEncounterType, participants: string, created_at: string, updated_at: string, opts?: { id?: Generated<string>; world_id?: string | null; intensity?: Generated<ContentIntensity>; narrative_style?: Generated<NarrativeStyle>; phases?: Generated<string>; current_phase?: Generated<number>; outcomes?: Generated<string>; content_tags?: Generated<string>; completed?: Generated<number> }): Promise<void> {
  return db.insertInto("nsfw_encounters",).values({
    id: crypto.randomUUID(),
    encounter_type,
    participants,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a character_body_profile row. */
export function insertCharacterBodyProfile(db: Db, actor_id: string, created_at: string, updated_at: string, opts?: { id?: Generated<string>; stamina?: Generated<number>; flexibility?: Generated<number>; sensitivity?: Generated<number>; endurance?: Generated<number>; size_category?: Generated<string>; build?: Generated<string>; beauty?: Generated<number>; charisma?: Generated<number>; style?: Generated<number>; scent?: string | null; modifications?: Generated<string> }): Promise<void> {
  return db.insertInto("character_body_profile",).values({
    id: crypto.randomUUID(),
    actor_id,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a character_heat_cycle row. */
export function insertCharacterHeatCycle(db: Db, actor_id: string, created_at: string, updated_at: string, opts?: { id?: Generated<string>; species?: Generated<string>; cycle_length_days?: Generated<number>; current_phase?: Generated<string>; days_until_next_heat?: Generated<number>; effects?: Generated<string> }): Promise<void> {
  return db.insertInto("character_heat_cycle",).values({
    id: crypto.randomUUID(),
    actor_id,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a character_fantasies row. */
export function insertCharacterFantasies(db: Db, actor_id: string, fantasy_name: string, category: FantasyCategory, created_at: string, updated_at: string, opts?: { id?: Generated<string>; intensity?: Generated<string>; requirements?: Generated<string>; fulfillment_effects?: Generated<string>; risks?: Generated<string>; discovered_through?: string | null; initial_reaction?: Generated<string>; current_feeling?: Generated<string>; times_explored?: Generated<number> }): Promise<void> {
  return db.insertInto("character_fantasies",).values({
    id: crypto.randomUUID(),
    actor_id,
    fantasy_name,
    category,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a location_nsfw_config row. */
export function insertLocationNsfwConfig(db: Db, location_id: string, location_type: NsfwLocationType, created_at: string, updated_at: string, opts?: { id?: Generated<string>; privacy_level?: Generated<string>; discovery_chance?: Generated<number>; atmosphere?: Generated<string>; equipment?: Generated<string>; risks?: Generated<string> }): Promise<void> {
  return db.insertInto("location_nsfw_config",).values({
    id: crypto.randomUUID(),
    location_id,
    location_type,
    created_at,
    updated_at,
    ...opts,
  },).execute();
}

/** Insert a model_comparisons row. */
export function insertModelComparisons(db: Db, message_id: string, user_id: string, reference_model: string, preference: string, confidence: number, created_at: string, opts?: { id?: Generated<string> }): Promise<void> {
  return db.insertInto("model_comparisons",).values({
    id: crypto.randomUUID(),
    message_id,
    user_id,
    reference_model,
    preference,
    confidence,
    created_at,
    ...opts,
  },).execute();
}

/** Insert a blog_posts row. */
export function insertBlogPosts(db: Db, author_id: string, title: string, body: string, opts?: { id?: Generated<string>; visibility?: Generated<string>; author_type?: Generated<string>; status?: Generated<string>; category?: string | null; world_id?: string | null; character_id?: string | null; scheduled_at?: string | null; published_at?: string | null; view_count?: Generated<number>; metadata?: Generated<string>; created_at?: Generated<string>; updated_at?: Generated<string> }): Promise<void> {
  return db.insertInto("blog_posts",).values({
    id: crypto.randomUUID(),
    author_id,
    title,
    body,
    ...opts,
  },).execute();
}

/** Insert a blog_comments row. */
export function insertBlogComments(db: Db, post_id: string, author_id: string, body: string, opts?: { id?: Generated<string>; status?: Generated<string>; created_at?: Generated<string> }): Promise<void> {
  return db.insertInto("blog_comments",).values({
    id: crypto.randomUUID(),
    post_id,
    author_id,
    body,
    ...opts,
  },).execute();
}

/** Insert a blog_tags row. */
export function insertBlogTags(db: Db, post_id: string, tag: string, opts?: { id?: Generated<string> }): Promise<void> {
  return db.insertInto("blog_tags",).values({
    id: crypto.randomUUID(),
    post_id,
    tag,
    ...opts,
  },).execute();
}

/** Insert a blog_follows row. */
export function insertBlogFollows(db: Db, follower_id: string, author_id: string, opts?: { id?: Generated<string>; created_at?: Generated<string> }): Promise<void> {
  return db.insertInto("blog_follows",).values({
    id: crypto.randomUUID(),
    follower_id,
    author_id,
    ...opts,
  },).execute();
}

/** Insert a blog_rag_sources row. */
export function insertBlogRagSources(db: Db, post_id: string, source_type: string, uri: string, title: string, opts?: { id?: Generated<string>; relevance_score?: Generated<number>; snippet?: Generated<string>; created_at?: Generated<string> }): Promise<void> {
  return db.insertInto("blog_rag_sources",).values({
    id: crypto.randomUUID(),
    post_id,
    source_type,
    uri,
    title,
    ...opts,
  },).execute();
}

/** Insert a nsfw_user_preferences row. */
export function insertNsfwUserPreferences(db: Db, user_id: string, opts?: { id?: Generated<string>; nsfw_enabled?: Generated<number>; max_rating?: Generated<string>; blocked_from_nsfw?: Generated<number>; banned_from_nsfw?: Generated<number>; shadow_nsfw?: Generated<number>; block_reason?: string | null; banned_at?: string | null; banned_by?: string | null; created_at?: Generated<string>; updated_at?: Generated<string> }): Promise<void> {
  return db.insertInto("nsfw_user_preferences",).values({
    id: crypto.randomUUID(),
    user_id,
    ...opts,
  },).execute();
}

/** Insert a content_flags row. */
export function insertContentFlags(db: Db, reporter_id: string, content_type: string, content_id: string, flag_reason: string, opts?: { id?: Generated<string>; chat_id?: string | null; world_id?: string | null; description?: string | null; status?: Generated<string>; resolution?: string | null; resolved_by?: string | null; resolved_at?: string | null; created_at?: Generated<string> }): Promise<void> {
  return db.insertInto("content_flags",).values({
    id: crypto.randomUUID(),
    reporter_id,
    content_type,
    content_id,
    flag_reason,
    ...opts,
  },).execute();
}

/** Insert a moderation_actions row. */
export function insertModerationActions(db: Db, action_type: string, target_user_id: string, performed_by: string, reason: string, scope: string, opts?: { id?: Generated<string>; scope_id?: string | null; metadata?: Generated<string>; expires_at?: string | null; created_at?: Generated<string> }): Promise<void> {
  return db.insertInto("moderation_actions",).values({
    id: crypto.randomUUID(),
    action_type,
    target_user_id,
    performed_by,
    reason,
    scope,
    ...opts,
  },).execute();
}

/** Insert a message_translations row. */
export function insertMessageTranslations(db: Db, message_id: string, locale: string, content: string, created_at: string, opts?: { id?: Generated<string>; provider?: string | null; updated_at?: string | null }): Promise<void> {
  return db.insertInto("message_translations",).values({
    id: crypto.randomUUID(),
    message_id,
    locale,
    content,
    created_at,
    ...opts,
  },).execute();
}

/** Insert a moderation_appeals row. */
export function insertModerationAppeals(db: Db, user_id: string, action_id: string, reason: string, created_at: string, opts?: { id?: Generated<string>; status?: Generated<string>; reviewed_by?: string | null; review_note?: string | null; updated_at?: string | null }): Promise<void> {
  return db.insertInto("moderation_appeals",).values({
    id: crypto.randomUUID(),
    user_id,
    action_id,
    reason,
    created_at,
    ...opts,
  },).execute();
}

/** Insert a shadow_notes row. */
export function insertShadowNotes(db: Db, chat_id: string, type: ShadowNoteType, content: string, created_at: string, opts?: { id?: Generated<string>; revealed?: Generated<number> }): Promise<void> {
  return db.insertInto("shadow_notes",).values({
    id: crypto.randomUUID(),
    chat_id,
    type,
    content,
    created_at,
    ...opts,
  },).execute();
}

/** Insert a whitenotes row. */
export function insertWhitenotes(db: Db, chat_id: string, type: WhiteneoteType, content: string, created_at: string, opts?: { id?: Generated<string>; priority?: Generated<number>; scope?: Generated<WhiteneoteScope>; expires_at?: string | null }): Promise<void> {
  return db.insertInto("whitenotes",).values({
    id: crypto.randomUUID(),
    chat_id,
    type,
    content,
    created_at,
    ...opts,
  },).execute();
}
