// SPDX-License-Identifier: LGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Loop Lore Contributors

/**
 * Branch coverage for the shared mock LLM provider
 * (src/test-utils/mock-provider.ts): happy path, failure flags,
 * streaming event sequence, and capability metadata.
 *
 * Waiver note (generated code): src/test-utils/insert-helpers.ts is
 * auto-generated by scripts/generate-db-types.ts ("DO NOT EDIT MANUALLY"
 * header; regenerated via `bun run db:sync-types`) and already carries
 * 2515 of this module's 2606 coverable lines. The coverage gate's 80%
 * floor is unreachable for `test-utils` without testing generated code,
 * so this module is covered here only through its hand-written helpers
 * (mock-provider, create-test-db, isolate-only); insert-helpers stays
 * exercised indirectly by the integration tests that insert through it.
 */
import { describe, expect, test, } from "bun:test";
import type { GenerateRequest, StreamHandler, } from "../generation/providers/types";
import { MockLLMProvider, } from "./mock-provider";

/** Minimal provider request — mirrors the shape used in registry tests. */
function makeReq(): GenerateRequest {
  return {
    model: "mock-model",
    messages: [],
    params: {},
  } as unknown as GenerateRequest;
}

describe("MockLLMProvider — happy path", () => {
  test("complete resolves the canned response with usage", async () => {
    const provider = new MockLLMProvider();
    const res = await provider.complete(makeReq(),);
    expect(res.content,).toBe("Mock response content",);
    expect(res.finishReason,).toBe("stop",);
    expect(res.usage,).toEqual({ promptTokens: 10, completionTokens: 20, totalTokens: 30, },);
  });

  test("stream emits three content chunks plus done, then resolves", async () => {
    const provider = new MockLLMProvider();
    const seen: string[] = [];
    let done = false;
    const handler: StreamHandler = (event,) => {
      if (event.type === "content") { seen.push(event.content!,); }
      if (event.type === "done") { done = true; }
    };
    const res = await provider.stream(makeReq(), handler,);
    expect(seen.join("",),).toBe("Mock streamed response",);
    expect(done,).toBe(true,);
    expect(res.content,).toBe("Mock streamed response",);
  });

  test("healthCheck reports ok and listModels exposes the mock model", async () => {
    const provider = new MockLLMProvider();
    await expect(provider.healthCheck(),).resolves.toEqual({ status: "ok", },);
    await expect(provider.listModels(),).resolves.toEqual([{ id: "mock-model", },],);
  });

  test("capabilities advertise a streaming text-only mock", () => {
    const provider = new MockLLMProvider();
    expect(provider.capabilities.text,).toBe(true,);
    expect(provider.capabilities.streaming,).toBe(true,);
    expect(provider.capabilities.image,).toBe(false,);
    expect(provider.capabilities.embeddings,).toBe(false,);
  });
});

describe("MockLLMProvider — failure flags", () => {
  test("failOnCall makes complete throw", async () => {
    const provider = new MockLLMProvider();
    expect(provider.failOnCall,).toBe(false,);
    provider.failOnCall = true;
    expect(provider.failOnCall,).toBe(true,);
    expect(() => provider.complete(makeReq(),)).toThrow("Mock provider failure",);
    provider.failOnCall = false;
    await expect(provider.complete(makeReq(),),).resolves.toBeDefined();
  });

  test("streamError makes stream throw", async () => {
    const provider = new MockLLMProvider();
    expect(provider.streamError,).toBe(false,);
    provider.streamError = true;
    expect(provider.streamError,).toBe(true,);
    await expect(Promise.resolve().then(() => provider.stream(makeReq(), () => {},)),).rejects.toThrow(
      "Mock stream failure",
    );
  });
  test("flags are independent per instance", async () => {
    const failing = new MockLLMProvider();
    failing.failOnCall = true;
    const healthy = new MockLLMProvider();
    await expect(healthy.complete(makeReq(),),).resolves.toBeDefined();
    await expect(Promise.resolve().then(() => failing.complete(makeReq(),)),).rejects.toThrow();
  });
});
