// SPDX-License-Identifier: LGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Loop Lore Contributors

// src/autonomy/config/resolver.ts — Layered autonomy config resolver
//
// Precedence (highest wins):
//   per-actor override (character_internal_traits.autonomy_preferences.autonomy)
//     > per-chat override  (chats.autonomy_config)
//     > per-world default  (worlds.autonomy_config)
//     > preset default     (built-in PRESETS table)
//
// No caching past a single call: callers (scheduler / governor) MUST
// re-resolve each tick so chat-session-scoped overrides take effect
// immediately. The resolver is pure I/O — no scheduler/governor deps.

import { sql, } from "kysely";
import type { Db, } from "../../db";
import { jsonParseOr, } from "../../utils";
import { getPreset, } from "./presets";
import type {
  AutonomyConfig,
  AutonomyConfigOverride,
  AutonomyLayers,
  PacingPresetName,
  ResolveAutonomyScope,
} from "./types";

/** Default preset used when no layer names one. */
const DEFAULT_PRESET: PacingPresetName = "organic";

/**
 * Read the autonomy JSON column from a single row. Empty / missing
 * rows return `{}` so every layer can opt into specific keys without
 * copying the preset shape.
 * @param db
 * @param table
 * @param id
 * @returns Parsed JSON object (possibly empty).
 */
async function readJsonColumn(
  db: Db,
  table: "chats" | "worlds",
  id: string,
): Promise<AutonomyConfigOverride> {
  // Raw SQL: the typed `DB` interface is regenerated by `db:sync-types`
  // after migration 021 lands; using `sql` keeps this module compiling
  // before the regen runs.
  const result = await sql<{ value: string | null }>`
    SELECT autonomy_config AS value
    FROM ${sql.table(table,)}
    WHERE id = ${id}
    LIMIT 1
  `.execute(db,);

  const raw = result.rows[0]?.value;
  return jsonParseOr<AutonomyConfigOverride>(raw ?? "{}", {},);
}

/**
 * Read the actor's autonomy override, if any. The
 * `character_internal_traits.autonomy_preferences` JSON may carry an
 * `autonomy` sub-object for pacing overrides — preserved here even
 * though the surrounding shape is psychological/narrative.
 * @param db
 * @param actorId
 * @returns Override fragment or empty.
 */
async function readActorOverride(db: Db, actorId: string,): Promise<AutonomyConfigOverride> {
  const result = await sql<{ value: string | null }>`
    SELECT autonomy_preferences AS value
    FROM character_internal_traits
    WHERE actor_id = ${actorId}
    LIMIT 1
  `.execute(db,);

  const raw = result.rows[0]?.value;
  const parsed = jsonParseOr<{ autonomy?: AutonomyConfigOverride }>(
    raw ?? "{}",
    {},
  );

  return parsed.autonomy ?? {};
}

/**
 * Apply a single layer's overrides onto `out`. Only fields explicitly
 * set in the layer override the preset baseline.
 */
function applyLayer(out: AutonomyConfig, layer: AutonomyConfigOverride,): void {
  if (layer.preset !== undefined) { out.preset = layer.preset; }
  if (layer.enabled !== undefined) { out.enabled = layer.enabled; }
  if (layer.tickIntervalMs !== undefined) { out.tickIntervalMs = layer.tickIntervalMs; }
  if (layer.jitterRatio !== undefined) { out.jitterRatio = layer.jitterRatio; }
  if (layer.perAgentCap !== undefined) { out.perAgentCap = layer.perAgentCap; }
  if (layer.perUserCap !== undefined) { out.perUserCap = layer.perUserCap; }
}

/**
 * Read every layer for a scope, plus the config they resolve to.
 *
 * Settings UI needs the per-layer values to show what a layer
 * actually overrides versus what it inherits — the resolved config
 * alone cannot answer that. Same SELECTs as `resolveAutonomyConfig`,
 * and the merge is shared, so the two cannot disagree on precedence.
 * @param db
 * @param scope
 * @returns each layer's raw override plus the merged result
 */
export async function resolveAutonomyLayers(
  db: Db,
  scope: ResolveAutonomyScope,
): Promise<AutonomyLayers> {
  const world = await readJsonColumn(db, "worlds", scope.worldId,);
  const chat = await readJsonColumn(db, "chats", scope.chatId,);
  const actor = scope.actorId ? await readActorOverride(db, scope.actorId,) : {};
  return { layers: { world, chat, actor, }, resolved: mergeLayers(world, chat, actor,), };
}

/**
 * Apply the four layers into one config. The preset name resolves
 * actor > chat > world > default; values layer lowest-first onto the
 * preset baseline.
 * @param world
 * @param chat
 * @param actor
 * @returns the merged config
 */
function mergeLayers(
  world: AutonomyConfigOverride,
  chat: AutonomyConfigOverride,
  actor: AutonomyConfigOverride,
): AutonomyConfig {
  // preset name: actor > chat > world > DEFAULT.
  const presetName: PacingPresetName = actor.preset ?? chat.preset ?? world.preset ?? DEFAULT_PRESET;
  const preset = getPreset(presetName,);

  // Start from preset baseline; layers apply in order (lowest first).
  const out: AutonomyConfig = {
    preset: presetName,
    enabled: true,
    tickIntervalMs: preset.tickIntervalMs,
    jitterRatio: preset.jitterRatio,
    perAgentCap: preset.perAgentCap,
    perUserCap: preset.perUserCap,
  };

  applyLayer(out, world,);
  applyLayer(out, chat,);
  applyLayer(out, actor,);
  return out;
}

/**
 * Resolve the full autonomy config for a scope. Reads 2–3 rows
 * depending on whether `actorId` is supplied. Pure I/O; safe to call
 * per tick.
 * @param db
 * @param scope
 * @returns Fully layered AutonomyConfig.
 */
export async function resolveAutonomyConfig(
  db: Db,
  scope: ResolveAutonomyScope,
): Promise<AutonomyConfig> {
  const world = await readJsonColumn(db, "worlds", scope.worldId,);
  const chat = await readJsonColumn(db, "chats", scope.chatId,);
  const actor = scope.actorId ? await readActorOverride(db, scope.actorId,) : {};
  return mergeLayers(world, chat, actor,);
}
