/**
 * DB Schema — Telemetry Domain Tables
 *
 * Auto-generated by scripts/generate-db-types.ts
 * DO NOT EDIT MANUALLY — run `bun run db:sync-types` to regenerate.
 */
import type { Generated, } from "kysely";

// ── telemetry_events ────────────────────────────────────────────
export interface TelemetryEvents {
  id: Generated<string>;
  session_id: string | null;
  user_id: string | null;
  chat_id: string | null;
  event_type: string;
  event_data: Generated<string>;
  source: Generated<string>;
  created_at: string;
}
