/**
 * DB Schema — Content Domain Tables
 *
 * Auto-generated by scripts/generate-db-types.ts
 * DO NOT EDIT MANUALLY — run `bun run db:sync-types` to regenerate.
 */
import type { Generated, } from "kysely";
import type {
  AssetAlphaStatus,
  AssetLinkEntity,
  AssetType,
  AssetVisibility,
  StorageBackend,
} from "./enums";

// ── asset_links ────────────────────────────────────────────
export interface AssetLinks {
  asset_id: string;
  entity_type: AssetLinkEntity;
  entity_id: string;
  label: string | null;
  sort_order: Generated<number>;
  created_at: Generated<string>;
}

// ── asset_shares ────────────────────────────────────────────
export interface AssetShares {
  id: Generated<string>;
  asset_id: string;
  shared_with_id: string;
  shared_by_id: string;
  created_at: Generated<string>;
}

// ── assets ────────────────────────────────────────────
export interface Assets {
  id: Generated<string>;
  owner_id: string;
  filename: string;
  mime_type: string;
  asset_type: AssetType;
  size_bytes: number;
  storage_path: string;
  storage_backend: Generated<StorageBackend>;
  width: number | null;
  height: number | null;
  duration_secs: number | null;
  alt_text: string | null;
  visibility: Generated<AssetVisibility>;
  created_at: Generated<string>;
  encryption_tier: Generated<string>;
  encrypted_key_id: string | null;
  alpha_status: Generated<AssetAlphaStatus>;
  content_hash: string | null;
  data_version: Generated<number>;
  record_hash: Generated<string>;
  thumbnail_path: string | null;
}

// ── asset_tags ────────────────────────────────────────────
export interface AssetTags {
  id: Generated<string>;
  asset_id: string;
  tag: string;
  scope: Generated<string>;
  owner_id: string | null;
  source: Generated<string>;
  created_at: Generated<string>;
}

// ── asset_tag_dismissals ────────────────────────────────────────────
export interface AssetTagDismissals {
  id: Generated<string>;
  asset_id: string;
  tag: string;
  user_id: string;
  created_at: Generated<string>;
}
