/**
 * DB Schema — Synthetic Domain Tables
 *
 * Auto-generated by scripts/generate-db-types.ts
 * DO NOT EDIT MANUALLY — run `bun run db:sync-types` to regenerate.
 */
import type { Generated, } from "kysely";
import type { SyntheticDataStatus, SyntheticDataType, } from "./enums";

// ── synthetic_data ────────────────────────────────────────────
export interface SyntheticData {
  id: Generated<string>;
  chat_id: string | null;
  world_id: string | null;
  type: SyntheticDataType;
  source_data: string;
  generated_cases: string;
  metadata: Generated<string>;
  status: Generated<SyntheticDataStatus>;
  created_at: Generated<string>;
  validated_at: string | null;
  validated_by: string | null;
}
