/**
 * DB Schema Manifest — Single Source of Truth (AUTO-GENERATED)
 *
 * Generated by scripts/generate-schema-manifest.ts
 * DO NOT EDIT MANUALLY — run `bun run db:sync-manifest` to regenerate.
 *
 * Runtime representation of every table and its columns.
 * Used by:
 *   - schema-sync.test.ts: verify migrations produce correct DB
 *   - test-utils: typed insert helpers
 *   - future: generate EXPECTED_TABLES, insert defaults, etc.
 *
 * When adding a table or column:
 *   1. Add migration file
 *   2. Run `bun run db:sync-manifest`
 *   3. This test validates everything lines up
 */
import type { DB, } from "./schema";

/** Type-safe table name from the DB interface. */
export type TableName = keyof DB;

// ── Types ─────────────────────────────────────────────────────

interface ColMeta {
  /** SQLite storage type */
  type: "text" | "integer" | "real" | "blob";
  /** NOT NULL constraint */
  notNull?: boolean;
  /** Has DEFAULT expression or value */
  hasDefault?: boolean;
  /** Is part of PRIMARY KEY */
  primaryKey?: boolean;
}

interface TableMeta {
  columns: Record<string, ColMeta>;
}

// ── SchemaManifest ────────────────────────────────────────────

export class SchemaManifest {
  readonly tables = new Map<string, TableMeta>();

  /** Register a table. Chainable. */
  table(name: string, columns: Record<string, ColMeta>,): this {
    this.tables.set(name, { columns, },);
    return this;
  }

  /** All table names, sorted. */
  get tableNames(): string[] {
    return [...this.tables.keys(),].sort();
  }

  /** Column names for a table, in registration order. */
  columnsOf(name: string,): string[] {
    const t = this.tables.get(name,);
    if (!t) { throw new Error(`Unknown table: ${name}`,); }
    return Object.keys(t.columns,);
  }

  /** Column metadata for a table. */
  tableOf(name: string,): TableMeta {
    const t = this.tables.get(name,);
    if (!t) { throw new Error(`Unknown table: ${name}`,); }
    return t;
  }

  /**
   * Verify an in-memory SQLite DB matches this manifest.
   * Returns structured diff for test assertions.
   */
  verify(sqlite: { query(sql: string, params?: unknown[],): { all(): unknown[] } },): {
    missingTables: string[];
    extraTables: string[];
    columnMismatches: {
      table: string;
      missingInDb: string[];
      extraInDb: string[];
    }[];
  } {
    const rows = sqlite
      .query("SELECT name, sql FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'kysely_%'",)
      .all() as { name: string; sql: string | null }[];
    // FTS5 virtual tables (created via raw SQL) and their internal shadow tables
    // are implementation details — drop them so they are not treated as extra tables.
    const virtualRoots = new Set(
      rows.filter((r,) => (r.sql ?? "").trim().toUpperCase().startsWith("CREATE VIRTUAL TABLE",))
        .map((r,) => r.name),
    );
    const actualTables = new Set(
      rows.filter((r,) => {
        if (virtualRoots.has(r.name,)) { return false; }
        for (const suffix of ["_data", "_idx", "_content", "_docsize", "_config",]) {
          if (r.name.endsWith(suffix,) && virtualRoots.has(r.name.slice(0, -suffix.length,),)) {
            return false;
          }
        }
        return true;
      },).map((r,) => r.name),
    );

    const missingTables: string[] = [];
    const extraTables: string[] = [];
    const columnMismatches: {
      table: string;
      missingInDb: string[];
      extraInDb: string[];
    }[] = [];

    // Check each manifest table exists in DB
    for (const name of this.tableNames) {
      if (!actualTables.has(name,)) {
        missingTables.push(name,);
        continue;
      }

      const expected = this.columnsOf(name,);
      const actualCols = (sqlite.query(`PRAGMA table_info("${name}")`,).all() as { name: string }[]).map(
        (r,) => r.name,
      );

      const expectedSet = new Set(expected,);
      const actualSet = new Set(actualCols,);

      const missingInDb = expected.filter((c,) => !actualSet.has(c,));
      const extraInDb = actualCols.filter((c,) => !expectedSet.has(c,));

      if (missingInDb.length > 0 || extraInDb.length > 0) {
        columnMismatches.push({ table: name, missingInDb, extraInDb, },);
      }
    }

    // Extra tables in DB (not in manifest)
    for (const name of actualTables) {
      if (!this.tables.has(name,)) {
        extraTables.push(name,);
      }
    }

    return { missingTables, extraTables, columnMismatches, };
  }
}

// ── The Single Source of Truth (AUTO-GENERATED) ────────────────
//
// Every table, every column — parsed from src/db/migrations/*.ts
// Generated by: bun run db:sync-manifest

function col(type: ColMeta["type"], opts?: Omit<ColMeta, "type">,): ColMeta {
  return { type, ...opts, };
}

export const SCHEMA = new SchemaManifest()
  // ── Misc ──────────────────────────────────────────────
  .table("achievements", {
    id: col("text", { primaryKey: true, hasDefault: true, },),
    name: col("text", { notNull: true, },),
    description: col("text", { notNull: true, },),
    category: col("text", { notNull: true, },),
    tier: col("text", { notNull: true, },),
    icon: col("text",),
    is_secret: col("integer", { notNull: true, hasDefault: true, },),
    is_hidden: col("integer", { notNull: true, hasDefault: true, },),
    unlock_condition: col("text", { notNull: true, hasDefault: true, },),
    rewards: col("text", { notNull: true, hasDefault: true, },),
    metadata: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("battles", {
    id: col("text", { primaryKey: true, hasDefault: true, },),
    chat_id: col("text", { notNull: true, },),
    world_id: col("text",),
    status: col("text", { notNull: true, hasDefault: true, },),
    round: col("integer", { notNull: true, hasDefault: true, },),
    turn_index: col("integer", { notNull: true, hasDefault: true, },),
    combatants: col("text", { notNull: true, hasDefault: true, },),
    log: col("text", { notNull: true, hasDefault: true, },),
    created_by: col("text", { notNull: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    ended_at: col("text",),
  },)
  .table("crafting_attempts", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    world_id: col("text", { notNull: true, },),
    recipe_id: col("text", { notNull: true, },),
    station_instance_id: col("text",),
    materials_used: col("text", { notNull: true, hasDefault: true, },),
    status: col("text", { notNull: true, },),
    quality_achieved: col("integer", { notNull: true, hasDefault: true, },),
    output_item_id: col("text",),
    output_quantity: col("integer", { notNull: true, hasDefault: true, },),
    experience_gained: col("integer", { notNull: true, hasDefault: true, },),
    skill_increase: col("integer", { notNull: true, hasDefault: true, },),
    bonus_effects: col("text", { notNull: true, hasDefault: true, },),
    duration_ms: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
  },)
  .table("crafting_orders", {
    id: col("text", { primaryKey: true, },),
    world_id: col("text", { notNull: true, },),
    requester_actor_id: col("text", { notNull: true, },),
    crafter_actor_id: col("text",),
    recipe_id: col("text", { notNull: true, },),
    quantity: col("integer", { notNull: true, hasDefault: true, },),
    max_quality: col("text",),
    offered_payment: col("integer", { notNull: true, hasDefault: true, },),
    offered_materials: col("text", { notNull: true, hasDefault: true, },),
    requested_materials: col("text", { notNull: true, hasDefault: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    deadline: col("text",),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
    trade_type: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("crafting_recipe_materials", {
    id: col("text", { primaryKey: true, },),
    recipe_id: col("text", { notNull: true, },),
    item_id: col("text", { notNull: true, },),
    quantity: col("integer", { notNull: true, hasDefault: true, },),
    slot_type: col("text", { notNull: true, hasDefault: true, },),
    quality_requirement: col("text",),
    bonus_effect: col("text",),
    sort_order: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
  },)
  .table("crafting_recipes", {
    id: col("text", { primaryKey: true, },),
    world_id: col("text", { notNull: true, },),
    name: col("text", { notNull: true, },),
    description: col("text",),
    discipline: col("text", { notNull: true, },),
    tier: col("integer", { notNull: true, hasDefault: true, },),
    level_required: col("integer", { notNull: true, hasDefault: true, },),
    output_item_id: col("text", { notNull: true, },),
    output_quantity: col("integer", { notNull: true, hasDefault: true, },),
    crafting_time_seconds: col("integer", { notNull: true, hasDefault: true, },),
    base_success_chance: col("real", { notNull: true, hasDefault: true, },),
    base_quality_min: col("integer", { notNull: true, hasDefault: true, },),
    base_quality_max: col("integer", { notNull: true, hasDefault: true, },),
    perfect_threshold: col("integer", { notNull: true, hasDefault: true, },),
    station_type_required: col("text",),
    discovered_by_default: col("integer", { notNull: true, hasDefault: true, },),
    tags: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("crafting_station_defs", {
    id: col("text", { primaryKey: true, },),
    world_id: col("text", { notNull: true, },),
    name: col("text", { notNull: true, },),
    description: col("text",),
    station_type: col("text", { notNull: true, },),
    tier: col("integer", { notNull: true, hasDefault: true, },),
    speed_bonus: col("real", { notNull: true, hasDefault: true, },),
    quality_bonus: col("real", { notNull: true, hasDefault: true, },),
    success_bonus: col("real", { notNull: true, hasDefault: true, },),
    material_saving_chance: col("real", { notNull: true, hasDefault: true, },),
    max_durability: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("crafting_station_instances", {
    id: col("text", { primaryKey: true, },),
    station_def_id: col("text", { notNull: true, },),
    world_id: col("text", { notNull: true, },),
    location_id: col("text",),
    owner_actor_id: col("text",),
    current_durability: col("integer", { notNull: true, },),
    is_active: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("data_migrations", {
    table_name: col("text", { notNull: true, },),
    from_version: col("integer", { notNull: true, },),
    to_version: col("integer", { notNull: true, },),
    description: col("text", { notNull: true, },),
    applied_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("dice_roll_history", {
    id: col("text", { primaryKey: true, hasDefault: true, },),
    user_id: col("text", { notNull: true, },),
    chat_id: col("text",),
    actor_id: col("text",),
    sides: col("integer", { notNull: true, },),
    count: col("integer", { notNull: true, },),
    modifier: col("integer", { notNull: true, hasDefault: true, },),
    advantage_mode: col("text", { notNull: true, hasDefault: true, },),
    exploding: col("integer", { notNull: true, hasDefault: true, },),
    raw_rolls: col("text", { notNull: true, },),
    raw_total: col("integer", { notNull: true, },),
    total: col("integer", { notNull: true, },),
    purpose: col("text",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("e2e_group_wraps", {
    id: col("text", { primaryKey: true, },),
    group_session_id: col("text", { notNull: true, },),
    recipient_actor_id: col("text", { notNull: true, },),
    wrapped_key: col("text", { notNull: true, },),
    sender_eph_pub_jwk: col("text", { notNull: true, },),
    chain_index: col("integer", { notNull: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("e2e_sessions", {
    id: col("text", { primaryKey: true, },),
    sender_actor_id: col("text", { notNull: true, },),
    recipient_actor_id: col("text",),
    chat_id: col("text",),
    kind: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    last_message_at: col("text",),
    revoked_at: col("text",),
    root_key: col("blob",),
    sending_chain_key: col("blob",),
    receiving_chain_key: col("blob",),
    send_count: col("integer", { notNull: true, hasDefault: true, },),
    recv_count: col("integer", { notNull: true, hasDefault: true, },),
    ephemeral_public_jwk: col("text",),
    ephemeral_private_jwk: col("text",),
  },)
  .table("e2e_skipped_keys", {
    id: col("text", { primaryKey: true, },),
    session_id: col("text", { notNull: true, },),
    dh_public_jwk: col("text", { notNull: true, },),
    counter: col("integer", { notNull: true, },),
    encrypted_message_key: col("text", { notNull: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    expires_at: col("text", { notNull: true, },),
  },)
  .table("e2e_skipped_message_keys", {
    id: col("text", { primaryKey: true, },),
    session_id: col("text", { notNull: true, },),
    recipient_actor_id: col("text", { notNull: true, },),
    chain_index: col("integer", { notNull: true, },),
    message_key: col("text", { notNull: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("emotions", {
    id: col("text", { primaryKey: true, },),
    name: col("text", { notNull: true, },),
    display_name: col("text", { notNull: true, },),
    category: col("text", { notNull: true, },),
    valence: col("real", { notNull: true, },),
    arousal: col("real", { notNull: true, },),
    icon: col("text", { hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
  },)
  .table("gathering_node_defs", {
    id: col("text", { primaryKey: true, },),
    world_id: col("text", { notNull: true, },),
    name: col("text", { notNull: true, },),
    description: col("text",),
    node_type: col("text", { notNull: true, },),
    skill_required: col("integer", { notNull: true, hasDefault: true, },),
    respawn_time_seconds: col("integer", { notNull: true, hasDefault: true, },),
    rarity: col("text", { notNull: true, hasDefault: true, },),
    max_uses: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("gathering_node_instances", {
    id: col("text", { primaryKey: true, },),
    node_def_id: col("text", { notNull: true, },),
    world_id: col("text", { notNull: true, },),
    location_id: col("text",),
    current_uses: col("integer", { notNull: true, },),
    state: col("text", { notNull: true, hasDefault: true, },),
    respawn_at: col("text",),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("gathering_node_materials", {
    id: col("text", { primaryKey: true, },),
    node_def_id: col("text", { notNull: true, },),
    item_id: col("text", { notNull: true, },),
    min_quantity: col("integer", { notNull: true, hasDefault: true, },),
    max_quantity: col("integer", { notNull: true, hasDefault: true, },),
    drop_chance: col("real", { notNull: true, hasDefault: true, },),
    min_quality: col("text",),
    max_quality: col("text",),
    sort_order: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
  },)
  .table("generation_attempts", {
    id: col("text", { primaryKey: true, },),
    chat_id: col("text", { notNull: true, },),
    parent_message_id: col("text", { notNull: true, },),
    actor_id: col("text", { notNull: true, },),
    idempotency_key: col("text", { notNull: true, },),
    model_id: col("text", { notNull: true, },),
    provider: col("text", { notNull: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    cancel_reason: col("text",),
    cancel_reason_detail: col("text",),
    cancel_source: col("text",),
    abort_signal_id: col("text",),
    started_at: col("text", { notNull: true, hasDefault: true, },),
    completed_at: col("text",),
    prompt_tokens: col("integer",),
    completion_tokens: col("integer",),
    total_tokens: col("integer",),
    generation_time_ms: col("integer",),
    error_message: col("text",),
    streaming_chunks_received: col("integer",),
    streaming_chars_received: col("integer",),
    repetition_score: col("real",),
    repetition_analysis: col("text",),
    policy_analysis: col("text",),
    response_count_in_turn: col("integer",),
    parent_attempt_id: col("text",),
    continuation_count: col("integer", { hasDefault: true, },),
    partial_content: col("text",),
    step_index: col("integer", { hasDefault: true, },),
    total_steps: col("integer", { hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    last_rendered_chunk_index: col("integer",),
    delivery_confirmed_at: col("text",),
    side_effect_jobs_cancelled: col("integer", { hasDefault: true, },),
  },)
  .table("group_initiatives", {
    chat_id: col("text", { notNull: true, },),
    scene_id: col("text", { notNull: true, },),
    actor_id: col("text", { notNull: true, },),
    score: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("growth_log", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    axis: col("text", { notNull: true, },),
    event_type: col("text", { notNull: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    subject_kind: col("text",),
    subject_id: col("text",),
    before_json: col("text",),
    after_json: col("text",),
    reason: col("text", { notNull: true, hasDefault: true, },),
    source_event_id: col("text",),
    recorded_at: col("text", { notNull: true, },),
    confirmed_at: col("text",),
    confirmed_by: col("text",),
  },)
  .table("log_entries", {
    id: col("text", { primaryKey: true, },),
    level: col("integer", { notNull: true, hasDefault: true, },),
    timestamp: col("real", { notNull: true, },),
    time: col("text", { notNull: true, },),
    message: col("text", { notNull: true, },),
    module: col("text",),
    user_id: col("text",),
    session_id: col("text",),
    request_id: col("text",),
    meta: col("text",),
    event_type: col("text",),
    entity_type: col("text",),
    entity_id: col("text",),
    action: col("text",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("loot_entries", {
    id: col("text", { primaryKey: true, hasDefault: true, },),
    loot_table_id: col("text", { notNull: true, },),
    item_name: col("text", { notNull: true, },),
    description: col("text",),
    item_type: col("text", { notNull: true, },),
    rarity: col("text", { notNull: true, hasDefault: true, },),
    weight: col("integer", { notNull: true, hasDefault: true, },),
    min_quantity: col("integer", { notNull: true, hasDefault: true, },),
    max_quantity: col("integer", { notNull: true, hasDefault: true, },),
    min_level: col("integer", { notNull: true, hasDefault: true, },),
    metadata: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("loot_tables", {
    id: col("text", { primaryKey: true, hasDefault: true, },),
    name: col("text", { notNull: true, },),
    source_type: col("text", { notNull: true, },),
    source_id: col("text",),
    total_weight: col("integer", { notNull: true, hasDefault: true, },),
    used: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("memory_embeddings", {
    memory_id: col("text", { primaryKey: true, },),
    model: col("text", { notNull: true, hasDefault: true, },),
    dimensions: col("integer", { notNull: true, hasDefault: true, },),
    vector_blob: col("blob", { notNull: true, },),
    created_at: col("integer", { notNull: true, },),
  },)
  .table("message_reactions", {
    id: col("text", { primaryKey: true, },),
    message_id: col("text", { notNull: true, },),
    user_id: col("text", { notNull: true, },),
    emoji: col("text", { notNull: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("message_seen", {
    id: col("text", { primaryKey: true, },),
    message_id: col("text", { notNull: true, },),
    actor_id: col("text", { notNull: true, },),
    state: col("text", { notNull: true, hasDefault: true, },),
    seen_at: col("text",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("message_translations", {
    id: col("text", { primaryKey: true, },),
    message_id: col("text", { notNull: true, },),
    locale: col("text", { notNull: true, },),
    content: col("text", { notNull: true, },),
    provider: col("text",),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text",),
  },)
  .table("meta_progression", {
    player_id: col("text", { primaryKey: true, },),
    total_playthroughs: col("integer", { notNull: true, hasDefault: true, },),
    endings_seen: col("text", { notNull: true, hasDefault: true, },),
    secrets_found: col("text", { notNull: true, hasDefault: true, },),
    achievements_unlocked: col("text", { notNull: true, hasDefault: true, },),
    permanent_bonuses: col("text", { notNull: true, hasDefault: true, },),
    unlocked_content: col("text", { notNull: true, hasDefault: true, },),
    metadata: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("mood_events", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    world_id: col("text",),
    event_type: col("text", { notNull: true, },),
    happiness_delta: col("integer", { notNull: true, },),
    mood_override: col("text", { hasDefault: true, },),
    source: col("text", { notNull: true, },),
    source_id: col("text", { hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
  },)
  .table("music_links", {
    id: col("text", { primaryKey: true, },),
    chat_id: col("text", { notNull: true, },),
    section_id: col("text",),
    sender_id: col("text", { notNull: true, },),
    service: col("text", { notNull: true, },),
    url: col("text", { notNull: true, },),
    embed_html: col("text",),
    title: col("text", { notNull: true, },),
    artist: col("text", { notNull: true, },),
    thumbnail_url: col("text",),
    duration_secs: col("integer",),
    service_track_id: col("text", { notNull: true, },),
    service_url: col("text", { notNull: true, },),
    is_playlist: col("integer", { notNull: true, hasDefault: true, },),
    track_count: col("integer",),
    explicit: col("integer", { notNull: true, hasDefault: true, },),
    year: col("integer",),
    genre: col("text",),
    nsfw_hidden: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("npc_states", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    world_id: col("text", { notNull: true, },),
    location_id: col("text",),
    health: col("integer", { notNull: true, hasDefault: true, },),
    mental_state: col("text", { notNull: true, hasDefault: true, },),
    knowledge: col("text", { notNull: true, hasDefault: true, },),
    relationships: col("text", { notNull: true, hasDefault: true, },),
    inventory: col("text", { notNull: true, hasDefault: true, },),
    schedule: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("player_achievements", {
    id: col("text", { primaryKey: true, hasDefault: true, },),
    player_id: col("text", { notNull: true, },),
    achievement_id: col("text", { notNull: true, },),
    progress: col("integer", { notNull: true, hasDefault: true, },),
    max_progress: col("integer", { notNull: true, hasDefault: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    unlocked_at: col("text",),
    claimed_at: col("text",),
    metadata: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("playthroughs", {
    id: col("text", { primaryKey: true, hasDefault: true, },),
    player_id: col("text", { notNull: true, },),
    world_id: col("text", { notNull: true, },),
    playthrough_number: col("integer", { notNull: true, hasDefault: true, },),
    difficulty: col("text", { notNull: true, hasDefault: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    ending_id: col("text",),
    ending_type: col("text",),
    completion_time: col("integer", { notNull: true, hasDefault: true, },),
    choices_made: col("integer", { notNull: true, hasDefault: true, },),
    secrets_found: col("integer", { notNull: true, hasDefault: true, },),
    achievements_unlocked: col("integer", { notNull: true, hasDefault: true, },),
    metadata: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    completed_at: col("text",),
  },)
  .table("proactive_messaging_config", {
    id: col("text", { primaryKey: true, },),
    chat_id: col("text", { notNull: true, },),
    actor_id: col("text", { notNull: true, },),
    frequency: col("text", { notNull: true, hasDefault: true, },),
    quiet_hours_start: col("text",),
    quiet_hours_end: col("text",),
    enabled: col("integer", { notNull: true, hasDefault: true, },),
    last_proactive_at: col("text",),
    backoff_count: col("integer", { notNull: true, hasDefault: true, },),
    config_json: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("profession_specializations", {
    id: col("text", { primaryKey: true, },),
    profession_id: col("text", { notNull: true, },),
    name: col("text", { notNull: true, },),
    description: col("text",),
    bonus_type: col("text", { notNull: true, },),
    bonus_value: col("real", { notNull: true, hasDefault: true, },),
    requirement_level: col("integer", { notNull: true, hasDefault: true, },),
    requirement_specializations: col("text", { notNull: true, hasDefault: true, },),
    is_active: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
  },)
  .table("professions", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    world_id: col("text", { notNull: true, },),
    discipline: col("text", { notNull: true, },),
    level: col("integer", { notNull: true, hasDefault: true, },),
    experience: col("integer", { notNull: true, hasDefault: true, },),
    title: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("recipe_discoveries", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    world_id: col("text", { notNull: true, },),
    recipe_id: col("text", { notNull: true, },),
    discovery_method: col("text", { notNull: true, },),
    discovered_at: col("text", { notNull: true, },),
    mastery_level: col("integer", { notNull: true, hasDefault: true, },),
  },)
  .table("request_results", {
    id: col("text", { primaryKey: true, },),
    method: col("text", { notNull: true, },),
    route_pattern: col("text", { notNull: true, },),
    user_id: col("text",),
    status: col("text", { notNull: true, },),
    progress: col("text",),
    response_status: col("integer",),
    response_headers: col("text",),
    response_body: col("text",),
    error: col("text",),
    started_at: col("text", { notNull: true, },),
    completed_at: col("text",),
    offloaded_at: col("text",),
    offload_path: col("text",),
    data_version: col("integer", { notNull: true, hasDefault: true, },),
    record_hash: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("schema_version", {
    version: col("integer", { primaryKey: true, },),
    applied_at: col("text", { notNull: true, hasDefault: true, },),
    description: col("text",),
  },)
  .table("seed_audit", {
    id: col("text", { primaryKey: true, },),
    seed_type: col("text", { notNull: true, },),
    seed_id: col("text", { notNull: true, },),
    seeded_by: col("text", { notNull: true, },),
    seeded_at: col("text", { notNull: true, },),
    environment: col("text", { notNull: true, },),
    metadata: col("text",),
  },)
  .table("shadow_notes", {
    id: col("text", { primaryKey: true, },),
    chat_id: col("text", { notNull: true, },),
    type: col("text", { notNull: true, },),
    content: col("text", { notNull: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
  },)
  .table("synthetic_data", {
    id: col("text", { primaryKey: true, },),
    chat_id: col("text",),
    world_id: col("text",),
    type: col("text", { notNull: true, },),
    source_data: col("text", { notNull: true, },),
    generated_cases: col("text", { notNull: true, },),
    metadata: col("text", { notNull: true, hasDefault: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    validated_at: col("text",),
    validated_by: col("text",),
  },)
  .table("system_config", {
    key: col("text", { primaryKey: true, },),
    value: col("text", { notNull: true, },),
    description: col("text",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("telemetry_events", {
    id: col("text", { primaryKey: true, },),
    session_id: col("text",),
    user_id: col("text",),
    chat_id: col("text",),
    event_type: col("text", { notNull: true, },),
    event_data: col("text", { notNull: true, hasDefault: true, },),
    source: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
  },)
  .table("trade_history", {
    id: col("text", { primaryKey: true, },),
    world_id: col("text", { notNull: true, },),
    buyer_actor_id: col("text", { notNull: true, },),
    seller_actor_id: col("text", { notNull: true, },),
    price: col("integer", { notNull: true, hasDefault: true, },),
    currency_type: col("text", { notNull: true, hasDefault: true, },),
    items_offered: col("text", { notNull: true, hasDefault: true, },),
    items_requested: col("text", { notNull: true, hasDefault: true, },),
    trade_type: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
  },)
  .table("vn_choices", {
    id: col("text", { primaryKey: true, },),
    chat_id: col("text", { notNull: true, },),
    scene_index: col("integer", { notNull: true, },),
    label: col("text", { notNull: true, },),
    description: col("text",),
    consequences: col("text", { notNull: true, hasDefault: true, },),
    relationship_impact: col("text", { notNull: true, hasDefault: true, },),
    mood_impact: col("text", { notNull: true, hasDefault: true, },),
    unlock_conditions: col("text", { notNull: true, hasDefault: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    selected_at: col("text",),
    created_at: col("text", { notNull: true, },),
  },)
  .table("whitenotes", {
    id: col("text", { primaryKey: true, },),
    chat_id: col("text", { notNull: true, },),
    type: col("text", { notNull: true, },),
    content: col("text", { notNull: true, },),
    priority: col("integer", { notNull: true, hasDefault: true, },),
    scope: col("text", { notNull: true, hasDefault: true, },),
    expires_at: col("text",),
    created_at: col("text", { notNull: true, },),
  },)
  .table("xp_ledger", {
    id: col("text", { primaryKey: true, hasDefault: true, },),
    actor_id: col("text", { notNull: true, },),
    amount: col("integer", { notNull: true, },),
    source: col("text", { notNull: true, },),
    description: col("text",),
    reference_id: col("text",),
    chat_id: col("text",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  // ── Activity & Notifications ──────────────────────────────────────────────
  .table("activitypub_actor_keys", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    key_id: col("text", { notNull: true, },),
    public_jwk: col("text", { notNull: true, },),
    encrypted_private_jwk: col("text", { notNull: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    rotated_at: col("text",),
    created_at: col("text", { notNull: true, },),
    expires_at: col("text",),
  },)
  .table("notifications", {
    id: col("text", { primaryKey: true, },),
    user_id: col("text", { notNull: true, },),
    type: col("text", { notNull: true, },),
    title: col("text", { notNull: true, },),
    body: col("text",),
    link: col("text",),
    read: col("text", { notNull: true, hasDefault: true, },),
    data: col("text",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  // ── Core: Actor Systems ──────────────────────────────────────────────
  .table("actor_currencies", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    world_id: col("text", { notNull: true, },),
    currency_type: col("text", { notNull: true, },),
    balance: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("actor_e2e_pubkeys", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    public_key_jwk: col("text", { notNull: true, },),
    algorithm: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    expires_at: col("text",),
    revoked_at: col("text",),
  },)
  .table("actor_items", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    name: col("text", { notNull: true, },),
    description: col("text",),
    item_type: col("text", { notNull: true, },),
    quantity: col("integer", { notNull: true, hasDefault: true, },),
    value: col("integer", { notNull: true, hasDefault: true, },),
    weight: col("real",),
    tags: col("text", { hasDefault: true, },),
    metadata: col("text", { hasDefault: true, },),
    equipped: col("text", { notNull: true, hasDefault: true, },),
    sort_order: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    durability: col("integer", { notNull: true, hasDefault: true, },),
    max_durability: col("integer", { notNull: true, hasDefault: true, },),
  },)
  .table("actor_keys", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    name: col("text", { notNull: true, },),
    key_type: col("text", { notNull: true, },),
    encrypted_key: col("text", { notNull: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    expires_at: col("text",),
    status: col("text", { notNull: true, hasDefault: true, },),
    public_key: col("text",),
  },)
  .table("actor_lore_entries", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    name: col("text",),
    content: col("text", { notNull: true, },),
    keys: col("text", { notNull: true, hasDefault: true, },),
    secondary_keys: col("text", { hasDefault: true, },),
    selective: col("integer", { notNull: true, hasDefault: true, },),
    case_sensitive: col("integer", { notNull: true, hasDefault: true, },),
    enabled: col("text", { notNull: true, hasDefault: true, },),
    constant: col("integer", { notNull: true, hasDefault: true, },),
    position: col("text", { notNull: true, hasDefault: true, },),
    insertion_order: col("integer", { notNull: true, hasDefault: true, },),
    priority: col("integer", { notNull: true, hasDefault: true, },),
    comment: col("text",),
    sort_order: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    cooldown_seconds: col("integer", { notNull: true, hasDefault: true, },),
    last_activated: col("text",),
    audience_scope: col("text",),
    world_id: col("text",),
    key_type: col("text",),
    key_groups: col("text",),
    scan_depth: col("integer",),
    activation_chance: col("real",),
  },)
  .table("actor_memories", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    source_chat_id: col("text",),
    content: col("text", { notNull: true, },),
    memory_type: col("text", { notNull: true, hasDefault: true, },),
    confidence: col("real", { notNull: true, hasDefault: true, },),
    importance: col("integer", { notNull: true, hasDefault: true, },),
    keywords: col("text", { hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    expires_at: col("text",),
    decay_rate: col("real", { notNull: true, hasDefault: true, },),
    strength: col("real", { notNull: true, hasDefault: true, },),
    last_accessed_at: col("text",),
    source_message_id: col("text",),
    context: col("text",),
    world_id: col("text",),
    user_id: col("text",),
    scope: col("text", { notNull: true, hasDefault: true, },),
    pinned: col("text", { notNull: true, hasDefault: true, },),
    privacy: col("text", { notNull: true, hasDefault: true, },),
    shareability: col("text",),
  },)
  .table("actor_notes", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    title: col("text", { notNull: true, },),
    content: col("text", { notNull: true, },),
    category: col("text", { notNull: true, hasDefault: true, },),
    pinned: col("text", { notNull: true, hasDefault: true, },),
    sort_order: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("character_arc", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    current_stage: col("text", { notNull: true, },),
    stage_description: col("text",),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("character_arousal", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    world_id: col("text",),
    level: col("integer", { notNull: true, hasDefault: true, },),
    buildup_rate: col("real", { notNull: true, hasDefault: true, },),
    decay_rate: col("real", { notNull: true, hasDefault: true, },),
    modifiers: col("text", { notNull: true, hasDefault: true, },),
    last_update: col("text", { notNull: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("character_availability", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    usage_policy: col("text", { hasDefault: true, },),
    activity_restrictions: col("text", { hasDefault: true, },),
    content_policy: col("text", { hasDefault: true, },),
    nsfw_policy: col("text", { hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("character_avatar_config", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    selection_rule: col("text", { notNull: true, hasDefault: true, },),
    weights: col("text", { hasDefault: true, },),
    fallback_chain: col("text", { hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("character_avatars", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    asset_id: col("text", { notNull: true, },),
    label: col("text", { notNull: true, },),
    tags: col("text", { notNull: true, hasDefault: true, },),
    is_primary: col("integer", { notNull: true, hasDefault: true, },),
    sort_order: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("character_body_profile", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    stamina: col("integer", { notNull: true, hasDefault: true, },),
    flexibility: col("integer", { notNull: true, hasDefault: true, },),
    sensitivity: col("integer", { notNull: true, hasDefault: true, },),
    endurance: col("integer", { notNull: true, hasDefault: true, },),
    size_category: col("text", { notNull: true, hasDefault: true, },),
    build: col("text", { notNull: true, hasDefault: true, },),
    beauty: col("integer", { notNull: true, hasDefault: true, },),
    charisma: col("integer", { notNull: true, hasDefault: true, },),
    style: col("integer", { notNull: true, hasDefault: true, },),
    scent: col("text", { hasDefault: true, },),
    modifications: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
    world_id: col("text",),
  },)
  .table("character_desire_profile", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    turn_ons: col("text", { notNull: true, hasDefault: true, },),
    turn_offs: col("text", { notNull: true, hasDefault: true, },),
    fetishes: col("text", { notNull: true, hasDefault: true, },),
    hard_limits: col("text", { notNull: true, hasDefault: true, },),
    current_desire: col("integer", { notNull: true, hasDefault: true, },),
    desire_decay_rate: col("real", { notNull: true, hasDefault: true, },),
    desire_buildup_rate: col("real", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
    world_id: col("text",),
  },)
  .table("character_emotions", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    emotion_id: col("text", { notNull: true, },),
    intensity: col("real", { notNull: true, hasDefault: true, },),
    context: col("text", { hasDefault: true, },),
    expires_at: col("text", { hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("character_fantasies", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    fantasy_name: col("text", { notNull: true, },),
    category: col("text", { notNull: true, },),
    intensity: col("text", { notNull: true, hasDefault: true, },),
    requirements: col("text", { notNull: true, hasDefault: true, },),
    fulfillment_effects: col("text", { notNull: true, hasDefault: true, },),
    risks: col("text", { notNull: true, hasDefault: true, },),
    discovered_through: col("text", { hasDefault: true, },),
    initial_reaction: col("text", { notNull: true, hasDefault: true, },),
    current_feeling: col("text", { notNull: true, hasDefault: true, },),
    times_explored: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("character_heat_cycle", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    species: col("text", { notNull: true, hasDefault: true, },),
    cycle_length_days: col("integer", { notNull: true, hasDefault: true, },),
    current_phase: col("text", { notNull: true, hasDefault: true, },),
    days_until_next_heat: col("integer", { notNull: true, hasDefault: true, },),
    effects: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("character_internal_traits", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    aspirations: col("text", { notNull: true, hasDefault: true, },),
    moral_disposition: col("text", { notNull: true, hasDefault: true, },),
    autonomy_preferences: col("text", { notNull: true, hasDefault: true, },),
    coping_mechanisms: col("text", { notNull: true, hasDefault: true, },),
    approach_tendencies: col("text", { notNull: true, hasDefault: true, },),
    voice_patterns: col("text", { notNull: true, hasDefault: true, },),
    visibility: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("character_intimacy", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    target_actor_id: col("text", { notNull: true, },),
    world_id: col("text",),
    score: col("integer", { notNull: true, hasDefault: true, },),
    action_history: col("text", { notNull: true, hasDefault: true, },),
    unlocked_thresholds: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("character_licensing", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    license_type: col("text", { notNull: true, },),
    custom_license_text: col("text", { hasDefault: true, },),
    attribution: col("text", { hasDefault: true, },),
    allow_derivatives: col("integer", { notNull: true, hasDefault: true, },),
    allow_commercial: col("integer", { notNull: true, hasDefault: true, },),
    share_alike: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("character_location_traits", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    location_id: col("text", { notNull: true, },),
    trait_name: col("text", { notNull: true, },),
    trait_value: col("text", { notNull: true, },),
    bonus: col("integer", { hasDefault: true, },),
    penalty: col("integer", { hasDefault: true, },),
    effects: col("text", { hasDefault: true, },),
    equipment_override: col("text", { hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
    last_drifted_at: col("text",),
    drift_count: col("integer", { notNull: true, hasDefault: true, },),
  },)
  .table("character_mood", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    world_id: col("text",),
    happiness: col("integer", { notNull: true, hasDefault: true, },),
    base_mood: col("text", { notNull: true, hasDefault: true, },),
    current_mood: col("text", { notNull: true, hasDefault: true, },),
    mood_stability: col("real", { notNull: true, hasDefault: true, },),
    expression_modifiers: col("text", { hasDefault: true, },),
    last_mood_change: col("text", { notNull: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("character_permanent_traits", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    trait_category: col("text", { notNull: true, },),
    trait_name: col("text", { notNull: true, },),
    trait_value: col("text", { notNull: true, },),
    immutable: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("character_relationships", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    target_actor_id: col("text", { notNull: true, },),
    world_id: col("text",),
    relationship_type: col("text", { notNull: true, },),
    standing: col("integer", { notNull: true, hasDefault: true, },),
    trust: col("integer", { notNull: true, hasDefault: true, },),
    familiarity: col("integer", { notNull: true, hasDefault: true, },),
    is_bidirectional: col("integer", { notNull: true, hasDefault: true, },),
    metadata: col("text", { hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
    evolution_tracked: col("integer", { notNull: true, hasDefault: true, },),
    last_evolution_at: col("text",),
  },)
  .table("character_seduction_skills", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    skill_category: col("text", { notNull: true, },),
    skill_name: col("text", { notNull: true, },),
    level: col("integer", { notNull: true, hasDefault: true, },),
    xp: col("integer", { notNull: true, hasDefault: true, },),
    xp_to_next: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
    world_id: col("text",),
  },)
  .table("character_skills", {
    id: col("text", { primaryKey: true, hasDefault: true, },),
    actor_id: col("text", { notNull: true, },),
    world_id: col("text",),
    name: col("text", { notNull: true, },),
    category: col("text", { notNull: true, },),
    description: col("text",),
    level: col("integer", { notNull: true, hasDefault: true, },),
    xp: col("integer", { notNull: true, hasDefault: true, },),
    proficiency: col("text", { notNull: true, hasDefault: true, },),
    specialization: col("text",),
    lock_state: col("text", { notNull: true, hasDefault: true, },),
    prerequisites: col("text", { notNull: true, hasDefault: true, },),
    metadata: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    acquired_at: col("text",),
    acquisition_reason: col("text",),
    acquisition_source: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("character_stats", {
    id: col("text", { primaryKey: true, hasDefault: true, },),
    actor_id: col("text", { notNull: true, },),
    level: col("integer", { notNull: true, hasDefault: true, },),
    hp: col("integer", { notNull: true, },),
    max_hp: col("integer", { notNull: true, },),
    temp_hp: col("integer", { notNull: true, hasDefault: true, },),
    mp: col("integer", { notNull: true, hasDefault: true, },),
    max_mp: col("integer", { notNull: true, hasDefault: true, },),
    ac: col("integer", { notNull: true, },),
    speed: col("integer", { notNull: true, hasDefault: true, },),
    str: col("integer", { notNull: true, hasDefault: true, },),
    dex: col("integer", { notNull: true, hasDefault: true, },),
    con: col("integer", { notNull: true, hasDefault: true, },),
    int: col("integer", { notNull: true, hasDefault: true, },),
    wis: col("integer", { notNull: true, hasDefault: true, },),
    cha: col("integer", { notNull: true, hasDefault: true, },),
    hit_dice: col("text", { notNull: true, hasDefault: true, },),
    death_save_successes: col("integer", { notNull: true, hasDefault: true, },),
    death_save_failures: col("integer", { notNull: true, hasDefault: true, },),
    xp: col("integer", { notNull: true, hasDefault: true, },),
    xp_to_next: col("integer", { notNull: true, hasDefault: true, },),
    data_version: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    behavior_profile: col("text", { hasDefault: true, },),
    evasiveness: col("real", { hasDefault: true, },),
    cooperativeness: col("real", { hasDefault: true, },),
    aggression_threshold: col("real", { hasDefault: true, },),
    character_state: col("text", { notNull: true, hasDefault: true, },),
    conditions: col("text", { notNull: true, hasDefault: true, },),
    active_effects: col("text", { notNull: true, hasDefault: true, },),
    combat_alignment: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("character_world_setup", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    world_id: col("text", { notNull: true, },),
    starting_inventory: col("text", { notNull: true, hasDefault: true, },),
    lore_entries: col("text", { notNull: true, hasDefault: true, },),
    backstory: col("text",),
    scenario_override: col("text",),
    system_prompt_override: col("text",),
    initial_state: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("character_world_traits", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    world_id: col("text", { notNull: true, },),
    trait_category: col("text", { notNull: true, },),
    trait_name: col("text", { notNull: true, },),
    trait_value: col("text", { notNull: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
    last_drifted_at: col("text",),
    drift_count: col("integer", { notNull: true, hasDefault: true, },),
  },)
  // ── Core: Actors & Characters ──────────────────────────────────────────────
  .table("actors", {
    id: col("text", { primaryKey: true, },),
    actor_type: col("text", { notNull: true, hasDefault: true, },),
    display_name: col("text", { notNull: true, },),
    user_id: col("text",),
    owner_id: col("text",),
    avatar_asset_id: col("text",),
    description: col("text",),
    system_prompt: col("text",),
    agent_type: col("text", { notNull: true, hasDefault: true, },),
    settings: col("text", { notNull: true, hasDefault: true, },),
    format_version: col("integer", { notNull: true, hasDefault: true, },),
    visibility: col("text", { notNull: true, hasDefault: true, },),
    welcome_message: col("text",),
    personality: col("text",),
    scenario: col("text",),
    mes_example: col("text",),
    alternate_greetings: col("text",),
    post_history_instructions: col("text",),
    creator_notes: col("text",),
    creator: col("text",),
    character_version: col("text",),
    import_spec: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    content_rating: col("text", { notNull: true, hasDefault: true, },),
    template_overrides: col("text", { notNull: true, hasDefault: true, },),
    data_source_format: col("text", { hasDefault: true, },),
    data_raw: col("text",),
    agent_role: col("text",),
    growth_mode: col("text", { notNull: true, hasDefault: true, },),
    llm_assist_enabled: col("integer", { notNull: true, hasDefault: true, },),
  },)
  .table("characters", {
    id: col("text", { primaryKey: true, },),
    owner_id: col("text", { notNull: true, },),
    name: col("text", { notNull: true, },),
    avatar_asset_id: col("text",),
    description: col("text",),
    system_prompt: col("text",),
    agent_type: col("text", { notNull: true, hasDefault: true, },),
    settings: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    agent_role: col("text",),
    federation_consent: col("integer", { notNull: true, hasDefault: true, },),
    data_version: col("integer", { notNull: true, hasDefault: true, },),
    record_hash: col("text", { notNull: true, hasDefault: true, },),
  },)
  // ── Admin & Config ──────────────────────────────────────────────
  .table("admin_character_overrides", {
    id: col("text", { primaryKey: true, },),
    actor_id: col("text", { notNull: true, },),
    admin_id: col("text", { notNull: true, },),
    action: col("text", { notNull: true, },),
    visibility_override: col("text", { hasDefault: true, },),
    license_override: col("text", { hasDefault: true, },),
    reason: col("text", { hasDefault: true, },),
    expires_at: col("text", { hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
  },)
  // ── Assets ──────────────────────────────────────────────
  .table("asset_links", {
    asset_id: col("text", { notNull: true, },),
    entity_type: col("text", { notNull: true, },),
    entity_id: col("text", { notNull: true, },),
    label: col("text",),
    sort_order: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("asset_shares", {
    id: col("text", { primaryKey: true, },),
    asset_id: col("text", { notNull: true, },),
    shared_with_id: col("text", { notNull: true, },),
    shared_by_id: col("text", { notNull: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("assets", {
    id: col("text", { primaryKey: true, },),
    owner_id: col("text", { notNull: true, },),
    filename: col("text", { notNull: true, },),
    mime_type: col("text", { notNull: true, },),
    asset_type: col("text", { notNull: true, },),
    size_bytes: col("integer", { notNull: true, },),
    storage_path: col("text", { notNull: true, },),
    storage_backend: col("text", { notNull: true, hasDefault: true, },),
    width: col("integer",),
    height: col("integer",),
    duration_secs: col("real",),
    alt_text: col("text",),
    visibility: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    encryption_tier: col("text", { notNull: true, hasDefault: true, },),
    encrypted_key_id: col("text",),
    content_hash: col("text",),
    data_version: col("integer", { notNull: true, hasDefault: true, },),
    record_hash: col("text", { notNull: true, hasDefault: true, },),
  },)
  // ── Blog System ──────────────────────────────────────────────
  .table("blog_comments", {
    id: col("text", { primaryKey: true, },),
    post_id: col("text", { notNull: true, },),
    author_id: col("text", { notNull: true, },),
    body: col("text", { notNull: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    parent_comment_id: col("text",),
  },)
  .table("blog_follows", {
    id: col("text", { primaryKey: true, },),
    follower_id: col("text", { notNull: true, },),
    author_id: col("text", { notNull: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("blog_posts", {
    id: col("text", { primaryKey: true, },),
    author_id: col("text", { notNull: true, },),
    title: col("text", { notNull: true, },),
    body: col("text", { notNull: true, },),
    visibility: col("text", { notNull: true, hasDefault: true, },),
    author_type: col("text", { notNull: true, hasDefault: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    category: col("text",),
    world_id: col("text",),
    character_id: col("text",),
    scheduled_at: col("text",),
    published_at: col("text",),
    view_count: col("integer", { notNull: true, hasDefault: true, },),
    metadata: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("blog_rag_sources", {
    id: col("text", { primaryKey: true, },),
    post_id: col("text", { notNull: true, },),
    source_type: col("text", { notNull: true, },),
    uri: col("text", { notNull: true, },),
    title: col("text", { notNull: true, },),
    relevance_score: col("real", { notNull: true, hasDefault: true, },),
    snippet: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("blog_tags", {
    id: col("text", { primaryKey: true, },),
    post_id: col("text", { notNull: true, },),
    tag: col("text", { notNull: true, },),
  },)
  // ── Core: Chats & Messages ──────────────────────────────────────────────
  .table("chat_background_assignments", {
    id: col("text", { primaryKey: true, },),
    chat_id: col("text", { notNull: true, },),
    background_id: col("text", { notNull: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("chat_backgrounds", {
    id: col("text", { primaryKey: true, },),
    name: col("text", { notNull: true, },),
    type: col("text", { notNull: true, hasDefault: true, },),
    location_id: col("text",),
    asset_id: col("text",),
    config: col("text",),
    priority: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("chat_invites", {
    id: col("text", { primaryKey: true, },),
    chat_id: col("text", { notNull: true, },),
    code: col("text", { notNull: true, },),
    created_by: col("text",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    expires_at: col("text",),
    max_uses: col("integer",),
    uses: col("integer", { notNull: true, hasDefault: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("chat_keys", {
    id: col("text", { primaryKey: true, },),
    chat_id: col("text", { notNull: true, },),
    encrypted_chat_key: col("text", { notNull: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    expires_at: col("text",),
  },)
  .table("chat_location_events", {
    id: col("text", { primaryKey: true, },),
    chat_id: col("text", { notNull: true, },),
    section_id: col("text",),
    from_location_id: col("text",),
    to_location_id: col("text",),
    triggering_message_id: col("text",),
    source: col("text", { notNull: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("chat_mentions", {
    id: col("text", { primaryKey: true, },),
    message_id: col("text", { notNull: true, },),
    actor_id: col("text", { notNull: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("chat_participants", {
    chat_id: col("text", { notNull: true, },),
    actor_id: col("text", { notNull: true, },),
    role_in_chat: col("text", { notNull: true, hasDefault: true, },),
    joined_at: col("text", { notNull: true, hasDefault: true, },),
    last_read_message_id: col("text",),
    impersonate_actor_id: col("text",),
    persona_id: col("text",),
    talkativity: col("integer", { notNull: true, hasDefault: true, },),
    initiative: col("integer", { notNull: true, hasDefault: true, },),
  },)
  .table("chat_pins", {
    id: col("text", { primaryKey: true, },),
    chat_id: col("text", { notNull: true, },),
    message_id: col("text", { notNull: true, },),
    pinned_by: col("text", { notNull: true, },),
    pinned_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("chat_random_events", {
    id: col("text", { primaryKey: true, },),
    chat_id: col("text", { notNull: true, },),
    event_id: col("text", { notNull: true, },),
    category: col("text", { notNull: true, },),
    content: col("text", { notNull: true, },),
    token_count: col("integer", { notNull: true, },),
    fired_at: col("integer", { notNull: true, },),
    expires_at: col("integer", { notNull: true, },),
    fired_count: col("integer", { notNull: true, hasDefault: true, },),
  },)
  .table("chat_sections", {
    id: col("text", { primaryKey: true, },),
    chat_id: col("text", { notNull: true, },),
    label: col("text", { notNull: true, },),
    description: col("text",),
    location_id: col("text",),
    sort_index: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    background_id: col("text",),
  },)
  .table("chat_setup_templates", {
    id: col("text", { primaryKey: true, },),
    slug: col("text", { notNull: true, },),
    name: col("text", { notNull: true, },),
    description: col("text",),
    mode: col("text",),
    turn_strategy: col("text",),
    world_id: col("text",),
    gm_config: col("text",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    features: col("text", { hasDefault: true, },),
    visibility: col("text", { hasDefault: true, },),
  },)
  .table("chats", {
    id: col("text", { primaryKey: true, },),
    name: col("text", { notNull: true, },),
    type: col("text", { notNull: true, hasDefault: true, },),
    mode: col("text", { notNull: true, hasDefault: true, },),
    created_by: col("text", { notNull: true, },),
    world_id: col("text",),
    current_location_id: col("text",),
    story_state: col("text",),
    gm_config: col("text",),
    turn_strategy: col("text",),
    max_turns: col("integer",),
    auto_advance: col("integer",),
    parent_chat_id: col("text",),
    is_pinned: col("text", { notNull: true, hasDefault: true, },),
    encryption_level: col("text", { notNull: true, hasDefault: true, },),
    response_length_preset: col("text", { notNull: true, hasDefault: true, },),
    response_length_custom: col("integer",),
    context_max_tokens: col("integer",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    streaming: col("integer",),
    nsfw_override: col("text",),
    name_source: col("text",),
    template_id: col("text",),
    visibility: col("text", { notNull: true, hasDefault: true, },),
    thinking_visibility: col("text", { notNull: true, hasDefault: true, },),
    quick_replies: col("text",),
    prompt_override: col("text",),
    output_style_preset: col("text",),
    data_version: col("integer", { notNull: true, hasDefault: true, },),
    record_hash: col("text", { notNull: true, hasDefault: true, },),
    custom_instructions: col("text",),
  },)
  .table("messages", {
    id: col("text", { primaryKey: true, },),
    chat_id: col("text", { notNull: true, },),
    actor_id: col("text", { notNull: true, },),
    parent_id: col("text",),
    role: col("text", { notNull: true, },),
    content: col("text", { notNull: true, },),
    key_id: col("text",),
    content_format: col("text", { notNull: true, hasDefault: true, },),
    content_type: col("text", { notNull: true, hasDefault: true, },),
    content_encoding: col("text", { notNull: true, hasDefault: true, },),
    emotion: col("text",),
    model_id: col("text",),
    provider: col("text",),
    token_count_prompt: col("integer",),
    token_count_completion: col("integer",),
    token_count_total: col("integer",),
    token_cost: col("real",),
    generation_time_ms: col("integer",),
    tokens_per_second: col("real",),
    status: col("text", { notNull: true, hasDefault: true, },),
    visibility: col("text", { notNull: true, hasDefault: true, },),
    hidden_by: col("text",),
    hidden_reason: col("text",),
    idempotency_key: col("text",),
    continuation_index: col("integer",),
    swipe_index: col("integer",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    edited_at: col("text",),
    attachments: col("text",),
    archived_at: col("text",),
    format_version: col("integer", { notNull: true, hasDefault: true, },),
    section_id: col("text",),
    tool_calls: col("text",),
    thinking: col("text",),
    metadata: col("text",),
    e2e_payload: col("text",),
    e2e_session_id: col("text",),
    e2e_sender_eph_pub_jwk: col("text",),
    e2e_chain_index: col("integer",),
    content_plaintext: col("text",),
    data_version: col("integer", { notNull: true, hasDefault: true, },),
    record_hash: col("text", { notNull: true, hasDefault: true, },),
  },)
  // ── NSFW & Moderation ──────────────────────────────────────────────
  .table("content_flags", {
    id: col("text", { primaryKey: true, },),
    reporter_id: col("text", { notNull: true, },),
    content_type: col("text", { notNull: true, },),
    content_id: col("text", { notNull: true, },),
    chat_id: col("text",),
    world_id: col("text",),
    flag_reason: col("text", { notNull: true, },),
    description: col("text",),
    status: col("text", { notNull: true, hasDefault: true, },),
    resolution: col("text",),
    resolved_by: col("text",),
    resolved_at: col("text",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("moderation_actions", {
    id: col("text", { primaryKey: true, },),
    action_type: col("text", { notNull: true, },),
    target_user_id: col("text", { notNull: true, },),
    performed_by: col("text", { notNull: true, },),
    reason: col("text", { notNull: true, },),
    scope: col("text", { notNull: true, },),
    scope_id: col("text",),
    metadata: col("text", { notNull: true, hasDefault: true, },),
    expires_at: col("text",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    superseded_by: col("text",),
    deleted_at: col("text",),
    deleted_by: col("text",),
  },)
  .table("moderation_appeals", {
    id: col("text", { primaryKey: true, },),
    user_id: col("text", { notNull: true, },),
    action_id: col("text", { notNull: true, },),
    reason: col("text", { notNull: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    reviewed_by: col("text",),
    review_note: col("text",),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text",),
  },)
  .table("nsfw_consent_state", {
    id: col("text", { primaryKey: true, },),
    user_id: col("text", { notNull: true, },),
    chat_id: col("text", { notNull: true, },),
    action: col("text", { notNull: true, },),
    scope: col("text", { notNull: true, hasDefault: true, },),
    reason: col("text",),
    created_at: col("text", { notNull: true, },),
    revoked_at: col("text",),
  },)
  .table("nsfw_encounters", {
    id: col("text", { primaryKey: true, },),
    world_id: col("text",),
    encounter_type: col("text", { notNull: true, },),
    intensity: col("text", { notNull: true, hasDefault: true, },),
    narrative_style: col("text", { notNull: true, hasDefault: true, },),
    participants: col("text", { notNull: true, },),
    phases: col("text", { notNull: true, hasDefault: true, },),
    current_phase: col("integer", { notNull: true, hasDefault: true, },),
    outcomes: col("text", { notNull: true, hasDefault: true, },),
    content_tags: col("text", { notNull: true, hasDefault: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("nsfw_user_preferences", {
    id: col("text", { primaryKey: true, },),
    user_id: col("text", { notNull: true, },),
    nsfw_enabled: col("integer", { notNull: true, hasDefault: true, },),
    max_rating: col("text", { notNull: true, hasDefault: true, },),
    access_status: col("text", { notNull: true, hasDefault: true, },),
    shadow_nsfw: col("integer", { notNull: true, hasDefault: true, },),
    block_reason: col("text",),
    banned_at: col("text",),
    banned_by: col("text",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  // ── World & RPG ──────────────────────────────────────────────
  .table("items", {
    id: col("text", { primaryKey: true, },),
    world_id: col("text", { notNull: true, },),
    name: col("text", { notNull: true, },),
    description: col("text",),
    category: col("text", { notNull: true, },),
    rarity: col("text", { notNull: true, hasDefault: true, },),
    stackable: col("text", { notNull: true, hasDefault: true, },),
    max_stack: col("integer", { notNull: true, hasDefault: true, },),
    properties: col("text", { notNull: true, hasDefault: true, },),
    value: col("integer", { notNull: true, hasDefault: true, },),
    weight: col("real", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("location_nsfw_config", {
    id: col("text", { primaryKey: true, },),
    location_id: col("text", { notNull: true, },),
    location_type: col("text", { notNull: true, },),
    privacy_level: col("text", { notNull: true, hasDefault: true, },),
    discovery_chance: col("integer", { notNull: true, hasDefault: true, },),
    atmosphere: col("text", { notNull: true, hasDefault: true, },),
    equipment: col("text", { notNull: true, hasDefault: true, },),
    risks: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("location_states", {
    id: col("text", { primaryKey: true, },),
    location_id: col("text", { notNull: true, },),
    world_id: col("text", { notNull: true, },),
    description_override: col("text",),
    atmosphere: col("text",),
    npcs_present: col("text", { notNull: true, hasDefault: true, },),
    items_available: col("text", { notNull: true, hasDefault: true, },),
    time_of_day: col("text",),
    weather: col("text",),
    hazards: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("locations", {
    id: col("text", { primaryKey: true, },),
    world_id: col("text", { notNull: true, },),
    name: col("text", { notNull: true, },),
    description: col("text",),
    connections: col("text", { notNull: true, hasDefault: true, },),
    publication_status: col("text", { notNull: true, hasDefault: true, },),
    parent_location_id: col("text",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("quest_progress", {
    id: col("text", { primaryKey: true, },),
    quest_id: col("text", { notNull: true, },),
    chat_id: col("text", { notNull: true, },),
    progress: col("integer", { notNull: true, hasDefault: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    contributed_events: col("text", { notNull: true, hasDefault: true, },),
    started_at: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    completed_at: col("text",),
  },)
  .table("quests", {
    id: col("text", { primaryKey: true, },),
    world_id: col("text", { notNull: true, },),
    creator_id: col("text", { notNull: true, },),
    name: col("text", { notNull: true, },),
    description: col("text",),
    type: col("text", { notNull: true, },),
    category: col("text", { notNull: true, hasDefault: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    priority: col("integer", { notNull: true, hasDefault: true, },),
    config: col("text", { notNull: true, hasDefault: true, },),
    progress: col("integer", { notNull: true, hasDefault: true, },),
    target: col("integer", { notNull: true, },),
    start_time: col("text",),
    deadline: col("text",),
    time_location_id: col("text",),
    rewards: col("text", { notNull: true, hasDefault: true, },),
    narrative_hooks: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    completed_at: col("text",),
  },)
  .table("world_avatar_config", {
    id: col("text", { primaryKey: true, },),
    world_id: col("text", { notNull: true, },),
    actor_id: col("text", { notNull: true, },),
    selection_rule_override: col("text", { hasDefault: true, },),
    weights_override: col("text", { hasDefault: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("world_invites", {
    id: col("text", { primaryKey: true, },),
    world_id: col("text", { notNull: true, },),
    code: col("text", { notNull: true, },),
    created_by: col("text",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    expires_at: col("text",),
    max_uses: col("integer",),
    uses: col("integer", { notNull: true, hasDefault: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("world_items", {
    id: col("text", { primaryKey: true, },),
    world_id: col("text", { notNull: true, },),
    item_id: col("text", { notNull: true, },),
    location_id: col("text",),
    owner_actor_id: col("text",),
    quantity: col("integer", { notNull: true, hasDefault: true, },),
    visibility: col("text", { notNull: true, hasDefault: true, },),
    spawn_condition: col("text",),
    respawnable: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("world_lore_entries", {
    id: col("text", { primaryKey: true, },),
    world_id: col("text", { notNull: true, },),
    name: col("text",),
    content: col("text", { notNull: true, },),
    keys: col("text", { notNull: true, hasDefault: true, },),
    secondary_keys: col("text", { hasDefault: true, },),
    selective: col("integer", { notNull: true, hasDefault: true, },),
    case_sensitive: col("integer", { notNull: true, hasDefault: true, },),
    enabled: col("text", { notNull: true, hasDefault: true, },),
    constant: col("integer", { notNull: true, hasDefault: true, },),
    position: col("text", { notNull: true, hasDefault: true, },),
    insertion_order: col("integer", { notNull: true, hasDefault: true, },),
    priority: col("integer", { notNull: true, hasDefault: true, },),
    comment: col("text",),
    sort_order: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    cooldown_seconds: col("integer", { notNull: true, hasDefault: true, },),
    last_activated: col("text",),
    audience_scope: col("text",),
    key_type: col("text",),
    key_groups: col("text",),
    scan_depth: col("integer",),
    activation_chance: col("real",),
  },)
  .table("world_members", {
    world_id: col("text", { notNull: true, },),
    actor_id: col("text", { notNull: true, },),
  },)
  .table("world_states", {
    id: col("text", { primaryKey: true, },),
    world_id: col("text", { notNull: true, },),
    snapshot: col("text", { notNull: true, },),
    trigger_message_id: col("text",),
    trigger_turn_id: col("text",),
    description: col("text",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("world_timeline_events", {
    id: col("text", { primaryKey: true, },),
    world_id: col("text", { notNull: true, },),
    story_id: col("text",),
    event_type: col("text", { notNull: true, },),
    actor_id: col("text",),
    description: col("text", { notNull: true, },),
    data: col("text",),
    occurred_at: col("text", { notNull: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    timeline_id: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("world_timelines", {
    id: col("text", { primaryKey: true, },),
    world_id: col("text", { notNull: true, },),
    name: col("text", { notNull: true, },),
    description: col("text",),
    is_prime: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("worlds", {
    id: col("text", { primaryKey: true, },),
    owner_id: col("text", { notNull: true, },),
    name: col("text", { notNull: true, },),
    description: col("text",),
    lore: col("text",),
    publication_status: col("text", { notNull: true, hasDefault: true, },),
    kind: col("text", { notNull: true, hasDefault: true, },),
    visibility: col("text", { notNull: true, hasDefault: true, },),
    scan_depth: col("integer", { notNull: true, hasDefault: true, },),
    token_budget: col("integer", { notNull: true, hasDefault: true, },),
    difficulty_modifier: col("real", { notNull: true, hasDefault: true, },),
    difficulty_reroll: col("text", { notNull: true, hasDefault: true, },),
    difficulty_state: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    nsfw_override: col("text",),
    rpg_enabled: col("integer", { notNull: true, hasDefault: true, },),
    data_version: col("integer", { notNull: true, hasDefault: true, },),
    record_hash: col("text", { notNull: true, hasDefault: true, },),
  },)
  // ── Generation & Prompts ──────────────────────────────────────────────
  .table("model_capabilities", {
    id: col("text", { primaryKey: true, notNull: true, },),
    provider_id: col("text", { notNull: true, },),
    model_id: col("text", { notNull: true, },),
    context_window: col("integer",),
    max_output: col("integer",),
    supports_tools: col("integer", { hasDefault: true, },),
    supports_vision: col("integer", { hasDefault: true, },),
    supports_thinking: col("integer", { hasDefault: true, },),
    modalities: col("text",),
    param_size: col("text",),
    owned_by: col("text",),
    user_override: col("integer", { notNull: true, hasDefault: true, },),
    notes: col("text",),
    last_seen: col("text", { notNull: true, },),
    created_at: col("text", { notNull: true, },),
    updated_at: col("text", { notNull: true, },),
  },)
  .table("model_comparisons", {
    id: col("text", { primaryKey: true, },),
    message_id: col("text", { notNull: true, },),
    user_id: col("text", { notNull: true, },),
    reference_model: col("text", { notNull: true, },),
    preference: col("text", { notNull: true, },),
    confidence: col("real", { notNull: true, },),
    created_at: col("text", { notNull: true, },),
  },)
  .table("model_role_overrides", {
    role: col("text", { primaryKey: true, },),
    provider: col("text", { notNull: true, },),
    model: col("text", { notNull: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    temperature: col("real",),
    max_tokens: col("integer",),
  },)
  // ── Core: Users & Sessions ──────────────────────────────────────────────
  .table("personas", {
    id: col("text", { primaryKey: true, },),
    user_id: col("text", { notNull: true, },),
    name: col("text", { notNull: true, },),
    avatar_asset_id: col("text",),
    description: col("text",),
    title: col("text",),
    is_default: col("text", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
    format_version: col("integer", { notNull: true, hasDefault: true, },),
    temperature: col("real",),
    max_tokens: col("integer",),
    model: col("text",),
  },)
  .table("sessions", {
    id: col("text", { primaryKey: true, },),
    user_id: col("text", { notNull: true, },),
    token_hash: col("text", { notNull: true, },),
    ip: col("text",),
    user_agent: col("text",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    last_activity: col("text", { notNull: true, hasDefault: true, },),
    expires_at: col("text", { notNull: true, },),
  },)
  .table("user_api_keys", {
    id: col("text", { primaryKey: true, },),
    user_id: col("text", { notNull: true, },),
    provider_name: col("text", { notNull: true, },),
    api_key_encrypted: col("text", { notNull: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  .table("users", {
    id: col("text", { primaryKey: true, },),
    username: col("text", { notNull: true, },),
    display_name: col("text", { notNull: true, },),
    password_hash: col("text",),
    role: col("text", { notNull: true, hasDefault: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    settings: col("text", { notNull: true, hasDefault: true, },),
    birth_date: col("text",),
    age_gate_accepted_at: col("text",),
    format_version: col("integer", { notNull: true, hasDefault: true, },),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    last_seen_at: col("text",),
  },)
  // ── Plugin System ──────────────────────────────────────────────
  .table("plugin_state", {
    name: col("text", { primaryKey: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    enabled_at: col("text",),
    disabled_at: col("text",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },)
  // ── Turn & Story ──────────────────────────────────────────────
  .table("story_turns", {
    id: col("text", { primaryKey: true, },),
    chat_id: col("text", { notNull: true, },),
    turn_number: col("integer", { notNull: true, },),
    actor_id: col("text", { notNull: true, },),
    turn_type: col("text", { notNull: true, },),
    prompt_sent: col("text", { notNull: true, },),
    response_received: col("text",),
    quality_score: col("real",),
    quality_details: col("text",),
    regeneration_count: col("integer", { notNull: true, hasDefault: true, },),
    status: col("text", { notNull: true, hasDefault: true, },),
    gm_decision: col("text",),
    world_events: col("text", { notNull: true, hasDefault: true, },),
    quest_progress: col("text", { notNull: true, hasDefault: true, },),
    started_at: col("text", { notNull: true, hasDefault: true, },),
    completed_at: col("text",),
    created_at: col("text", { notNull: true, hasDefault: true, },),
    updated_at: col("text", { notNull: true, hasDefault: true, },),
  },);
