/**
 * DB Schema — Gm Domain Tables
 *
 * Auto-generated by scripts/generate-db-types.ts
 * DO NOT EDIT MANUALLY — run `bun run db:sync-types` to regenerate.
 */
import type { Generated, } from "kysely";
import type { ShadowNoteType, WhiteneoteScope, WhiteneoteType, } from "./schemas";

// ── shadow_notes ────────────────────────────────────────────
export interface ShadowNotes {
  id: Generated<string>;
  chat_id: string;
  type: ShadowNoteType;
  content: string;
  revealed: Generated<number>;
  created_at: string;
}

// ── whitenotes ────────────────────────────────────────────
export interface Whitenotes {
  id: Generated<string>;
  chat_id: string;
  type: WhiteneoteType;
  content: string;
  priority: Generated<number>;
  scope: Generated<WhiteneoteScope>;
  expires_at: string | null;
  created_at: string;
}
