// SPDX-License-Identifier: LGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Loop Lore Contributors

/**
 * Persist a validated entity generated by the `/create` command.
 *
 * Extraction point for {@link insertGeneratedEntity} so both the (deprecated)
 * inline path and the confirmation endpoint (`POST /api/chats/:id/create-entity`)
 * share one insertion routine. Insertion only runs after the quality gates in
 * `src/assistant/quality/entity-creation.ts` have passed and the user has
 * confirmed.
 */

import type { Kysely, } from "kysely";
import { createChat, getChatSetupTemplate, } from "../../chat/service";
import { DifficultyReroll, DifficultyState, LoreEntryStatus, LorePosition, } from "../../db/enums-story";
import type { DB, } from "../../db/schema";
import { normalizeAudienceScope, } from "../../story/events/promote-lore";
import { safeJsonParse, safeJsonStringify, uid, } from "../../utils";
import type { LoreScope, } from "../lore/audience";
import type { EntityKind, } from "../prompt/templates/entity-generation";
import type {
  GeneratedEntity,
  GeneratedEntityLoreEntry,
} from "../quality/entity-creation";

/** A confirmed entity draft ready for persistence. */
export interface EntityDraft {
  kind: EntityKind;
  data: GeneratedEntity;
  /** Original user description (fallback when LLM omits one). */
  description: string;
  /** World scope resolved at generation time. */
  worldId?: string;
}

/** Result of persisting an entity. */
export interface InsertedEntity {
  id: string;
  kind: EntityKind;
  name: string;
  /** For locations, the auto-created public chat id (if template present). */
  linkedChatId?: string;
}

/**
 * Insert a validated, user-confirmed entity into the correct table.
 *
 * Entity insert + all lore inserts are wrapped in a single transaction so a
 * failure leaves no orphaned rows (BUG-create-entity-no-transaction-on-lore-failure).
 *
 * @param db     - Database handle (or open transaction)
 * @param draft  - The confirmed draft (must have passed quality gates)
 * @param userId - Actor id of the creating user
 * @returns The persisted entity id and name
 * @throws when the insert fails (transaction rolls back)
 */
export async function insertGeneratedEntity(
  db: Kysely<DB>,
  draft: EntityDraft,
  userId: string,
): Promise<InsertedEntity> {
  return await db.transaction().execute(async (trx,) => {
    const id = uid();
    const { kind, data, description, worldId, } = draft;
    const name = data.name || "Unnamed";

    switch (kind) {
      case "character": {
        await trx
          .insertInto("actors",)
          .values({
            id,
            actor_type: "character",
            display_name: name,
            user_id: userId,
            owner_id: userId,
            agent_type: "ai",
            description: data.description ?? description,
            system_prompt: null,
            settings: "{}",
            personality: data.personality ?? null,
            scenario: data.scenario ?? null,
            import_spec: "llm-generated",
          },)
          .execute();
        await insertEntityLore(trx, kind, id, worldId, data.lore,);
        return { id, kind, name, };
      }

      case "location": {
        const resolvedWorld = worldId ?? "default";
        await trx
          .insertInto("locations",)
          .values({
            id,
            world_id: resolvedWorld,
            name,
            description: data.description ?? description,
            connections: "[]",
          },)
          .execute();

        // Mirror the REST location creation: auto-create a public chat bound to
        // the default `world` template so the location is immediately reachable.
        let linkedChatId: string | undefined;
        const template = await getChatSetupTemplate(trx, "template-world",);
        if (template) {
          const gmParsed = template.gm_config
            ? safeJsonParse<Record<string, unknown>>(template.gm_config,)
            : null;
          const chat = await createChat(trx, {
            name,
            type: "group",
            mode: template.mode ?? "story",
            createdBy: userId,
            worldId: resolvedWorld,
            currentLocationId: id,
            turnStrategy: template.turn_strategy,
            gmConfig: gmParsed?.ok ? gmParsed.value : null,
            renderingOverride: gmParsed?.ok && (gmParsed.value.renderingOverride === "visual_novel" ||
                gmParsed.value.renderingOverride === "text")
              ? gmParsed.value.renderingOverride
              : null,
            visibility: template.visibility ?? "private",
            templateId: template.id,
          },);
          linkedChatId = chat;
        }
        await insertEntityLore(trx, kind, id, resolvedWorld, data.lore,);
        return { id, kind, name, linkedChatId, };
      }

      case "world": {
        await trx
          .insertInto("worlds",)
          .values({
            id,
            owner_id: userId,
            name,
            description: data.description ?? description,
            lore: typeof data.lore === "string" ? data.lore : null,
            difficulty_modifier: 1,
            difficulty_reroll: DifficultyReroll.None,
            difficulty_state: DifficultyState.Normal,
          },)
          .execute();
        await insertEntityLore(trx, kind, id, id, data.lore,);
        return { id, kind, name, };
      }

      case "item": {
        const resolvedWorld = worldId ?? "default";
        await trx
          .insertInto("items",)
          .values({
            id,
            world_id: resolvedWorld,
            name,
            description: data.description ?? description,
            category: "other",
            rarity: "common",
            stackable: "unique",
            max_stack: 1,
            properties: "{}",
            value: 0,
            weight: 1,
          },)
          .execute();
        await insertEntityLore(trx, kind, id, resolvedWorld, data.lore,);
        return { id, kind, name, };
      }
    }
  },);
}

/**
 * Map an EntityKind to its target lore table.
 */
interface LoreTarget {
  table: "world_lore_entries" | "actor_lore_entries";
  fkColumn: "world_id" | "actor_id";
}

/** Resolve the lore target table and FK column for a given entity kind. */
function resolveLoreTarget(kind: EntityKind,): LoreTarget | null {
  switch (kind) {
    case "world":
    case "location":
    case "item":
      return { table: "world_lore_entries", fkColumn: "world_id", };
    case "character":
      return { table: "actor_lore_entries", fkColumn: "actor_id", };
  }
}

/**
 * Insert structured lore entries for a generated entity into the appropriate
 * lore table(s). Each entry becomes a separate row.
 *
 * - world → world_lore_entries (world_id = the world's id)
 * - location → world_lore_entries (world_id = the parent world)
 * - item → world_lore_entries (world_id = the parent world)
 * - character → actor_lore_entries (actor_id = the character's id)
 *
 * Location and item lore entries get `requires_presence = true` by default.
 * Entries with `selective = true` but empty keys are stored with `selective = 0`
 * since keyword matching cannot fire without triggers.
 * @param db       - Database handle (or open transaction)
 * @param kind     - Entity kind (determines target table)
 * @param entityId - The newly-inserted entity's id
 * @param worldId  - Resolved world id (required for world/loc/item; null for character)
 * @param lore     - Structured lore entries from the normalized entity
 * @throws when worldId is missing for a kind that requires it
 */
export async function insertEntityLore(
  db: Kysely<DB>,
  kind: EntityKind,
  entityId: string,
  worldId: string | undefined,
  lore: string | GeneratedEntityLoreEntry[] | undefined,
): Promise<void> {
  if (!Array.isArray(lore,)) { return; }
  if (lore.length === 0) { return; }

  const target = resolveLoreTarget(kind,);
  if (!target) { return; }

  // world/location/item lore is stored in world_lore_entries which has a
  // NOT NULL FK on world_id — the world must be known.
  if (target.table === "world_lore_entries" && !worldId) {
    throw new Error(`worldId is required for ${kind} lore persistence,`,);
  }

  const now = new Date().toISOString();

  for (const entry of lore) {
    // Build audience_scope JSON from subject + requires_presence.
    // For location/item lore without a subject, attach a synthetic
    // { kind: "location", locationId: entityId } so parseLoreScope can
    // read it back (it requires a subject key) and requires_presence
    // is meaningful in isLoreVisibleTo.
    const scope: LoreScope = {};
    if (entry.subject) {
      scope.subject = entry.subject;
    } else if (kind === "location" || kind === "item") {
      scope.subject = { kind: "location" as const, locationId: entityId, };
    }

    if (kind === "location" || kind === "item") {
      scope.requires_presence = entry.requires_presence ?? true;
    } else if (entry.requires_presence !== undefined) {
      scope.requires_presence = entry.requires_presence;
    }

    // Validate subject via normalizeAudienceScope (checks kind + selectors).
    // If subject is present but invalid, skip this entry.
    const validated = normalizeAudienceScope(scope,);
    if (entry.subject && !validated) { continue; }

    // Serialize the scope directly — preserves requires_presence + subject.
    // Store null when scope is empty (no audience restriction).
    const scopeStrResult = safeJsonStringify(scope,);
    let audienceScopeStr: string | null = null;
    if (scopeStrResult.ok && (scope.subject || scope.requires_presence !== undefined)) {
      audienceScopeStr = scopeStrResult.value;
    }

    const keysStrResult = safeJsonStringify(entry.keys ?? [],);
    const keysStr = keysStrResult.ok ? keysStrResult.value : "[]";

    // N6: force selective=0 when keys are empty — selective gating requires
    // keyword triggers to ever match.
    const hasKeys = entry.keys && entry.keys.length > 0;
    const selectiveFlag = entry.selective && hasKeys ? 1 : 0;

    const loreValues = {
      name: entry.name,
      content: entry.content,
      keys: keysStr,
      constant: entry.constant ? 1 : 0,
      selective: selectiveFlag,
      position: entry.position ?? LorePosition.BeforeChar,
      insertion_order: entry.insertion_order ?? 0,
      priority: entry.priority ?? 0,
      cooldown_seconds: entry.cooldown_seconds ?? 0,
      enabled: LoreEntryStatus.Enabled,
      sort_order: 0,
      audience_scope: audienceScopeStr,
      created_at: now,
      updated_at: now,
      secondary_keys: null,
      case_sensitive: 0,
      comment: null,
      last_activated: null,
      key_type: null,
      key_groups: null,
      scan_depth: null,
      activation_chance: null,
    };

    if (target.table === "world_lore_entries") {
      await db
        .insertInto("world_lore_entries",)
        .values({
          ...loreValues,
          world_id: worldId!,
        },)
        .execute();
    } else {
      // actor_lore_entries
      await db
        .insertInto("actor_lore_entries",)
        .values({
          ...loreValues,
          actor_id: entityId,
          world_id: worldId && worldId !== "default" ? worldId : null,
        },)
        .execute();
    }
  }
}
