// SPDX-License-Identifier: LGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Loop Lore Contributors

/**
 * Persist a validated entity generated by the `/create` command.
 *
 * Extraction point for {@link insertGeneratedEntity} so both the (deprecated)
 * inline path and the confirmation endpoint (`POST /api/chats/:id/create-entity`)
 * share one insertion routine. Insertion only runs after the quality gates in
 * `src/assistant/quality/entity-creation.ts` have passed and the user has
 * confirmed.
 */

import type { Kysely, } from "kysely";
import { createChat, getChatSetupTemplate, } from "../../chat/service";
import { DifficultyReroll, DifficultyState, } from "../../db/enums-story";
import type { DB, } from "../../db/schema";
import { safeJsonParse, uid, } from "../../utils";
import type { EntityKind, } from "../prompt/templates/entity-generation";
import type { GeneratedEntity, } from "../quality/entity-creation";

/** A confirmed entity draft ready for persistence. */
export interface EntityDraft {
  kind: EntityKind;
  data: GeneratedEntity;
  /** Original user description (fallback when LLM omits one). */
  description: string;
  /** World scope resolved at generation time. */
  worldId?: string;
}

/** Result of persisting an entity. */
export interface InsertedEntity {
  id: string;
  kind: EntityKind;
  name: string;
  /** For locations, the auto-created public chat id (if template present). */
  linkedChatId?: string;
}

/**
 * Insert a validated, user-confirmed entity into the correct table.
 *
 * @param db - Database handle
 * @param draft - The confirmed draft (must have passed quality gates)
 * @returns The persisted entity id and name
 * @throws when the insert fails
 */
export async function insertGeneratedEntity(
  db: Kysely<DB>,
  draft: EntityDraft,
  userId: string,
): Promise<InsertedEntity> {
  const id = uid();
  const { kind, data, description, worldId, } = draft;
  const name = data.name || "Unnamed";

  switch (kind) {
    case "character": {
      await db
        .insertInto("actors",)
        .values({
          id,
          actor_type: "character",
          display_name: name,
          user_id: userId,
          owner_id: userId,
          agent_type: "ai",
          description: data.description ?? description,
          system_prompt: null,
          settings: "{}",
          personality: data.personality ?? null,
          scenario: data.scenario ?? null,
          import_spec: "llm-generated",
        },)
        .execute();
      return { id, kind, name, };
    }

    case "location": {
      const resolvedWorld = worldId ?? "default";
      await db
        .insertInto("locations",)
        .values({
          id,
          world_id: resolvedWorld,
          name,
          description: data.description ?? description,
          connections: "[]",
        },)
        .execute();

      // Mirror the REST location creation: auto-create a public chat bound to
      // the default `world` template so the location is immediately reachable.
      let linkedChatId: string | undefined;
      const template = await getChatSetupTemplate(db, "template-world",);
      if (template) {
        const gmParsed = template.gm_config
          ? safeJsonParse<Record<string, unknown>>(template.gm_config,)
          : null;
        const chat = await createChat(db, {
          name,
          type: "group",
          mode: template.mode ?? "story",
          createdBy: userId,
          worldId: resolvedWorld,
          currentLocationId: id,
          turnStrategy: template.turn_strategy,
          gmConfig: gmParsed?.ok ? gmParsed.value : null,
          visualNovel: template.visual_novel === 1,
          visibility: template.visibility ?? "private",
          templateId: template.id,
        },);
        linkedChatId = chat;
      }
      return { id, kind, name, linkedChatId, };
    }

    case "world": {
      await db
        .insertInto("worlds",)
        .values({
          id,
          owner_id: userId,
          name,
          description: data.description ?? description,
          lore: data.lore ?? null,
          difficulty_modifier: 1,
          difficulty_reroll: DifficultyReroll.None,
          difficulty_state: DifficultyState.Normal,
        },)
        .execute();
      return { id, kind, name, };
    }

    case "item": {
      const resolvedWorld = worldId ?? "default";
      await db
        .insertInto("items",)
        .values({
          id,
          world_id: resolvedWorld,
          name,
          description: data.description ?? description,
          category: "other",
          rarity: "common",
          stackable: "unique",
          max_stack: 1,
          properties: "{}",
          value: 0,
          weight: 1,
        },)
        .execute();
      return { id, kind, name, };
    }
  }
}
