// SPDX-License-Identifier: LGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Loop Lore Contributors

/**
 * Tests for POST /api/chats/:id/create-entity — the confirm endpoint for
 * entity drafts generated by the `/create` command.
 */
import { afterAll, beforeAll, describe, expect, test, } from "bun:test";
import { Elysia, } from "elysia";
import type { Kysely, } from "kysely";
import { insertGeneratedEntity, } from "../../assistant/commands/create-entity";
import { ChatParticipantRole, } from "../../db/enums";
import type { DB, } from "../../db/schema";
import { createLogger, } from "../../logger";
import { createTestDb, } from "../../test-utils/create-test-db";
import { insertChatParticipants, insertChats, } from "../../test-utils/insert-helpers";
import { uid, } from "../../utils";
import { createEntityConfirmRoutes, } from "./create-entity-confirm";

/**
 * @param db
 * @param userId
 */
function createApp(db: Kysely<DB>, userId: string | null,): Elysia {
  return new Elysia({ name: "test-create-entity-confirm", },)
    .derive(() => ({ userId, }))
    .use(createEntityConfirmRoutes({ database: db, config: {} as never, },),) as unknown as Elysia;
}

describe("POST /api/chats/:id/create-entity", () => {
  let db: Kysely<DB>;
  const userId = uid();
  const otherUserId = uid();
  let worldId: string;

  beforeAll(async () => {
    createLogger({ level: "error", },);
    ({ db, } = await createTestDb());

    // Create test user
    await db
      .insertInto("users",)
      .values({
        id: userId,
        username: `user-${userId}`,
        display_name: "Test User",
        role: "solo",
        status: "active",
        settings: "{}",
      },)
      .execute();
    await db
      .insertInto("actors",)
      .values({
        id: userId,
        actor_type: "user",
        display_name: "Test User",
        user_id: userId,
        owner_id: userId,
        agent_type: "none",
        settings: "{}",
        format_version: 0,
        visibility: "private",
        import_spec: "{}",
      },)
      .execute();

    // Create second user for access-denied tests
    await db
      .insertInto("users",)
      .values({
        id: otherUserId,
        username: `user-${otherUserId}`,
        display_name: "Other User",
        role: "solo",
        status: "active",
        settings: "{}",
      },)
      .execute();
    await db
      .insertInto("actors",)
      .values({
        id: otherUserId,
        actor_type: "user",
        display_name: "Other User",
        user_id: otherUserId,
        owner_id: otherUserId,
        agent_type: "none",
        settings: "{}",
        format_version: 0,
        visibility: "private",
        import_spec: "{}",
      },)
      .execute();

    // Create a world for item/location FK (insertGeneratedEntity uses
    // worldId ?? "default" and items/locations reference worlds.id)
    worldId = uid();
    await db
      .insertInto("worlds",)
      .values({
        id: worldId,
        owner_id: userId,
        name: "Test World",
        description: "A test world",
        difficulty_modifier: 1,
      },)
      .execute();
  },);

  afterAll(async () => {
    await db.destroy();
  },);

  /** Helper: create a chat with the user as participant. */
  async function createChatWithUser(): Promise<string> {
    const chatId = uid();
    await insertChats(db, "Test Chat", userId, { id: chatId, } as never,);
    await insertChatParticipants(db, chatId, userId, { role_in_chat: ChatParticipantRole.Owner, } as never,);
    return chatId;
  }

  // ── Auth ─────────────────────────────────────────────────────

  test("rejects request without userId", async () => {
    const app = createApp(db, null,);
    const res = await app.handle(
      new Request("http://localhost/api/chats/c1/create-entity", {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "character",
          data: { name: "Test", description: "A test character", },
        },),
      },),
    );
    // Elysia body validation may fire before handler, producing 422
    expect(res.ok,).toBe(false,);
  });

  // ── Validation ───────────────────────────────────────────────

  test("returns 400 for invalid entity kind", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "invalid",
          data: { name: "Test", description: "Test desc", },
        },),
      },),
    );
    expect(res.status,).toBe(400,);
    const body = await res.json();
    expect(body.error,).toContain("kind",);
  });

  test("rejects request when data.name is empty or missing", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "character",
          data: { description: "No name", },
        },),
      },),
    );
    // Elysia body schema requires name: t.String(), rejects at validation
    expect(res.ok,).toBe(false,);
  });

  test("returns 422 when character is missing description", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "character",
          data: { name: "NoDesc", },
        },),
      },),
    );
    expect(res.status,).toBe(422,);
    const body = await res.json();
    expect(body.error,).toContain("Invalid entity",);
  });

  // ── Happy path: character ────────────────────────────────────

  test("creates a character entity and returns 201", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "character",
          data: {
            name: "Aragorn",
            description: "Ranger of the North",
            personality: "Noble and steadfast",
            scenario: "Middle-earth",
          },
        },),
      },),
    );
    expect(res.status,).toBe(201,);
    const body = await res.json();
    expect(body.kind,).toBe("character",);
    expect(body.name,).toBe("Aragorn",);
    expect(body.id,).toBeString();
    expect(body.linkedChatId,).toBeNull();

    // Verify persisted in DB
    const actor = await db
      .selectFrom("actors",)
      .where("id", "=", body.id,)
      .selectAll()
      .executeTakeFirst();
    expect(actor,).toBeDefined();
    expect(actor!.display_name,).toBe("Aragorn",);
    expect(actor!.personality,).toBe("Noble and steadfast",);
  });

  // ── Happy path: world ────────────────────────────────────────

  test("creates a world entity and returns 201", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "world",
          data: {
            name: "Middle-earth",
            description: "A world of hobbits and wizards",
            lore: "Created by Ilúvatar",
          },
        },),
      },),
    );
    expect(res.status,).toBe(201,);
    const body = await res.json();
    expect(body.kind,).toBe("world",);
    expect(body.name,).toBe("Middle-earth",);

    // Verify persisted
    const world = await db
      .selectFrom("worlds",)
      .where("id", "=", body.id,)
      .selectAll()
      .executeTakeFirst();
    expect(world,).toBeDefined();
    expect(world!.name,).toBe("Middle-earth",);
    expect(world!.lore,).toBe("Created by Ilúvatar",);
  });

  // ── Happy path: item ─────────────────────────────────────────

  test("creates an item entity and returns 201", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "item",
          data: {
            name: "Sting",
            description: "A glowing Elven blade",
          },
          worldId,
        },),
      },),
    );
    expect(res.status,).toBe(201,);
    const body = await res.json();
    expect(body.kind,).toBe("item",);
    expect(body.name,).toBe("Sting",);

    // Verify persisted
    const item = await db
      .selectFrom("items",)
      .where("id", "=", body.id,)
      .selectAll()
      .executeTakeFirst();
    expect(item,).toBeDefined();
    expect(item!.name,).toBe("Sting",);
  });

  // ── Happy path: location ─────────────────────────────────────

  test("creates a location entity and returns 201", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "location",
          data: {
            name: "Rivendell",
            description: "The Last Homely House",
          },
          worldId,
        },),
      },),
    );
    expect(res.status,).toBe(201,);
    const body = await res.json();
    expect(body.kind,).toBe("location",);
    expect(body.name,).toBe("Rivendell",);

    // Verify persisted
    const location = await db
      .selectFrom("locations",)
      .where("id", "=", body.id,)
      .selectAll()
      .executeTakeFirst();
    expect(location,).toBeDefined();
    expect(location!.name,).toBe("Rivendell",);
  });

  // ── Chat access ──────────────────────────────────────────────

  test("returns error when user has no access to chat", async () => {
    // Create a chat owned by otherUserId — userId has no access
    const chatId = uid();
    await insertChats(db, "Private Chat", otherUserId, { id: chatId, } as never,);
    await insertChatParticipants(db, chatId, otherUserId, { role_in_chat: ChatParticipantRole.Owner, } as never,);

    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "character",
          data: { name: "Intruder", description: "Should fail", },
        },),
      },),
    );
    expect(res.ok,).toBe(false,);
  });

  // ── World ownership guard ────────────────────────────────────

  test("forbids targeting a world owned by another user", async () => {
    // Create a chat owned by userId and add otherUserId as a participant
    // with READ access — but otherUserId does NOT own worldId. This
    // isolates the world-ownership guard from the chat-access gate.
    const chatId = uid();
    await insertChats(db, "Shared Chat", userId, { id: chatId, } as never,);
    await insertChatParticipants(db, chatId, userId, { role_in_chat: ChatParticipantRole.Owner, } as never,);
    await insertChatParticipants(db, chatId, otherUserId, { role_in_chat: ChatParticipantRole.Member, } as never,);

    const app = createApp(db, otherUserId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "item",
          data: { name: "Stolen Sword", description: "Should fail", },
          worldId,
        },),
      },),
    );
    expect(res.status,).toBe(403,);
  });

  // ── Lore persistence ─────────────────────────────────────────

  test("creates character with structured lore entries in actor_lore_entries", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "character",
          data: {
            name: "LoreKEEPER",
            description: "A keeper of ancient knowledge",
            lore: [
              {
                name: "Ancient Secret",
                content: "The keeper knows the location of the lost city.",
                keys: ["lost", "city",],
                subject: { kind: "race", race: "elf", },
                constant: false,
                selective: true,
                position: "before_char",
                insertion_order: 0,
                priority: 1,
                cooldown_seconds: 0,
              },
              {
                name: "Silent Oath",
                content: "Bound by a oath never to speak the old tongue.",
                keys: ["oath", "tongue",],
                constant: true,
                selective: false,
                position: "after_char",
              },
            ],
          },
        },),
      },),
    );
    expect(res.status,).toBe(201,);
    const body = await res.json();
    expect(body.kind,).toBe("character",);

    // Verify lore entries persisted in actor_lore_entries
    const loreEntries = await db
      .selectFrom("actor_lore_entries",)
      .selectAll()
      .where("actor_id", "=", body.id,)
      .execute();
    expect(loreEntries,).toHaveLength(2,);
    expect(loreEntries[0]!.name,).toBe("Ancient Secret",);
    expect(loreEntries[0]!.content,).toBe("The keeper knows the location of the lost city.",);
    expect(loreEntries[0]!.keys,).toBe(JSON.stringify(["lost", "city",],),);
    expect(loreEntries[0]!.constant,).toBe(0,);
    expect(loreEntries[0]!.selective,).toBe(1,);
    expect(loreEntries[0]!.position,).toBe("before_char",);
    expect(loreEntries[0]!.priority,).toBe(1,);
    expect(loreEntries[0]!.enabled,).toBe("enabled",);
    expect(loreEntries[0]!.insertion_order,).toBe(0,);
    expect(loreEntries[0]!.cooldown_seconds,).toBe(0,);
    expect(loreEntries[0]!.audience_scope,).not.toBeNull();

    const scope = JSON.parse(loreEntries[0]!.audience_scope!,);
    expect(scope.subject.kind,).toBe("race",);
    expect(scope.subject.race,).toBe("elf",);
    expect(scope.requires_presence,).toBeUndefined();

    // Second entry is constant
    expect(loreEntries[1]!.name,).toBe("Silent Oath",);
    expect(loreEntries[1]!.constant,).toBe(1,);
    expect(loreEntries[1]!.selective,).toBe(0,);
    expect(loreEntries[1]!.position,).toBe("after_char",);
    expect(loreEntries[1]!.audience_scope,).toBeNull();
  });

  test("creates world with lore entries in world_lore_entries", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "world",
          data: {
            name: "Golarion",
            description: "A fantasy world",
            lore: [
              {
                name: "The Starfall",
                content: "A meteor crashed here centuries ago.",
                keys: ["meteor", "star",],
                subject: { kind: "world", },
                constant: true,
                selective: false,
                position: "before_char",
              },
            ],
          },
        },),
      },),
    );
    expect(res.status,).toBe(201,);
    const body = await res.json();

    // Verify lore persisted in world_lore_entries
    const loreEntries = await db
      .selectFrom("world_lore_entries",)
      .selectAll()
      .where("world_id", "=", body.id,)
      .execute();
    expect(loreEntries,).toHaveLength(1,);
    expect(loreEntries[0]!.name,).toBe("The Starfall",);
    expect(loreEntries[0]!.content,).toBe("A meteor crashed here centuries ago.",);
    expect(loreEntries[0]!.constant,).toBe(1,);
    expect(loreEntries[0]!.selective,).toBe(0,);
    expect(loreEntries[0]!.position,).toBe("before_char",);
  });

  test("creates location with lore entries in world_lore_entries", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "location",
          data: {
            name: "Sunken Bridge",
            description: "An ancient bridge",
            lore: [
              {
                name: "Bridge Legend",
                content: "Built by drowned spirits.",
                keys: ["drowned",],
                selective: true,
                position: "before_char",
              },
            ],
          },
          worldId,
        },),
      },),
    );
    expect(res.status,).toBe(201,);

    // Verify lore persisted in world_lore_entries with world_id = worldId
    const loreEntries = await db
      .selectFrom("world_lore_entries",)
      .selectAll()
      .where("world_id", "=", worldId,)
      .execute();
    expect(loreEntries,).toHaveLength(1,);
    expect(loreEntries[0]!.name,).toBe("Bridge Legend",);
    // Location lore gets requires_presence = true by default
    const scope = JSON.parse(loreEntries[0]!.audience_scope!,);
    expect(scope.requires_presence,).toBe(true,);
  });

  test("creates item with lore entries in world_lore_entries", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "item",
          data: {
            name: "Whisperwind Pendant",
            description: "A magical pendant",
            lore: [
              {
                name: "The Bard's Tale",
                content: "Forged by a silenced bard.",
                keys: ["bard",],
                subject: { kind: "race", race: "human", },
                requires_presence: true,
              },
            ],
          },
          worldId,
        },),
      },),
    );
    expect(res.status,).toBe(201,);

    const loreEntries = await db
      .selectFrom("world_lore_entries",)
      .selectAll()
      .where("name", "=", "The Bard's Tale",)
      .execute();
    expect(loreEntries,).toHaveLength(1,);
    expect(loreEntries[0]!.name,).toBe("The Bard's Tale",);
  });

  test("creates entity without lore when lore is absent", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "character",
          data: { name: "Simple", description: "No lore here", },
        },),
      },),
    );
    expect(res.status,).toBe(201,);
    const body = await res.json();

    const loreEntries = await db
      .selectFrom("actor_lore_entries",)
      .select("id",)
      .where("actor_id", "=", body.id,)
      .execute();
    expect(loreEntries,).toHaveLength(0,);
  });

  // ── Transaction atomicity (B5) ──────────────────────────────────────────────

  test("rolls back entity insert when a follow-up lore insert fails (FK violation)", async () => {
    // insertGeneratedEntity wraps entity + lore inserts in a single transaction.
    // A world_id that does not exist violates the locations.world_id FK,
    // so the whole transaction must roll back — no orphaned entity row.
    const nonExistentWorld = uid();
    await expect(
      insertGeneratedEntity(db, {
        kind: "location",
        data: { name: "Phantom Bridge", description: "will fail", },
        description: "will fail",
        worldId: nonExistentWorld,
      }, userId,),
    ).rejects.toThrow();

    // Verify no location was persisted
    const locations = await db
      .selectFrom("locations",)
      .select("id",)
      .where("name", "=", "Phantom Bridge",)
      .execute();
    expect(locations,).toHaveLength(0,);
  });

  // ── selective flag with empty keys (N6) ─────────────────────────────────────

  test("stores selective=0 when selective=true but keys are empty", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "item",
          data: {
            name: "Sealed Locket",
            description: "A locket with no key triggers",
            lore: [
              {
                name: "No Trigger",
                content: "Cannot be triggered by keywords.",
                selective: true,
                // keys intentionally omitted → defaults to []
                position: "before_char",
              },
            ],
          },
          worldId,
        },),
      },),
    );
    expect(res.status,).toBe(201,);

    const loreEntries = await db
      .selectFrom("world_lore_entries",)
      .selectAll()
      .where("name", "=", "No Trigger",)
      .execute();
    expect(loreEntries,).toHaveLength(1,);
    // N6: selective=true with empty keys → stored as 0
    expect(loreEntries[0]!.selective,).toBe(0,);
  });

  test("stores selective=1 when selective=true and keys are non-empty", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "item",
          data: {
            name: "Whisper Stone",
            description: "A stone that whispers",
            lore: [
              {
                name: "Whisper Warning",
                content: "The stone warns of danger.",
                selective: true,
                keys: ["danger",],
                position: "before_char",
              },
            ],
          },
          worldId,
        },),
      },),
    );
    expect(res.status,).toBe(201,);

    const loreEntries = await db
      .selectFrom("world_lore_entries",)
      .selectAll()
      .where("name", "=", "Whisper Warning",)
      .execute();
    expect(loreEntries,).toHaveLength(1,);
    // selective=true with non-empty keys → stored as 1
    expect(loreEntries[0]!.selective,).toBe(1,);
  });

  // ── Synthetic location subject for lore without a subject (N5) ─────────────────

  test("location lore without a subject gets synthetic location subject in audience_scope", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "location",
          data: {
            name: "Forgotten Shrine",
            description: "An old shrine",
            lore: [
              {
                name: "Shrine History",
                content: "Built in the old age.",
                keys: ["old",],
                position: "before_char",
              },
            ],
          },
          worldId,
        },),
      },),
    );
    expect(res.status,).toBe(201,);
    const body = await res.json();

    const loreEntries = await db
      .selectFrom("world_lore_entries",)
      .selectAll()
      .where("world_id", "=", worldId,)
      .where("name", "=", "Shrine History",)
      .execute();
    expect(loreEntries,).toHaveLength(1,);
    expect(loreEntries[0]!.audience_scope,).not.toBeNull();
    const scope = JSON.parse(loreEntries[0]!.audience_scope!,);
    // Synthetic subject: { kind: "location", locationId: <entityId> }
    expect(scope.subject,).toBeDefined();
    expect(scope.subject.kind,).toBe("location",);
    expect(scope.subject.locationId,).toBe(body.id,);
    expect(scope.requires_presence,).toBe(true,);
  });

  test("character lore without subject does NOT get synthetic subject", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "character",
          data: {
            name: "Ranger",
            description: "A silent hunter",
            lore: [
              {
                name: "Hunting Ground",
                content: "Knows every trail.",
                keys: ["trail",],
                position: "before_char",
              },
            ],
          },
        },),
      },),
    );
    expect(res.status,).toBe(201,);

    const loreEntries = await db
      .selectFrom("actor_lore_entries",)
      .selectAll()
      .where("name", "=", "Hunting Ground",)
      .execute();
    expect(loreEntries,).toHaveLength(1,);
    // Character scope without subject → no audience_scope
    expect(loreEntries[0]!.audience_scope,).toBeNull();
  });
});
