// SPDX-License-Identifier: LGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Loop Lore Contributors

/**
 * Tests for POST /api/chats/:id/create-entity — the confirm endpoint for
 * entity drafts generated by the `/create` command.
 */
import { afterAll, beforeAll, describe, expect, test, } from "bun:test";
import { Elysia, } from "elysia";
import type { Kysely, } from "kysely";
import { ChatParticipantRole, } from "../../db/enums";
import type { DB, } from "../../db/schema";
import { createLogger, } from "../../logger";
import { createTestDb, } from "../../test-utils/create-test-db";
import { insertChatParticipants, insertChats, } from "../../test-utils/insert-helpers";
import { uid, } from "../../utils";
import { createEntityConfirmRoutes, } from "./create-entity-confirm";

function createApp(db: Kysely<DB>, userId: string | null,): Elysia {
  return new Elysia({ name: "test-create-entity-confirm", },)
    .derive(() => ({ userId, }))
    .use(createEntityConfirmRoutes({ database: db, config: {} as never, },),) as unknown as Elysia;
}

describe("POST /api/chats/:id/create-entity", () => {
  let db: Kysely<DB>;
  const userId = uid();
  const otherUserId = uid();
  let worldId: string;

  beforeAll(async () => {
    createLogger({ level: "error", },);
    ({ db, } = await createTestDb());

    // Create test user
    await db
      .insertInto("users",)
      .values({
        id: userId,
        username: `user-${userId}`,
        display_name: "Test User",
        role: "solo",
        status: "active",
        settings: "{}",
      },)
      .execute();
    await db
      .insertInto("actors",)
      .values({
        id: userId,
        actor_type: "user",
        display_name: "Test User",
        user_id: userId,
        owner_id: userId,
        agent_type: "none",
        settings: "{}",
        format_version: 0,
        visibility: "private",
        import_spec: "{}",
      },)
      .execute();

    // Create second user for access-denied tests
    await db
      .insertInto("users",)
      .values({
        id: otherUserId,
        username: `user-${otherUserId}`,
        display_name: "Other User",
        role: "solo",
        status: "active",
        settings: "{}",
      },)
      .execute();
    await db
      .insertInto("actors",)
      .values({
        id: otherUserId,
        actor_type: "user",
        display_name: "Other User",
        user_id: otherUserId,
        owner_id: otherUserId,
        agent_type: "none",
        settings: "{}",
        format_version: 0,
        visibility: "private",
        import_spec: "{}",
      },)
      .execute();

    // Create a world for item/location FK (insertGeneratedEntity uses
    // worldId ?? "default" and items/locations reference worlds.id)
    worldId = uid();
    await db
      .insertInto("worlds",)
      .values({
        id: worldId,
        owner_id: userId,
        name: "Test World",
        description: "A test world",
        difficulty_modifier: 1,
      },)
      .execute();
  },);

  afterAll(async () => {
    await db.destroy();
  },);

  /** Helper: create a chat with the user as participant. */
  async function createChatWithUser(): Promise<string> {
    const chatId = uid();
    await insertChats(db, "Test Chat", userId, { id: chatId, } as never,);
    await insertChatParticipants(db, chatId, userId, { role_in_chat: ChatParticipantRole.Owner, } as never,);
    return chatId;
  }

  // ── Auth ─────────────────────────────────────────────────────

  test("rejects request without userId", async () => {
    const app = createApp(db, null,);
    const res = await app.handle(
      new Request("http://localhost/api/chats/c1/create-entity", {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "character",
          data: { name: "Test", description: "A test character", },
        },),
      },),
    );
    // Elysia body validation may fire before handler, producing 422
    expect(res.ok,).toBe(false,);
  });

  // ── Validation ───────────────────────────────────────────────

  test("returns 400 for invalid entity kind", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "invalid",
          data: { name: "Test", description: "Test desc", },
        },),
      },),
    );
    expect(res.status,).toBe(400,);
    const body = await res.json();
    expect(body.error,).toContain("kind",);
  });

  test("rejects request when data.name is empty or missing", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "character",
          data: { description: "No name", },
        },),
      },),
    );
    // Elysia body schema requires name: t.String(), rejects at validation
    expect(res.ok,).toBe(false,);
  });

  test("returns 422 when character is missing description", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "character",
          data: { name: "NoDesc", },
        },),
      },),
    );
    expect(res.status,).toBe(422,);
    const body = await res.json();
    expect(body.error,).toContain("Invalid entity",);
  });

  // ── Happy path: character ────────────────────────────────────

  test("creates a character entity and returns 201", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "character",
          data: {
            name: "Aragorn",
            description: "Ranger of the North",
            personality: "Noble and steadfast",
            scenario: "Middle-earth",
          },
        },),
      },),
    );
    expect(res.status,).toBe(201,);
    const body = await res.json();
    expect(body.kind,).toBe("character",);
    expect(body.name,).toBe("Aragorn",);
    expect(body.id,).toBeString();
    expect(body.linkedChatId,).toBeNull();

    // Verify persisted in DB
    const actor = await db
      .selectFrom("actors",)
      .where("id", "=", body.id,)
      .selectAll()
      .executeTakeFirst();
    expect(actor,).toBeDefined();
    expect(actor!.display_name,).toBe("Aragorn",);
    expect(actor!.personality,).toBe("Noble and steadfast",);
  });

  // ── Happy path: world ────────────────────────────────────────

  test("creates a world entity and returns 201", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "world",
          data: {
            name: "Middle-earth",
            description: "A world of hobbits and wizards",
            lore: "Created by Ilúvatar",
          },
        },),
      },),
    );
    expect(res.status,).toBe(201,);
    const body = await res.json();
    expect(body.kind,).toBe("world",);
    expect(body.name,).toBe("Middle-earth",);

    // Verify persisted
    const world = await db
      .selectFrom("worlds",)
      .where("id", "=", body.id,)
      .selectAll()
      .executeTakeFirst();
    expect(world,).toBeDefined();
    expect(world!.name,).toBe("Middle-earth",);
    expect(world!.lore,).toBe("Created by Ilúvatar",);
  });

  // ── Happy path: item ─────────────────────────────────────────

  test("creates an item entity and returns 201", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "item",
          data: {
            name: "Sting",
            description: "A glowing Elven blade",
          },
          worldId,
        },),
      },),
    );
    expect(res.status,).toBe(201,);
    const body = await res.json();
    expect(body.kind,).toBe("item",);
    expect(body.name,).toBe("Sting",);

    // Verify persisted
    const item = await db
      .selectFrom("items",)
      .where("id", "=", body.id,)
      .selectAll()
      .executeTakeFirst();
    expect(item,).toBeDefined();
    expect(item!.name,).toBe("Sting",);
  });

  // ── Happy path: location ─────────────────────────────────────

  test("creates a location entity and returns 201", async () => {
    const chatId = await createChatWithUser();
    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "location",
          data: {
            name: "Rivendell",
            description: "The Last Homely House",
          },
          worldId,
        },),
      },),
    );
    expect(res.status,).toBe(201,);
    const body = await res.json();
    expect(body.kind,).toBe("location",);
    expect(body.name,).toBe("Rivendell",);

    // Verify persisted
    const location = await db
      .selectFrom("locations",)
      .where("id", "=", body.id,)
      .selectAll()
      .executeTakeFirst();
    expect(location,).toBeDefined();
    expect(location!.name,).toBe("Rivendell",);
  });

  // ── Chat access ──────────────────────────────────────────────

  test("returns error when user has no access to chat", async () => {
    // Create a chat owned by otherUserId — userId has no access
    const chatId = uid();
    await insertChats(db, "Private Chat", otherUserId, { id: chatId, } as never,);
    await insertChatParticipants(db, chatId, otherUserId, { role_in_chat: ChatParticipantRole.Owner, } as never,);

    const app = createApp(db, userId,);
    const res = await app.handle(
      new Request(`http://localhost/api/chats/${chatId}/create-entity`, {
        method: "POST",
        headers: { "Content-Type": "application/json", },
        body: JSON.stringify({
          kind: "character",
          data: { name: "Intruder", description: "Should fail", },
        },),
      },),
    );
    expect(res.ok,).toBe(false,);
  });
});
