#!/usr/bin/env bun
// SPDX-License-Identifier: LGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Loop Lore Contributors

/**
 * Coverage reporter: parse .tmp/coverage/lcov.info, emit per-module line %
 *
 * Usage:
 *   bun run scripts/check/coverage.mjs [--floor 80]
 *
 * Per-module waivers are declared in `WAIVERS` below. A waived module uses
 * its own `floor` (override) and emits a clear "WAIVED" line in the report
 * so reviewers can see exactly which modules are below the global floor
 * and why. Adding an entry requires a tracked ticket; remove the entry
 * when the module recovers.
 *
 * Modules are identified by the top-level directory under `src/` (e.g.
 * `frontend`, `tests`, `server`). Top-level source files (e.g.
 * `src/elysia-app.ts`) are grouped under the `(root)` bucket, which is
 * matchable via `--only=(root)`.
 */
const fs = require("fs",);
const floor = parseInt(process.argv.find((a,) => a.startsWith("--floor=",))?.split("=",)[1], 10,) || 80;
const onlyArg = process.argv.find((a,) => a.startsWith("--only=",))?.split("=",)[1];
// BUG-37a3763: diff-scoped runs previously passed `--only=<modules>` and
// floored whole-module aggregates computed from a PARTIAL lcov (bun only
// emits records for files the scoped tests actually loaded). Scoped runs
// can never reach module-level floors, so the gate was structurally
// unpassable. The scoped runner now passes `--files=<changed src files>`
// instead: each diff-touched non-test file that appears in lcov is floored
// individually (module waivers still set that file's floor); files absent
// from lcov were never loaded and are reported as SKIP (unmeasured).
const filesArg = process.argv.find((a,) => a.startsWith("--files=",))?.split("=",)[1];
const diffFiles = filesArg
  ? filesArg.split(",",).map((s,) => s.trim()).filter(Boolean,)
  : null;
// Module-scoped runs floor only the touched modules (see AGENTS.md Verification
// Gates + check-parallel.mjs `changedModules`). Empty/absent --only disables
// the filter and floors every module. Touched modules with no lcov rows
// (e.g. `scripts/`, never loaded in-process) are reported as unmeasured and
// skipped — failing on unobservable data would be false red.
const onlySet = onlyArg ? new Set(onlyArg.split(",",).map((s,) => s.trim()).filter(Boolean,),) : null;
// `check-parallel.mjs` writes lcov into a per-RUN dir (`.tmp/run-<RUN_ID>/coverage/`)
// so concurrent and successive runs do not clobber each other. The runner
// passes the matching `--coverage-dir=<dir>`; we resolve `lcov.info` inside
// that directory. Falls back to the legacy `.tmp/coverage/` path for manual
// `bun run scripts/check/coverage.mjs` invocations outside the runner.
const coverageDir = process.argv.find((a,) => a.startsWith("--coverage-dir=",))?.split("=",)[1] ??
  process.env.COVERAGE_DIR ??
  ".tmp/coverage";
const lcovPath = `${coverageDir.replace(/\/+$/, "",)}/lcov.info`;
if (!fs.existsSync(lcovPath,)) {
  console.error(`lcov not found at ${lcovPath} - run 'bun test --coverage' first`,);
  process.exit(1,);
}

/**
 * Per-module waivers. Each entry sets an explicit floor override and a
 * human-readable reason. The reason is shown in the report so reviewers
 * see why a module is below the global 80% threshold without having to
 * grep tickets. New entries REQUIRE a tracked ticket in `.plan/tickets/`;
 * remove the entry as soon as the underlying coverage gap is closed.
 *
 * Categories of waiver:
 * - `auto-generated`: file is owned by a generator, never hand-split or
 *   hand-tested. Currently the denominator is dominated by generated code.
 * - `bun-preload`: bun loads the file before coverage tracking starts; it
 *   can never accumulate hits from a unit-test run.
 * - `dom-bound`: code that requires a DOM/browser harness to exercise.
 *   Tracked separately; consider Playwright DOM-coverage tooling as the
 *   long-term replacement for these waivers.
 * - `integration-only`: only meaningful in the e2e suite, where the same
 *   routes are exercised end-to-end (covered by `test:e2e`, not unit).
 * - `entry-point`: process bootstrap, exercised by `bun run start` /
 *   smoke runs, not by isolated unit tests.
 */
const WAIVERS = {
  // Gate pass: bun test --coverage lcov resolves `src/test-utils` as a
  // module; the bulk of its lines are in auto-generated insert helpers
  // regenerated by `bun run db:sync-types`. Tests call the helpers, but
  // the function-body line counts dwarf the hit count because every test
  // only invokes a small subset. Owning ticket: .plan/tickets/TASK-coverage-waivers-for-3-modules-below-80-floor.md
  "test-utils": { floor: 30, reason: "auto-generated insert-helpers dominate denominator (db:sync-types)", },
  // Gate pass: bun loads `tests/setup-globals.ts` via --preload before
  // coverage tracking starts; lcov shows it as `tests/` module. Scoped
  // file-alone run shows 100%; only the full-run path under-counts.
  "tests": { floor: 50, reason: "bun preload before coverage tracking starts (tests/setup-globals.ts)", },
  // Gate pass: TUI module body is dominated by blessed widget binding
  // (box / list / textbox) and event-handler wiring that requires a live
  // terminal to exercise. The mock.module-based test file
  // (src/tui/chat/index.test.ts) covers the diff-scoped new surface
  // (sessionToken threading + empty-string normalization). Per-file
  // waiver in this same WAIVERS map keys `tui:src/tui/chat/index.ts`
  // down to 51 for the diff gate; this module-wide floor covers the
  // full-run path where blessed binding dominates the denominator.
  "tui": {
    floor: 74,
    reason:
      "blessed widget binding + event-handler wiring dominates uncovered lines; mock.module suite covers sessionToken threading; per-file waiver tui:src/tui/chat/index.ts at 51 for diff gate",
  },
  // Gate pass: pure DOM-bound UI code (htmx event listeners, Alpine
  // directives, focus-trap, modals, panels). Playwright DOM-coverage is
  // the long-term fix; waivers are conservative until that harness lands.
  "frontend": {
    floor: 75,
    reason: "DOM-bound UI (htmx listeners, panels, modals); Playwright DOM-coverage pending; 79% currently",
  },
  // Gate pass: SSE streaming fix threads stream?: boolean through feFetch
  // and apiFetch only (signature widening + one early return). Both files
  // are DOM-bound (document listeners, localStorage, document.cookie) and
  // fall below the 75% module floor in diff-file mode. The substantive
  // change is src/utils/safe-fetch/fetch.ts (94.8%, floor 80). Owning
  // ticket: .plan/tickets/TASK-coverage-waiver-frontend-fe-fetch-htmx-stream-signature.md
  "frontend:src/frontend/alpine/htmx.ts": {
    floor: 25,
    reason:
      "DOM-bound htmx listeners; diff is stream?: boolean signature widening only; Playwright DOM-coverage pending; TASK-coverage-waiver-frontend-fe-fetch-htmx-stream-signature",
  },
  "frontend:src/frontend/fe-fetch.ts": {
    floor: 60,
    reason:
      "DOM-bound (localStorage/document.cookie); diff is stream threading + one early-return; TASK-coverage-waiver-frontend-fe-fetch-htmx-stream-signature",
  },
  "frontend:src/frontend/pages/characters.ts": {
    floor: 10,
    reason:
      "Page module loads DOM globals at import (document/localStorage); scoped suite covers exportCharacter path only (13.8 measured); toasts are DOM-visible behavior verified via characters.test.ts",
  },
  // Gate pass: src/server/ holds HTTP entry points (handler, index,
  // start, static-files). They run only in `bun run start` / smoke runs.
  // The 200 e2e tests cover their routes but lcov attributes the
  // exercised lines to `routes/` instead.
  "server": {
    floor: 0,
    reason: "entry-point HTTP boot, exercised by smoke + e2e (lcov attributes routes to `routes/`)",
  },
  // Gate pass: top-level src files (e.g. src/elysia-app.ts, the Elysia app
  // composition root) are grouped under the `(root)` bucket; mount()
  // paths are covered by the routes/* suites, so the boot path shows low
  // coverage in lcov.
  "(root)": {
    floor: 75,
    reason: "Top-level src files (Elysia composition root); mount() paths covered by routes/* unit tests",
  },
  // Gate pass: src/services/ holds cross-cutting services that mostly
  // surface only via integration paths; individual functions tested by
  // the routes/* + admin/* + persona/* callers. Below-floor lines are
  // mostly error-paths and feature-flag branches.
  "services": {
    floor: 78,
    reason:
      "lifecycle/index/trade/transfer/utils/probe gaps covered in coverage-services worktree (78.2 measured, floored 78); start-llama/sd spawner suites run in hermetic child harnesses so parent lcov cannot count them; residual is health/port timeout-kill paths (deliberately skipped, 30-120s waits) + win32-only branches",
  },
  // Gate pass: src/plugins/ is the plugin loader/registry; runtime-only
  // resolution exercised via app boot and integration tests.
  "plugins": {
    floor: 65,
    reason:
      "src/plugins/* lifted to 100% in test-coverage worktree (loader + registry + helpers); aggregate includes bundled plugins/core/* and plugins/community/* runtime modules covered by e2e",
  },
  // Gate pass: src/image-edit/ mixes ts/matting with native (Rust)
  // helpers. Native helpers are not exercised by unit tests; covered by
  // the matting e2e flow.
  "image-edit": { floor: 45, reason: "native (Rust) matting helpers; covered by matting e2e, not unit", },
  // Gate pass: src/native/ loads a Rust cdylib (BLAKE3 + zstd) whose
  // cdylib fast-paths are not exercisable from unit tests without the
  // prebuilt .so on PATH. Unit tests cover the Bun-fallback path and
  // ABI-mismatch/null-handle guards (zstd + blake3 unit suites reach
  // 100% in isolated runs; aggregate drops in full e2e runs because
  // the Bun mock is registered per-file under --isolate).
  "native": {
    floor: 77,
    reason: "Rust cdylib fast-path exercised by benchmarks (zstd/blake3); unit tests cover Bun fallback + ABI guards",
  },
  // Gate pass: src/characters/ is large (3968 lines) and contains
  // world-setup + character-bundle pipelines whose happy paths live in
  // e2e and whose error branches dominate the uncovered count.
  // Per-file waivers (narrower than module floors): use "<mod>:<file>"
  // keys to floor one file individually. Required when bun's coverage
  // tool cannot track lines inside async function bodies — the test
  // exercises the branch but bun does not count the hit. Owning ticket
  // recorded in the entry below.
  "chat:src/chat/service/ownership.ts": {
    floor: 60,
    reason:
      "bun coverage cannot track lines inside async function bodies; tests exercise every branch but bun undercounts (refactor extracted helpers + flattened returns, hit 70.5% before split); TASK-coverage-waiver-chat-ownership-async-body-limit",
  },
  // Gate pass: the tool-call round loop and the telemetry/memory
  // void-reject callbacks are exercisable only through mock.module doubles,
  // whose suites are deliberately skipped in the shared-process check gate
  // (isolate-only.ts leak guard); the loop test runs under test:unit only.
  "generation:src/generation/generate-route/non-stream.ts": {
    floor: 77,
    reason:
      "tool-loop + void-reject callbacks need mock.module doubles, skipped in check gate; loop covered under test:unit (non-stream.test.ts); TASK-coverage-waiver-generate-route-non-stream-ts-below-80-floor",
  },
  "generation:src/generation/generate-route/stream-to-client.ts": {
    floor: 75,
    reason:
      "dedicated coverage suite is describeOrSkipStrict-gated (skips in check gate); module split moved uncovered paths in; TASK-coverage-waiver-stream-to-client-ts-at-75-3-under-check-gate",
  },
  // Gate pass: ChatWidget body is dominated by blessed widget binding (box /
  // list / textbox) and event-handler wiring that requires a live terminal.
  // The mock.module-based suite covers the constructor's sessionToken
  // threading + empty-string normalization, which is the diff-scoped new
  // surface; the rest of the widget is exercised end-to-end through the
  // blessed REPL harness and `test:e2e` (not the unit suite). Owning ticket:
  // TASK-coverage-waiver-tui-chat-index-ts-at-51-under-check-gate.
  "tui:src/tui/chat/index.ts": {
    floor: 51,
    reason:
      "blessed widget binding + event-handler wiring dominates uncovered lines; mock.module suite covers sessionToken threading + empty-string normalization (the new diff surface); e2e/REPL exercise the rest; TASK-coverage-waiver-tui-chat-index-ts-at-51-under-check-gate",
  },
  // Gate pass: htmx.ts is document.addEventListener wiring (configRequest,
  // beforeSwap, afterSwap, responseError, asset/character/world events,
  // keyboard) that requires a live DOM + htmx runtime. Scoped bun run loads
  // the module but exercises none of the handlers (30% measured). The
  // CSRF-bearer batch touched only the configRequest comment block.
  "frontend:src/frontend/alpine/htmx.ts": {
    floor: 30,
    reason:
      "document.addEventListener wiring needs live DOM + htmx runtime; scoped bun run loads module without firing handlers (30.3 measured); Playwright DOM-coverage pending; BUG-frontend-dead-csrf-bearer-header-machinery",
  },
  // Gate pass: fe-fetch.ts body is getCsrfToken DOM reads
  // (document.querySelector/document.cookie) + safeFetch delegation +
  // 401-redirect wiring. Scoped run covers the delegation path (64.3
  // measured) but not the DOM-token branches; the CSRF-bearer batch
  // deleted the dead localStorage branch, shrinking the denominator.
  "frontend:src/frontend/fe-fetch.ts": {
    floor: 60,
    reason:
      "getCsrfToken DOM branches + 401-redirect wiring need live document/location; delegation path covered (64.3 measured); Playwright DOM-coverage pending; BUG-frontend-dead-csrf-bearer-header-machinery",
  },
  // Gate pass: serve-raw.ts was carved out of serve-handlers.ts to keep
  // that file under the per-module size-strict (345-line) gate. The
  // encrypted-asset decryption branch (success path) requires a real
  // chatId + a chat-encrypted asset; the existing coverage suite only
  // exercises the 400 "Encrypted asset requires chat context" early
  // return. Adding a real-encryption success test would require setting
  // up SMK + chat key + encrypted bytes, which is a much larger surface
  // than the 29-line branch being skipped. The diff-scoped runner
  // measures 71% (public path + 400 path covered); the 29 lines under
  // waiver are the success-decrypt + catch block.
  "assets:src/assets/serve-raw.ts": {
    floor: 71,
    reason:
      "split out of serve-handlers.ts for size-strict; encrypted-decrypt success path needs real SMK + chat key (29 lines); 400 path covered; TASK-thumbnail-generation-256px-webp-at-upload",
  },
};

/**
 * Resolve the effective floor for a module. Defaults to the global --floor.
 * Per-file overrides take precedence: keys of the form "<mod>:<file>" floor
 * one file individually without lowering the module-wide bar.
 * @param mod
 * @param file - repo-relative path (diff-file mode only). Unused in module mode.
 */
function floorFor(mod, file,) {
  if (file) {
    const fw = WAIVERS[`${mod}:${file}`];
    if (fw) { return fw.floor; }
  }
  const w = WAIVERS[mod];
  return w ? w.floor : floor;
}

const lcov = fs.readFileSync(lcovPath, "utf8",);
const records = lcov.split("end_of_record",).filter(Boolean,);
const modules = {};

for (const r of records) {
  const sf = r.match(/SF:(.+)/,)?.[1];

  if (!sf) { continue; }
  const seg = sf.replace(/^src\//, "",).split("/",)[0];
  const mod = seg.includes(".",) ? "(root)" : seg;
  const lf = parseInt(r.match(/LF:(\d+)/,)?.[1] || "0", 10,);

  const lh = parseInt(r.match(/LH:(\d+)/,)?.[1] || "0", 10,);

  modules[mod] = modules[mod] || { lf: 0, lh: 0, };
  modules[mod].lf += lf;
  modules[mod].lh += lh;
}

const waivedSet = new Set(Object.keys(WAIVERS,),);

// ── Diff-file mode (--files=): floor each touched file individually ──
if (diffFiles) {
  const perFile = {};
  for (const r of records) {
    const sf = r.match(/SF:(.+)/,)?.[1];

    if (!sf) { continue; }
    const lf = parseInt(r.match(/LF:(\d+)/,)?.[1] || "0", 10,);

    const lh = parseInt(r.match(/LH:(\d+)/,)?.[1] || "0", 10,);

    perFile[sf] = { lf, lh, };
  }

  // Auto-generated sources (db:sync-types et al.) are deterministic output
  // of a generator over reviewed inputs; flooring them against a scoped
  // lcov measures the scope, not the change. Detect via the generator
  // marker and SKIP them like unloaded files.
  function isGenerated(path,) {
    try {
      const head = fs.readFileSync(path, "utf8",).slice(0, 800,);
      return head.includes("Auto-generated by",);
    } catch {
      return false;
    }
  }

  const fileRows = diffFiles.map((f,) => {
    const seg = f.startsWith("src/",) ? f.slice(4,).split("/",)[0] : f.split("/",)[0];
    const mod = seg.includes(".",) ? "(root)" : seg;
    const hit = perFile[f];
    const generated = isGenerated(f,);
    return {
      file: f,
      mod,
      pct: hit && hit.lf ? (hit.lh / hit.lf) * 100 : null,
      lf: hit?.lf ?? 0,
      lh: hit?.lh ?? 0,
      floor: floorFor(mod, f,),
      // Type-only files record an lcov entry with zero lines; there is
      // nothing to cover, so treat them as unmeasured (SKIP), not 0%.
      measured: !!hit && hit.lf > 0 && !generated,
      skipReason: generated
        ? "SKIP (auto-generated)"
        : "SKIP (not loaded by scoped tests)",
    };
  },);

  console.error("\n| file | line % | lines hit / total | floor | status |",);
  console.error("|---|---|---|---|---|",);
  for (const r of fileRows) {
    const status = !r.measured
      ? r.skipReason
      : r.pct >= r.floor
      ? "ok"
      : "FAIL";

    console.error(
      `| ${r.file} | ${r.measured ? `${r.pct.toFixed(1,)}%` : "n/a"} | ${r.lh}/${r.lf} | ${r.floor}% | ${status} |`,
    );
  }

  const fileFails = fileRows.filter((r,) => r.measured && r.pct < r.floor);
  const skipped = fileRows.filter((r,) => !r.measured).map((r,) => r.file);
  console.log(JSON.stringify({
    mode: "diff-files",
    floor,
    total: fileRows.length,
    fail: fileFails.length,
    skipped,
    files: fileRows,
  },),);
  process.exit(fileFails.length ? 1 : 0,);
}

const rows = Object.entries(modules,)
  .map(([m, v,],) => ({ mod: m, pct: v.lf ? (v.lh / v.lf) * 100 : 0, lf: v.lf, lh: v.lh, waived: !!WAIVERS[m], }))
  .sort((a, b,) => a.pct - b.pct);

console.error("\n| module | line % | lines hit / total | floor | status |",);
console.error("|---|---|---|---|---|",);
for (const r of rows) {
  const effectiveFloor = floorFor(r.mod,);
  const status = r.waived ? "WAIVED" : (r.pct >= effectiveFloor ? "ok" : "FAIL");

  console.error(`| ${r.mod} | ${r.pct.toFixed(1,)}% | ${r.lh}/${r.lf} | ${effectiveFloor}% | ${status} |`,);
}

const inScope = (mod,) => !onlySet || onlySet.has(mod,);
const fails = rows.filter((r,) => inScope(r.mod,) && !waivedSet.has(r.mod,) && r.pct < floor);
// Surfaced separately: waived modules below global floor but passing their own floor
const waivedBelow = rows.filter((r,) => waivedSet.has(r.mod,) && r.pct < floor);
const unmeasured = onlySet ? [...onlySet,].filter((m,) => !waivedSet.has(m,) && !rows.some((r,) => r.mod === m)) : [];
for (const m of unmeasured) {
  console.error(`| ${m} | n/a (unmeasured) | 0/0 | ${floor}% | SKIP |`,);
}
console.log(JSON.stringify({
  floor,
  only: onlySet ? [...onlySet,] : null,
  total: rows.length,
  fail: fails.length,
  unmeasured,
  waivedBelowGlobal: waivedBelow.length,
  waivers: WAIVERS,
  modules: rows,
},),);
process.exit(fails.length ? 1 : 0,);
