// SPDX-License-Identifier: LGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Loop Lore Contributors

import type { AlpineMagicThis, GalleryAsset, PromptTemplateInfo, QuickReplyButton, } from "../types";
import type * as filterState from "./filter-state";
import type { GenerationDetail, GroupedMessage, Message, } from "./messages";
import type * as uiState from "./ui-state";
import type { ChatWorldChannelsState, } from "./world-channels";
export type { ChatCoreFilterState, } from "./filter-state";
export type { ChatCoreUiState, } from "./ui-state";
/** Chat page core state and methods (messages, lists, editing, VN, filters). */
export interface ChatCoreState
  extends AlpineMagicThis, ChatWorldChannelsState, filterState.ChatCoreFilterState, uiState.ChatCoreUiState
{
  isGenerating: boolean;
  generationLabel: string;
  activeAttemptId: string | null;
  continuingMessageId: string | null;
  isContinuing: boolean;
  _generationEventSource: EventSource | null;
  /** Rendered tool-call blocks emitted during live streaming (prepended to stream container). */
  _streamToolCalls: string[];
  /** Latest streamed content HTML (preserved so tool-call renders don't wipe it). */
  _streamContent: string;
  chats: {
    id: string;
    name?: string;
    isPinned?: number;
    type?: string;
    mode?: string;
    turn_strategy?: string;
    story_state?: string;
    gm_config?: string;
    thinking_visibility?: string;
    prompt_override?: string | null;
    quick_replies?: string | null;
  }[];
  activeChat: string | null;
  messages: Message[];
  loadingMessages: boolean;
  loadingError: string | null;
  hasMoreMessages: boolean;
  loadingOlder: boolean;
  currentPage: number;
  totalPages: number;
  scrollObserver: IntersectionObserver | null;
  activeChatName: string;
  galleryAssets: GalleryAsset[];
  userDisplayName: string;
  userRole: string;
  currentCharacter: {
    id: string;
    display_name?: string;
    name?: string;
    description?: string;
    avatar_asset_id?: string;
  } | null;
  generationDetail: GenerationDetail | null;
  detailLevel: "Immersion" | "Basic" | "Detailed";
  impersonationActive: boolean;
  impersonatingActorId: string | null;
  editingMessageId: string | null;
  editContent: string;
  previewMediaAsset: GalleryAsset | null;
  pendingAssets: { assetId: string; filename: string }[];
  groupedMessages: GroupedMessage[];
  _observer: MutationObserver | null;
  _groupedKey: string;
  _groupedCache: GroupedMessage[] | null;
  _toggleChatListHandler: (() => void) | null;
  _toggleGalleryHandler: (() => void) | null;
  _toggleCharacterInfoHandler: (() => void) | null;
  _toggleMemoryPanelHandler: (() => void) | null;
  _panelClickHandler: ((e: MouseEvent,) => void) | null;
  _keydownHandler: ((e: KeyboardEvent,) => void) | null;
  _chatSettingsName: string;
  _chatSettingsMode: string;
  _chatSettingsTurnStrategy: string;
  _chatSettingsThinkingVisibility: "hidden" | "collapsed" | "visible";
  _chatOnline: boolean;
  _groupPaused: boolean;
  _renameChatId: string;
  _renameChatName: string;
  _personas: any[];
  _selectedPersonaId: string | null;
  _impersonatingActorId: string | null;
  _assistantRole: "off" | "helper" | "gm" | "moderator";
  _gmType: "llm" | "human" | "hybrid";
  _gmHumanActorId: string;
  _gmEscalationThreshold: number;
  // GM LLM settings + per-actor overrides (multi-LLM story mode) — persisted to gm_config.
  _gmModel: string;
  _gmProvider: string;
  _gmTemperature: number;
  _gmMaxTokens: number;
  _actorModels: Record<string, { model: string; provider: string }>;
  // VN (visual novel) mode settings — persisted to gm_config.
  _vnEnabled: boolean;
  _vnLayout: "overlay" | "below" | "split";
  _vnTypewriter: boolean;
  _vnTypewriterSpeed: number;
  _vnTransition: "fade" | "cut" | "dissolve" | "slide" | "wipe";
  _vnAutoAdvance: boolean;
  _responseLengthPreset: "short" | "medium" | "long" | "custom";
  _responseLengthCustom: number;
  _promptTemplate: PromptTemplateInfo | null;
  _promptLoading: boolean;
  _promptExpanded: boolean;
  _promptOverrideDraft: string;
  _promptOverrideSaving: boolean;
  loadPromptTemplate(): Promise<void>;
  savePromptOverride(): Promise<void>;
  _quickReplies: QuickReplyButton[];
  _quickRepliesDirty: boolean;
  _startupFiredChat: string | null;
  /** Marks an automated (event-triggered) send so it doesn't re-trigger `user` events. */
  _autoFired: boolean;
  /** Epoch ms of the last automated send; drives the min-interval rate limit. */
  _lastAutoFireAt: number;
  /** Consecutive automated sends since the last human-initiated send; capped to break loops. */
  _consecutiveAutoFires: number;
  loadQuickReplies(): void;
  executeQuickReply(command: string,): Promise<void>;
  fireStartupQuickReplies(): Promise<void>;
  fireAutoQuickReplies(trigger: "user" | "ai",): Promise<void>;
  saveQuickReplies(): Promise<void>;
  // Proactive messaging scheduler (chat-proactive.ts) — polls for due messages.
  _proactiveTimer: ReturnType<typeof setInterval> | null;
  _proactiveInFlight: boolean;
  _proactiveLastSendAt: number;
  startProactiveScheduler(): void;
  stopProactiveScheduler(): void;
  tickProactive(): Promise<void>;
  _chatKey: CryptoKey | null;
  _encryptionEnabled: boolean;
  _keyId: string | null;
  init(): void;
  destroy(): void;
  loadUserInfo(): Promise<void>;
  loadChats(): Promise<void>;
  selectChat(chatId: string,): Promise<void>;
  loadMessages(): Promise<void>;
  loadOlderMessages(): Promise<void>;
  setupInfiniteScroll(): void;
  sendMessage(): Promise<void>;
  autoResize(el: HTMLTextAreaElement,): void;
  scrollToBottom(): void;
  setupScrollDetection(): void;
  scrollToBottomSmooth(): void;
  loadGalleryAssets(): Promise<void>;
  uploadChatAssets(event: Event,): Promise<void>;
  loadCharacterInfo(): Promise<void>;
  formatTime(iso: string,): string;
  formatTimeShort(iso: string,): string;
  displayName(msg: { role: string; actor_name?: string },): string;
  copyMessage(msgId: string, event: Event,): Promise<void>;
  removeMessage(msgId: string, event: Event,): Promise<void>;
  toggleImpersonate(): Promise<void>;
  impersonate(cmd: string,): Promise<void>;
  toggleDebugView(): void;
  handleCommandInput(event: Event,): void;
  selectCommand(name: string,): void;
  dispatchCommandAction(action: string, payload: Record<string, unknown> | null, chatId: string,): Promise<void>;
  loadImpersonationState(): Promise<void>;
  loadChatParticipants(): Promise<void>;
  loadPersonas(): Promise<void>;
  setPersona(): Promise<void>;
  toggleImpersonation(): Promise<void>;
  generateImageFromMessage(msgId: string,): Promise<void>;
  captionMessage(msgId: string,): Promise<void>;
  statsLine(msg: {
    model_id?: string;
    provider?: string;
    generation_time_ms?: number;
    token_count_total?: number;
    tokens_per_second?: number;
  },): string;
  formattedGenerationTime(ms?: number,): string;
  formattedTokensPerSecond(msg: {
    tokens_per_second?: number;
    generation_time_ms?: number;
    token_count_total?: number;
  },): string;
  connectGenerationSSE(chatId: string,): void;
  renderStreamContainer(): void;
  _cleanupSSE(): void;
  cancelGeneration(): Promise<void>;
  markChatAsRead(chatId: string,): Promise<void>;
  getUnseenCount(chatId: string,): number;
  regenerateResponse(): Promise<void>;
  regenerateVariant(messageId: string,): Promise<void>;
  switchVariant(messageId: string, direction: number,): Promise<void>;
  continueMessage(messageId: string,): Promise<void>;
  retryFromPoint(attemptId: string, step: number,): Promise<void>;
  getChatId(): string | null;
  handleAttach(event: Event,): Promise<void>;
  escapeHtml(str: string,): string;
  startEdit(msgId: string,): void;
  cancelEdit(): void;
  saveEdit(msgId: string,): Promise<void>;
  renderMarkdown(content: string,): string;
  getMediaStyle(asset: any, totalCount: number,): Record<string, string>;
  openMediaPreview(asset: any,): void;
  removePendingAsset(assetId: string,): void;
  openAssetPreview(asset: { id: string; asset_type?: string; filename?: string; name?: string },): void;
  openChatSettings(): Promise<void>;
  updateVnMode(): void;
  saveChatSettings(): Promise<void>;
  isChatPaused(chat: any,): boolean;
  readonly currentChat: {
    id: string;
    name?: string;
    type?: string;
    mode?: string;
    turn_strategy?: string;
    story_state?: string;
    gm_config?: string;
    thinking_visibility?: string;
  } | null;
  toggleGroupPause(): Promise<void>;
  renameChat(chatId: string,): Promise<void>;
  openRenameModal(chatId: string,): void;
  confirmRenameChat(): Promise<void>;
  deleteChat(chatId: string, event: Event,): Promise<void>;
  toggleChatPin(chatId: string,): Promise<void>;
  toggleChatSelection(chatId: string,): void;
  batchArchive(): Promise<void>;
  batchDelete(): Promise<void>;
  batchExport(): Promise<void>;
  loadChatKey(chatId: string,): Promise<void>;
  checkGenerationStatus(chatId: string,): Promise<void>;
  registerPanelHandlers(): void;
  unregisterPanelHandlers(): void;
}
