import type { AlpineMagicThis, GalleryAsset, PromptTemplateInfo, } from "../types";
import type { GenerationDetail, GroupedMessage, Message, } from "./messages";
import type { WorldChannelChat, } from "./world";

/** Chat page core state and methods (messages, lists, editing, VN, filters). */
export interface ChatCoreState extends AlpineMagicThis {
  isGenerating: boolean;
  generationLabel: string;
  activeAttemptId: string | null;
  continuingMessageId: string | null;
  isContinuing: boolean;
  _generationEventSource: EventSource | null;
  /** Rendered tool-call blocks emitted during live streaming (prepended to stream container). */
  _streamToolCalls: string[];
  /** Latest streamed content HTML (preserved so tool-call renders don't wipe it). */
  _streamContent: string;
  chats: {
    id: string;
    name?: string;
    isPinned?: number;
    type?: string;
    mode?: string;
    turn_strategy?: string;
    story_state?: string;
    gm_config?: string;
  }[];
  activeChat: string | null;
  messages: Message[];
  loadingMessages: boolean;
  loadingError: string | null;
  hasMoreMessages: boolean;
  loadingOlder: boolean;
  currentPage: number;
  totalPages: number;
  scrollObserver: IntersectionObserver | null;
  activeChatName: string;
  galleryAssets: GalleryAsset[];
  userDisplayName: string;
  userRole: string;
  currentCharacter: {
    id: string;
    display_name?: string;
    name?: string;
    description?: string;
    avatar_asset_id?: string;
  } | null;
  generationDetail: GenerationDetail | null;
  detailLevel: "Immersion" | "Basic" | "Detailed";
  impersonationActive: boolean;
  impersonatingActorId: string | null;
  editingMessageId: string | null;
  editContent: string;
  previewMediaAsset: GalleryAsset | null;
  pendingAssets: { assetId: string; filename: string }[];
  groupedMessages: GroupedMessage[];
  _observer: MutationObserver | null;
  _groupedKey: string;
  _groupedCache: GroupedMessage[] | null;
  _toggleChatListHandler: (() => void) | null;
  _toggleGalleryHandler: (() => void) | null;
  _toggleCharacterInfoHandler: (() => void) | null;
  _toggleMemoryPanelHandler: (() => void) | null;
  _panelClickHandler: ((e: MouseEvent,) => void) | null;
  _keydownHandler: ((e: KeyboardEvent,) => void) | null;
  _chatSettingsName: string;
  _chatSettingsMode: string;
  _chatSettingsTurnStrategy: string;
  _chatOnline: boolean;
  _groupPaused: boolean;
  _renameChatId: string;
  _renameChatName: string;
  _personas: any[];
  _selectedPersonaId: string | null;
  _impersonatingActorId: string | null;
  _assistantRole: "off" | "helper" | "gm" | "moderator";
  _gmType: "llm" | "human" | "hybrid";
  _gmHumanActorId: string;
  _gmEscalationThreshold: number;
  // GM LLM settings + per-actor overrides (multi-LLM story mode) — persisted to gm_config.
  _gmModel: string;
  _gmProvider: string;
  _gmTemperature: number;
  _gmMaxTokens: number;
  _actorModels: Record<string, { model: string; provider: string }>;
  // VN (visual novel) mode settings — persisted to gm_config.
  _vnEnabled: boolean;
  _vnLayout: "overlay" | "below" | "split";
  _vnTypewriter: boolean;
  _vnTypewriterSpeed: number;
  _vnTransition: "fade" | "cut" | "dissolve" | "slide" | "wipe";
  _vnAutoAdvance: boolean;
  // Prompt template preview
  _promptTemplate: PromptTemplateInfo | null;
  _promptLoading: boolean;
  _promptExpanded: boolean;
  loadPromptTemplate(): Promise<void>;
  _chatKey: CryptoKey | null;
  _encryptionEnabled: boolean;
  _keyId: string | null;
  _hamburgerOpen: Record<string, boolean>;
  _statsOpen: Record<string, boolean>;
  _contextMenu: { visible: boolean; messageId: string | null; x: number; y: number };
  _impersonationLoaded: boolean;
  _storageHandler: ((e: StorageEvent,) => void) | null;
  _unseenCounts: Record<string, number>;
  _isScrolledUp: boolean;
  _scrollHandler: (() => void) | null;
  _debugView: boolean;
  _showCommandPalette: boolean;
  _activeCommand: string;
  _commandList: { name: string; description: string }[];
  _filteredCommands: { name: string; description: string }[];
  _chatFilter: string;
  readonly filteredChats: { id: string; name?: string }[];
  // Chat-list filters (chat-filters.ts) — server-side query params for /api/chats.
  _chatType: "all" | "direct" | "group";
  _chatStatus: "all" | "active" | "archived";
  _chatSort: "recent" | "name" | "unread" | "pinned-first";
  _filterParams(): string;
  applyChatFilters(): Promise<void>;
  _searchResults: { chatId: string; chatName: string; characterName: string; characterAvatar: string | null }[];
  searchChats(q: string,): Promise<void>;
  // World channels (chat-only worlds) — sidebar tree.
  _worlds: { id: string; name: string }[];
  _worldChats: Record<string, WorldChannelChat[]>;
  _worldExpanded: Record<string, boolean>;
  _worldsLoading: boolean;
  worldJoinCode: string;
  loadWorldChannels(): Promise<void>;
  loadWorldChats(worldId: string,): Promise<void>;
  toggleWorld(worldId: string,): void;
  worldChatGroups(worldId: string,): { locationId: string; locationName: string; chats: WorldChannelChat[] }[];
  joinWorldByCode(): Promise<void>;
  _joinableChats: { chatId: string; chatName: string; participantCount: number; lastActiveAt: string | null }[];
  loadJoinableChats(): Promise<void>;
  joinChat(chatId: string,): Promise<void>;
  selectedChats: string[];
  _mentionQuery: string;
  _mentionResults: { actor_id: string; name: string; display_name?: string; actor_type?: string }[];
  _showMentionAutocomplete: boolean;
  _chatParticipants: { actor_id: string; name: string; display_name?: string; actor_type?: string }[];
  init(): void;
  destroy(): void;
  loadUserInfo(): Promise<void>;
  loadChats(): Promise<void>;
  selectChat(chatId: string,): Promise<void>;
  loadMessages(): Promise<void>;
  loadOlderMessages(): Promise<void>;
  setupInfiniteScroll(): void;
  sendMessage(): Promise<void>;
  autoResize(el: HTMLTextAreaElement,): void;
  scrollToBottom(): void;
  setupScrollDetection(): void;
  scrollToBottomSmooth(): void;
  loadGalleryAssets(): Promise<void>;
  loadCharacterInfo(): Promise<void>;
  formatTime(iso: string,): string;
  formatTimeShort(iso: string,): string;
  displayName(msg: { role: string; actor_name?: string },): string;
  copyMessage(msgId: string, event: Event,): Promise<void>;
  removeMessage(msgId: string, event: Event,): Promise<void>;
  toggleImpersonate(): Promise<void>;
  toggleDebugView(): void;
  handleCommandInput(event: Event,): void;
  selectCommand(name: string,): void;
  dispatchCommandAction(action: string, payload: Record<string, unknown> | null, chatId: string,): Promise<void>;
  loadImpersonationState(): Promise<void>;
  loadChatParticipants(): Promise<void>;
  loadPersonas(): Promise<void>;
  setPersona(): Promise<void>;
  toggleImpersonation(): Promise<void>;
  generateImageFromMessage(msgId: string,): Promise<void>;
  captionMessage(msgId: string,): Promise<void>;
  statsLine(msg: {
    model_id?: string;
    provider?: string;
    generation_time_ms?: number;
    token_count_total?: number;
    tokens_per_second?: number;
  },): string;
  formattedGenerationTime(ms?: number,): string;
  formattedTokensPerSecond(msg: {
    tokens_per_second?: number;
    generation_time_ms?: number;
    token_count_total?: number;
  },): string;
  connectGenerationSSE(chatId: string,): void;
  renderStreamContainer(): void;
  _cleanupSSE(): void;
  cancelGeneration(): Promise<void>;
  markChatAsRead(chatId: string,): Promise<void>;
  getUnseenCount(chatId: string,): number;
  regenerateResponse(): Promise<void>;
  regenerateVariant(messageId: string,): Promise<void>;
  switchVariant(messageId: string, direction: number,): Promise<void>;
  continueMessage(messageId: string,): Promise<void>;
  retryFromPoint(attemptId: string, step: number,): Promise<void>;
  getChatId(): string | null;
  handleAttach(event: Event,): Promise<void>;
  escapeHtml(str: string,): string;
  startEdit(msgId: string,): void;
  cancelEdit(): void;
  saveEdit(msgId: string,): Promise<void>;
  renderMarkdown(content: string,): string;
  getMediaStyle(asset: any, totalCount: number,): Record<string, string>;
  openMediaPreview(asset: any,): void;
  removePendingAsset(assetId: string,): void;
  openAssetPreview(asset: { id: string; asset_type?: string; filename?: string; name?: string },): void;
  openChatSettings(): Promise<void>;
  updateVnMode(): void;
  openContextMenu(event: MouseEvent, msgId: string,): void;
  closeContextMenu(): void;
  saveChatSettings(): Promise<void>;
  isChatPaused(chat: any,): boolean;
  readonly currentChat: {
    id: string;
    name?: string;
    type?: string;
    mode?: string;
    turn_strategy?: string;
    story_state?: string;
    gm_config?: string;
  } | null;
  toggleGroupPause(): Promise<void>;
  handleMentionInput(event: Event,): void;
  selectMention(participant: { actor_id: string; name: string },): void;
  hideMentionAutocomplete(): void;
  renameChat(chatId: string,): Promise<void>;
  openRenameModal(chatId: string,): void;
  confirmRenameChat(): Promise<void>;
  deleteChat(chatId: string, event: Event,): Promise<void>;
  toggleChatPin(chatId: string,): Promise<void>;
  toggleChatSelection(chatId: string,): void;
  batchArchive(): Promise<void>;
  batchDelete(): Promise<void>;
  batchExport(): Promise<void>;
  loadChatKey(chatId: string,): Promise<void>;
  checkGenerationStatus(chatId: string,): Promise<void>;
  registerPanelHandlers(): void;
  unregisterPanelHandlers(): void;
  toggleReaction(msgId: string, emoji: string,): Promise<void>;
  loadMessageReactions(msgId: string,): Promise<void>;
  loadAllReactions(): Promise<void>;
  _reactionPicker: { visible: boolean; messageId: string; x: number; y: number };
  _quickEmojis: string[];
  showReactionPicker(msgId: string, event: Event,): void;
  closeReactionPicker(): void;
}
