// SPDX-License-Identifier: LGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Loop Lore Contributors

/**
 * Primitive + enum validation schemas.
 *
 * Shared leaf schemas (ids, names, pagination) plus generic response
 * helpers. DB-backed enums are re-exported from generated ../db-schemas.
 */

import { t, } from "elysia";
import type { Static, } from "@sinclair/typebox";
import { ChatRenderingOverrideSchema, } from "../db-schemas";

// ── Primitives ─────────────────────────────────────────────

export const Id = t.String({ format: "uuid", description: "UUID v4", },);
export const Name = t.String({ minLength: 1, maxLength: 255, description: "Entity name", },);
export const DisplayName = t.String({ minLength: 1, maxLength: 128, description: "Display name", },);
export const OptionalId = t.Optional(t.String({ format: "uuid", },),);
export const NullableId = t.Nullable(t.String({ format: "uuid", },),);

// ── Pagination ─────────────────────────────────────────────

export const PaginationQuery = t.Object({
  page: t.Optional(t.Numeric({ minimum: 1, default: 1, },),),
  pageSize: t.Optional(t.Numeric({ minimum: 1, maximum: 200, default: 50, },),),
},);

// ── DB-backed enums (generated single source) ───────────────────
// Re-exported from ../db-schemas.ts (generated by
// scripts/generate-db-types.ts from src/db/enums-*.ts). Do NOT hand-edit
// values here — extend the DB enum and regenerate.
export {
  ActorTypeSchema,
  ActorVisibilitySchema,
  AgentTypeSchema,
  AssetTypeSchema,
  AssetVisibilitySchema,
  ChatModeSchema,
  ChatParticipantRoleSchema,
  ChatRenderingOverrideSchema,
  ChatTypeSchema,
  ChatVisibilitySchema,
  ContentEncodingSchema,
  ContentRatingSchema,
  EncryptionLevelSchema,
  GenerationStatusSchema,
  ItemCategorySchema,
  ItemRaritySchema,
  LorePositionSchema,
  MemoryTypeSchema,
  MessageContentTypeSchema,
  MessageRoleSchema,
  MessageStatusSchema,
  MessageVisibilitySchema,
  NoteCategorySchema,
  PinnedStateSchema,
  QuestCategorySchema,
  QuestStatusSchema,
  QuestTypeSchema,
  StorageBackendSchema,
  ThinkingVisibilitySchema,
  TurnStatusSchema,
  TurnStrategySchema,
  TurnTypeSchema,
  UserRoleSchema,
  UserStatusSchema,
  WorldEventTypeSchema,
  WorldKindSchema,
  WorldVisibilitySchema,
} from "../db-schemas";

// ── Shared UI-only enums (no DB-generated counterpart) ──────────
// Single source for chat-presentation literals that live in `chats` JSON
// columns (`gm_config`, `quick_replies`) rather than DB enums. Services
// consume the `Static` types below via `import type` (no runtime dependency).
export const QuickReplyTriggerSchema = t.UnionEnum(["startup", "user", "ai",],);
export type QuickReplyTrigger = Static<typeof QuickReplyTriggerSchema>;
export const MemoryCarrySchema = t.UnionEnum(["full", "selective", "fresh",],);
export type MemoryCarry = Static<typeof MemoryCarrySchema>;
export const ChatHistoryCarrySchema = t.UnionEnum(["none", "summary", "full",],);
export type ChatHistoryCarry = Static<typeof ChatHistoryCarrySchema>;
export const OutputStylePresetSchema = t.UnionEnum([
  "neutral", "high_fantasy", "sci_fi", "modern", "noir", "cyberpunk",
  "pulp", "literary", "horror", "western", "",
],);
/** Nullable chat rendering override (DB `ChatRenderingOverride` + JSON null marker). */
export const NullableChatRenderingOverrideSchema = t.Union([ChatRenderingOverrideSchema, t.Null(),],);

// ── Hand-authored config enums (no DB counterpart) ──────────────
// Gm* members describe chat-level GM configuration JSON, not DB enums.
/** Tag-proposition provenance — single source for `TagProvenance` in `src/assets/service/tag-propositions.ts`. */
export const TagProvenanceSchema = t.UnionEnum(["alt_text", "filename",],);
export type TagProvenance = Static<typeof TagProvenanceSchema>;

/** Chat-level GM configuration — stored as JSON in `chats.gm_config` */
/** Per-participant turn priority for GM-guided story guidance. */
export const GmTurnPrioritySchema = t.UnionEnum(["high", "medium", "low",],);

/** Narrative guidance a human Game Master applies to a story chat. */
export const GmGuidanceSchema = t.Object({
  constraints: t.Array(t.String(),),
  targetCharacter: t.Optional(t.String(),),
  sceneDescription: t.Optional(t.String(),),
  turnPriority: t.Record(t.String(), GmTurnPrioritySchema,),
},);

export const GmConfigSchema = t.Object({
  assistantRole: t.Optional(t.UnionEnum(["off", "helper", "gm", "moderator",],),),
  renderingOverride: t.Optional(NullableChatRenderingOverrideSchema,),
  storyMode: t.Optional(t.Boolean(),),
  gmGuidance: t.Optional(GmGuidanceSchema,),
  type: t.Optional(t.UnionEnum(["llm", "human", "hybrid",],),),
  humanGM: t.Optional(t.Object({ actorId: t.String(), notifications: t.Boolean(), },),),
  escalationThreshold: t.Optional(t.Number({ minimum: 0, maximum: 1, },),),
  llmConfig: t.Optional(
    t.Object({
      model: t.String(),
      provider: t.String(),
      systemPrompt: t.String(),
      temperature: t.Number(),
      maxTokens: t.Number(),
    },),
  ),
  actorModels: t.Optional(
    t.Record(t.String(), t.Object({ model: t.String(), provider: t.String(), },),),
  ),
  // ── VN presentation keys (mutable once a chat is online) ──
  visualNovel: t.Optional(t.Boolean(),),
  vnLayout: t.Optional(t.UnionEnum(["overlay", "below", "split",],),),
  vnTypewriter: t.Optional(t.Boolean(),),
  vnTypewriterSpeed: t.Optional(t.Number(),),
  vnTransition: t.Optional(t.UnionEnum(["fade", "cut", "dissolve", "slide", "wipe",],),),
  vnAutoAdvance: t.Optional(t.Boolean(),),
  vnImageScaling: t.Optional(t.UnionEnum(["contain", "cover", "fill", "auto",],),),
  vnAutoAdvanceDelay: t.Optional(t.Number({ minimum: 0, },),),
  vnDialogueBoxOpacity: t.Optional(t.Number({ minimum: 0, maximum: 1, },),),
  vnPortraitSize: t.Optional(t.Number({ minimum: 0, },),),
  vnSplitRatio: t.Optional(t.Number({ minimum: 0, maximum: 100, },),),
  responseLengthPreset: t.Optional(t.UnionEnum(["short", "medium", "long", "custom",],),),
  responseLengthCustom: t.Optional(t.Number({ minimum: 50, maximum: 2000, },),),
  outputStyle: t.Optional(t.Union([
    t.Object({
      preset: t.Optional(OutputStylePresetSchema,),
      customInstruction: t.Optional(t.String(),),
      intensity: t.Optional(t.Number({ minimum: 0, maximum: 1, },),),
    },),
    t.Null(),
  ],),),
},);

// ── Response schemas ──────────────────────────────────────

export const ErrorResponse = t.Object({
  error: t.String(),
  code: t.Optional(t.String(),),
  details: t.Optional(t.Any(),),
},);

export const SuccessResponse = t.Object({
  data: t.Any(),
},);

/**
 * Generic list envelope: `{ data: T[], total }` for paginated list responses.
 * @param itemSchema - TypeBox schema for items in the `data` array
 * @returns TypeBox object schema `{ data: T[], total: number }`.
 */
export function ListResponse(itemSchema: Parameters<typeof t.Array>[0],) {
  return t.Object({
    data: t.Array(itemSchema,),
    total: t.Number(),
    page: t.Number(),
    pageSize: t.Number(),
  },);
}
