// SPDX-License-Identifier: LGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Loop Lore Contributors

/**
 * Markdown stale-link guard.
 *
 * Scans Markdown files and flags intra-repo links whose target does not
 * resolve to an existing repository path. Catches links that rot when
 * files/epics/tickets are renamed or deleted (common in `.plan/` and
 * `docs/` where epics reference tickets and vice-versa).
 *
 * What is checked:
 * - Inline links `[text](target)` and images `![alt](target)`
 * - Reference links `[text][ref]` (ref resolved via `[ref]: target`)
 * - Relative paths (`../epics/x.md`, `tickets/TASK-x.md`, `/docs/...`)
 *   are resolved against the repo root (for `/`-prefixed) or the
 *   containing file's directory (for relative `./`/`../`).
 * - Anchors have their `#fragment` stripped before file resolution.
 *
 * What is skipped:
 * - Absolute web URLs (`http://`, `https://`, `mailto:`, `ftp://`)
 * - Anchor-only links (`[x](#section)`) — same-file anchors
 * - Code spans and fenced code blocks (paths in backticks/code)
 * - Auto-links `<https://...>`
 *
 * Modes:
 * - Default: reports broken links, exits 1 if any (blocking in `bun check`)
 * - `--fix`: rewrites non-existent relative targets to `<file> (missing)` —
 *   only for links that point at other tracks of the repo; prints the diff.
 *
 * Usage: `bun run scripts/check-md-links.ts`
 */
import { Glob, } from "bun";
import { existsSync, } from "node:fs";
import { dirname, join, resolve, } from "node:path";

const PROJECT_ROOT = import.meta.dir + "/..";
const GLOBS = ["docs/**/*.md", ".plan/**/*.md",];

// ── Markdown parsing (lightweight, no deps) ─────────────────────

/** Strip fenced code blocks: ```…``` and indented 4-space code. */
function stripCodeBlocks(text: string,): string {
  return text
    .replace(/```[\s\S]*?```/g, "",)
    .replace(/(?:^|\n)( {4}|\t)[^\n]*/g, "",);
}

/** Strip inline code spans `...`. */
function stripInlineCode(text: string,): string {
  return text.replace(/`[^`]*`/g, "",);
}

/** Collect `[label](target)` and `[label][ref]` usages. */
function collectLinks(text: string,): string[] {
  const links: string[] = [];
  // Inline: [text](target "title"?) — capture the URL portion
  const inlineRe = /\[([^\]]*)\]\((\s*<?([^)\s]+?|...)?>?(?:\s+"[^"]*")?\s*)\)/g;
  let m: RegExpExecArray | null;
  while ((m = inlineRe.exec(text,)) !== null) {
    const inner = m[2] ?? "";
    const target = inner.match(/([^)\s"']+)/,);
    if (target) { links.push(target[1],); }
  }
  // Reference definitions + usages (simplified: resolve refs inline)
  const defRe = /^\[([^\]]+)\]:\s*(.+)$/gm;
  const defs = new Map<string, string>();
  while ((m = defRe.exec(text,)) !== null) {
    defs.set(m[1].toLowerCase(), m[2].trim(),);
  }
  const useRe = /\[[^\]]*\]\[([^\]]+)\]/g;
  while ((m = useRe.exec(text,)) !== null) {
    const target = defs.get(m[1].toLowerCase(),);
    if (target) { links.push(target,); }
  }
  return links;
}

// ── Target classification ───────────────────────────────────────

/** True if the target is an absolute/external URL we should not resolve. */
function isExternal(target: string,): boolean {
  return /^(https?:|mailto:|ftp:|tel:|data:)/i.test(target,);
}

/** True if target is anchor-only (same file fragment). */
function isAnchorOnly(target: string,): boolean {
  return target.startsWith("#",);
}

/** Resolve a relative target path against the containing file. */
function resolveTarget(target: string, containingFile: string,): string | null {
  // Strip anchor fragment
  const pathPart = target.split("#",)[0];
  if (!pathPart) { return null; }

  // Repo-root-relative prefixes used throughout docs/plan.
  // Strip a leading slash, then resolve from repo root.
  const trimmed = pathPart.replace(/^\//, "",);
  if (trimmed.startsWith("docs/",) || trimmed.startsWith(".plan/",) || trimmed.startsWith("src/",)) {
    return join(PROJECT_ROOT, trimmed,);
  }
  // `/plan/...` is shorthand for `.plan/...` in some prose docs.
  if (trimmed.startsWith("plan/",) || trimmed === "plan") {
    return join(PROJECT_ROOT, trimmed.replace(/^plan/, ".plan",),);
  }
  // Other `/`-prefixed paths are docs-site routes (/meta/issues, /api/...)
  // regenerated by VitePress — not in-repo files, so not resolvable here.
  if (pathPart.startsWith("/",)) { return null; }
  // Else relative to the containing file's directory (always absolute).
  return resolve(dirname(containingFile,), pathPart,);
}

// ── Main ────────────────────────────────────────────────────────

let broken = 0;
const seen = new Set<string>();

async function checkFile(file: string,): Promise<void> {
  if (seen.has(file,)) { return; }
  seen.add(file,);
  const raw = await Bun.file(file,).text();
  const body = stripInlineCode(stripCodeBlocks(raw,),);
  const links = collectLinks(body,);

  for (const target of links) {
    if (isExternal(target,) || isAnchorOnly(target,)) { continue; }

    const resolved = resolveTarget(target, file,);
    if (!resolved) { continue; }
    if (!existsSync(resolved,)) {
      broken++;
      console.error(`[md-links] ${file} → broken target: ${target} (resolved ${resolved})`,);
    }
  }
}

async function main(): Promise<void> {
  const files = new Set<string>();
  for (const g of GLOBS) {
    for await (const f of new Glob(g,).scan({ cwd: PROJECT_ROOT, },)) {
      files.add(join(PROJECT_ROOT, f,),);
    }
  }

  for (const file of files) { await checkFile(file,); }

  if (broken > 0) {
    console.error(`\n[md-links] ${broken} broken internal link(s) found. Fix target paths or update the doc.`,);
    process.exit(1,);
  }
  console.log(`[md-links] OK — ${files.size} markdown file(s), all internal links resolve.`,);
}

main().catch((err,) => {
  console.error("[md-links] failed:", err.message,);
  process.exit(1,);
},);
