// SPDX-License-Identifier: LGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Loop Lore Contributors

/**
 * generate-schema-fuzz.ts — emits src/validation/schema-fuzz.generated.test.ts.
 *
 * Walks every named export of the validation schema barrel, keeps the ones
 * that are TypeBox schemas, and writes one `describe` block per schema:
 *
 *   - "accepts generated values"   → schemaToArbitrary only emits valid values
 *   - "survives a JSON round-trip" → only for isJsonRoundTrippable schemas
 *
 * Every property runs with a FIXED seed, so a regenerated file produces the
 * same values on every machine and CI never flakes on a lucky draw.
 *
 * Usage:
 *   bun run scripts/generate-schema-fuzz.ts            # write the file
 *   bun run scripts/generate-schema-fuzz.ts --check    # exit 1 if stale
 */

import {
  isJsonRoundTrippable,
  isTypeBoxSchema,
} from "../src/test-utils/schema-arbitrary.ts";
import * as schemas from "../src/validation/schemas/index.ts";

const OUT_PATH = new URL("../src/validation/schema-fuzz.generated.test.ts", import.meta.url,);

/** Fixed run count + seed — a regenerated file must replay identical values. */
const FC_RUNS = { numRuns: 100, seed: 20260101, };

/** Schema names in sorted order, so regeneration is byte-identical. */
function discoverSchemas(): { names: string[]; nonSchema: number; throwing: number } {
  const namespace = schemas as unknown as Record<string, unknown>;
  const names: string[] = [];
  let nonSchema = 0;
  let throwing = 0;
  for (const key of Object.keys(namespace,).sort()) {
    let value: unknown;
    try {
      // A barrel may re-export a live binding whose getter throws on access.
      value = namespace[key];
    } catch {
      throwing++;
      continue;
    }
    if (isTypeBoxSchema(value,)) { names.push(key,); }
    else { nonSchema++; }
  }
  return { names, nonSchema, throwing, };
}

/** One schema's two (or one) cases, as source lines. */
function casesFor(name: string,): string[] {
  const schema = (schemas as unknown as Record<string, never>)[name];
  const cases = [`  test("accepts generated values", () => checkAllValid(schemas.${name}));`,];
  if (isJsonRoundTrippable(schema,)) {
    cases.push(`  test("survives a JSON round-trip", () => checkJsonRoundTrip(schemas.${name}));`,);
  }
  return cases;
}

/** Render the whole test file. Pure — same barrel in, same bytes out. */
function render(names: string[],): string {
  const lines: string[] = [
    "// SPDX-License-Identifier: LGPL-3.0-or-later",
    "// SPDX-FileCopyrightText: 2026 Loop Lore Contributors",
    "// AUTO-GENERATED by scripts/generate-schema-fuzz.ts — DO NOT EDIT MANUALLY.",
    "// Regenerate: bun run scripts/generate-schema-fuzz.ts",
    "",
    "/**",
    " * Schema fuzz (property) tests for the validation schema barrel.",
    " *",
    " * Each `describe` block is one exported TypeBox schema. Arbitraries come",
    " * from `@/test-utils/schema-arbitrary`, which only emits schema-valid",
    " * values — a failure here means the mapper drifted from the schema.",
    " */",
    "",
    'import type { TSchema, } from "@sinclair/typebox";',
    'import { describe, expect, test, } from "bun:test";',
    'import { Value, } from "@sinclair/typebox/value";',
    'import fc from "fast-check";',
    "",
    'import { schemaToArbitrary, } from "@/test-utils/schema-arbitrary";',
    'import * as schemas from "@/validation/schemas";',
    "",
    "/** Fixed run count + seed — a regenerated file must replay identical values. */",
    `const FC_RUNS = { numRuns: ${FC_RUNS.numRuns}, seed: ${FC_RUNS.seed}, };`,
    "",
    "/** Every generated value must satisfy its own schema. */",
    "function checkAllValid(schema: TSchema): void {",
    "  fc.assert(",
    "    fc.property(schemaToArbitrary(schema), (v) => Value.Check(schema, v) === true),",
    "    FC_RUNS,",
    "  );",
    "}",
    "",
    "/** JSON.stringify must be lossless — no dropped keys, no coerced values. */",
    "function checkJsonRoundTrip(schema: TSchema): void {",
    "  fc.assert(",
    "    fc.property(schemaToArbitrary(schema), (v) => {",
    "      const round: unknown = JSON.parse(JSON.stringify(v));",
    "      expect(round).toEqual(v);",
    "    }),",
    "    FC_RUNS,",
    "  );",
    "}",
    "",
  ];
  for (const name of names) {
    lines.push(`describe("${name}", () => {`, ...casesFor(name,), "});", "",);
  }
  lines.push(`// ${names.length} schemas discovered by scripts/generate-schema-fuzz.ts.`,);
  return `${lines.join("\n",)}\n`;
}

// ── CLI ────────────────────────────────────────────────────────────────────
if (import.meta.main) {
  const { names, nonSchema, throwing, } = discoverSchemas();
  const content = render(names,);
  const outPath = OUT_PATH.pathname;

  if (process.argv.includes("--check",)) {
    const existing = await Bun.file(OUT_PATH,).text().catch(() => "");
    if (existing !== content) {
      console.error(
        `[schema-fuzz] ${outPath} is stale — run: bun run scripts/generate-schema-fuzz.ts`,
      );
      process.exit(1,);
    }
    console.log(`[schema-fuzz] check ok — ${names.length} schemas, up to date (${outPath})`,);
  } else {
    await Bun.write(OUT_PATH, content,);
    console.log(`[schema-fuzz] wrote ${outPath} — ${names.length} schemas`,);
  }

  const skipped = throwing > 0
    ? `${nonSchema} non-schema, ${throwing} throwing on access`
    : `${nonSchema} non-schema`;
  console.log(`[schema-fuzz] skipped ${skipped} export(s)`,);
}
