// SPDX-License-Identifier: LGPL-3.0-or-later,// SPDX-FileCopyrightText: 2026 Loop Lore Contributors,,/**, * Mock NPC data + standing tiers for the NPC management UI (frontend dev)., */

import type { NpcData, NpcRelationship, StandingTier, } from "./chat-types/npc.js";

export const STANDING_TIERS: StandingTier[] = [
  { name: "Hated", min: -100, max: -76, color: "var(--accent-red)", },
  { name: "Hostile", min: -75, max: -60, color: "var(--accent-red)", },
  { name: "Unfriendly", min: -59, max: -40, color: "var(--accent-orange)", },
  { name: "Neutral", min: -39, max: 39, color: "var(--text-muted)", },
  { name: "Friendly", min: 40, max: 59, color: "var(--accent-green)", },
  { name: "Honored", min: 60, max: 74, color: "var(--accent-blue)", },
  { name: "Revered", min: 75, max: 89, color: "var(--accent-purple)", },
  { name: "Exalted", min: 90, max: 100, color: "var(--accent-gold)", },
];

// ── Mock Data ───────────────────────────────────────────────
export const MOCK_NPCS: NpcData[] = [
  {
    id: "npc-merchant",
    name: "Merchant",
    role: "Merchant",
    location: "Village Market",
    disposition: "friendly",
    dispositionScore: 75,
    description: "A shrewd trader with a warm smile and sharp eyes for profit.",
    stats: [
      { name: "Persuasion", value: 15, },
      { name: "Intimidation", value: 5, },
      { name: "Commerce", value: 20, },
    ],
    inventory: [
      { id: "iron-sword", name: "Iron Sword", category: "weapon", quantity: 3, },
      { id: "health-potion", name: "Health Potion", category: "consumable", quantity: 12, },
      { id: "mana-potion", name: "Mana Potion", category: "consumable", quantity: 8, },
      { id: "shield", name: "Shield", category: "armor", quantity: 2, },
    ],
    schedule: [
      { startTime: "06:00", endTime: "18:00", activity: "Trading", location: "Market", },
      { startTime: "18:00", endTime: "22:00", activity: "Resting", location: "Inn", },
      { startTime: "22:00", endTime: "06:00", activity: "Sleeping", location: "Home", },
    ],
    factionId: "faction-merchants",
    portrait: null,
  },
  {
    id: "npc-guard",
    name: "Guard",
    role: "City Guard",
    location: "Town Gate",
    disposition: "neutral",
    dispositionScore: 10,
    description: "A vigilant protector of the town, stern but fair.",
    stats: [
      { name: "Strength", value: 14, },
      { name: "Perception", value: 12, },
      { name: "Intimidation", value: 10, },
    ],
    inventory: [
      { id: "guard-spear", name: "Guard Spear", category: "weapon", quantity: 1, },
      { id: "chainmail", name: "Chainmail", category: "armor", quantity: 1, },
    ],
    schedule: [
      { startTime: "06:00", endTime: "18:00", activity: "Patrolling", location: "Town Gate", },
      { startTime: "18:00", endTime: "22:00", activity: "Off Duty", location: "Barracks", },
      { startTime: "22:00", endTime: "06:00", activity: "Sleeping", location: "Barracks", },
    ],
    factionId: "faction-guard",
    portrait: null,
  },
  {
    id: "npc-blacksmith",
    name: "Blacksmith",
    role: "Blacksmith",
    location: "Forge",
    disposition: "friendly",
    dispositionScore: 60,
    description: "A master craftsman who shapes metal into marvels.",
    stats: [
      { name: "Crafting", value: 18, },
      { name: "Strength", value: 16, },
      { name: "Commerce", value: 10, },
    ],
    inventory: [
      { id: "steel-ingot", name: "Steel Ingot", category: "material", quantity: 20, },
      { id: "iron-ingot", name: "Iron Ingot", category: "material", quantity: 30, },
      { id: "hammer", name: "Smithing Hammer", category: "tool", quantity: 2, },
    ],
    schedule: [
      { startTime: "05:00", endTime: "19:00", activity: "Smithing", location: "Forge", },
      { startTime: "19:00", endTime: "22:00", activity: "Resting", location: "Inn", },
      { startTime: "22:00", endTime: "05:00", activity: "Sleeping", location: "Home", },
    ],
    factionId: "faction-merchants",
    portrait: null,
  },
  {
    id: "npc-healer",
    name: "Healer",
    role: "Healer",
    location: "Temple",
    disposition: "honored",
    dispositionScore: 80,
    description: "A devoted priest who tends to the sick and wounded.",
    stats: [
      { name: "Healing", value: 20, },
      { name: "Wisdom", value: 16, },
      { name: "Persuasion", value: 12, },
    ],
    inventory: [
      { id: "holy-symbol", name: "Holy Symbol", category: "key_item", quantity: 1, },
      { id: "healing-herbs", name: "Healing Herbs", category: "material", quantity: 15, },
    ],
    schedule: [
      { startTime: "04:00", endTime: "12:00", activity: "Prayer", location: "Temple", },
      { startTime: "12:00", endTime: "20:00", activity: "Healing", location: "Temple", },
      { startTime: "20:00", endTime: "04:00", activity: "Meditation", location: "Temple Quarters", },
    ],
    factionId: "faction-temple",
    portrait: null,
  },
  {
    id: "npc-stranger",
    name: "Mysterious Stranger",
    role: "Unknown",
    location: "Tavern",
    disposition: "neutral",
    dispositionScore: 0,
    description: "A cloaked figure who speaks in riddles and watches from the shadows.",
    stats: [
      { name: "Stealth", value: 18, },
      { name: "Deception", value: 16, },
      { name: "Perception", value: 14, },
    ],
    inventory: [],
    schedule: [
      { startTime: "20:00", endTime: "02:00", activity: "Lurking", location: "Tavern", },
      { startTime: "02:00", endTime: "20:00", activity: "Gone", location: "Unknown", },
    ],
    factionId: null,
    portrait: null,
  },
];

export const MOCK_RELATIONSHIPS: NpcRelationship[] = [
  {
    id: "rel-1",
    fromId: "player",
    fromName: "Player",
    toId: "npc-merchant",
    toName: "Merchant",
    type: "friend",
    strength: 75,
    history: ["Traded多次", "Helped with delivery",],
  },
  {
    id: "rel-2",
    fromId: "player",
    fromName: "Player",
    toId: "npc-guard",
    toName: "Guard",
    type: "neutral",
    strength: 10,
    history: ["Brief encounter",],
  },
  {
    id: "rel-3",
    fromId: "player",
    fromName: "Player",
    toId: "npc-healer",
    toName: "Healer",
    type: "ally",
    strength: 80,
    history: ["Healed wounds", "Shared knowledge",],
  },
  {
    id: "rel-4",
    fromId: "npc-merchant",
    fromName: "Merchant",
    toId: "npc-blacksmith",
    toName: "Blacksmith",
    type: "friend",
    strength: 60,
    history: ["Business partners",],
  },
  {
    id: "rel-5",
    fromId: "npc-guard",
    fromName: "Guard",
    toId: "npc-stranger",
    toName: "Mysterious Stranger",
    type: "rival",
    strength: -30,
    history: ["Suspicious of stranger",],
  },
  {
    id: "rel-6",
    fromId: "npc-healer",
    fromName: "Healer",
    toId: "npc-merchant",
    toName: "Merchant",
    type: "friend",
    strength: 40,
    history: ["Heals merchant's ailments",],
  },
];
