// SPDX-License-Identifier: LGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Loop Lore Contributors

export interface WorldEditState {
  loading: boolean;
  error: boolean;
  activeTab: string;
  world: { id: string; name: string; description: string | null; lore: string | null; tags: string[] } | null;
  tagsStr: string;
  locations: {
    id: string;
    name: string;
    description: string | null;
    parent_location_id: string | null;
  }[];
  locationsLoaded: boolean;
  loadingLocations: boolean;
  showAddForm: boolean;
  newLocName: string;
  newLocDesc: string;
  newLocParentId: string;
  newLocConnections: string[];
  editingLocationId: string;
  expandedLoc: string;
  editLocName: string;
  editLocDesc: string;
  items: {
    id: string;
    name: string;
    description: string | null;
    category: string;
    rarity: string;
    value: number;
    weight: number;
    stackable: boolean;
    max_stack: number;
    properties: Record<string, unknown> | null;
  }[];
  itemsLoaded: boolean;
  loadingItems: boolean;
  newItemName: string;
  newItemDesc: string;
  newItemCategory: string;
  newItemRarity: string;
  newItemValue: string;
  newItemWeight: string;
  expandedItem: string;
  editItemName: string;
  editItemDesc: string;
  editItemCategory: string;
  editItemRarity: string;
  editItemValue: string;
  editItemWeight: string;
  locName(locId: string | null,): string;
  instances: {
    id: string;
    item_id: string;
    location_id: string | null;
    owner_actor_id: string | null;
    quantity: number;
    visibility: string;
    created_at: string;
  }[];
  instancesLoaded: boolean;
  loadingInstances: boolean;
  placeLocationId: string;
  placeQuantity: string;
  worldId: string | null;
  invites: {
    id: string;
    worldId: string;
    code: string;
    createdAt: string;
    expiresAt: string | null;
    maxUses: number | null;
    uses: number;
    status: string;
  }[];
  loadingInvites: boolean;
  invitesLoaded: boolean;
  newInviteMaxUses: string;
  showInviteForm: boolean;
  init(): void;
  saveWorld(): Promise<void>;
  loadLocations(): Promise<void>;
  addLocation(): Promise<void>;
  deleteLocation(locId: string,): Promise<void>;
  expandLoc(locId: string,): void;
  saveLocation(locId: string,): Promise<void>;
  loadItems(): Promise<void>;
  addItem(): Promise<void>;
  expandItem(itemId: string,): void;
  saveItem(itemId: string,): Promise<void>;
  deleteItem(itemId: string,): Promise<void>;
  loadInstances(itemId: string,): Promise<void>;
  placeInstance(itemId: string,): Promise<void>;
  destroyInstance(instanceId: string,): Promise<void>;
  loadInvites(): Promise<void>;
  createInvite(): Promise<void>;
  copyInviteCode(code: string,): void;
  revokeInvite(inviteId: string,): Promise<void>;
}
